DISCOUNT_NOTIFICATION_MODE = 'discount'
SUBSCRIPTION_NOTIFICATION_MODE = 'subscription'
SYSTEM_NOTIFICATION_MODE = 'system'
PARTNER_MODE = 'partner'

NOTIFICATION_MODES = (
    (DISCOUNT_NOTIFICATION_MODE, DISCOUNT_NOTIFICATION_MODE.capitalize()),
    (SUBSCRIPTION_NOTIFICATION_MODE, SUBSCRIPTION_NOTIFICATION_MODE.capitalize()),
    (SYSTEM_NOTIFICATION_MODE, SYSTEM_NOTIFICATION_MODE.capitalize()),
    (PARTNER_MODE, PARTNER_MODE.capitalize())
)

ACCEPT_DISCOUNT_TYPE = 'accept_discount'
DECLINE_DISCOUNT_TYPE = 'decline_discount'
NEW_DISCOUNT_TYPE = 'new_discount'
NEW_ORGANIZATION = 'new_organization'
FOLLOWED_TO_ORGANIZATION_TYPE = 'followed_to_organization'
ORGANIZATION_FOLLOWED_TYPE = 'organization_followed'
SYSTEM_TYPE = 'system'

NOTIFICATION_TYPES = (
    (ACCEPT_DISCOUNT_TYPE, ACCEPT_DISCOUNT_TYPE),
    (DECLINE_DISCOUNT_TYPE, DECLINE_DISCOUNT_TYPE),
    (NEW_DISCOUNT_TYPE, NEW_DISCOUNT_TYPE),
    (NEW_ORGANIZATION, NEW_ORGANIZATION),
    (FOLLOWED_TO_ORGANIZATION_TYPE, FOLLOWED_TO_ORGANIZATION_TYPE),
    (ORGANIZATION_FOLLOWED_TYPE, ORGANIZATION_FOLLOWED_TYPE),
    (SYSTEM_TYPE, SYSTEM_TYPE),

)

FOLLOWED_TO_ORGANIZATION_TITLE = 'На вашу организацию подписались'
ORGANIZATION_FOLLOWED_TITLE = 'Вы подписались на {org_title}'
DISCOUNT_COMPLETE_USER_TITLE = 'Вам провели скидку {discount_percent} %'
DISCOUNT_COMPLETE_DESCRIPTION = 'Итого со скидкой: {final_amount} {currency}'

DISCOUNT_COMPLETE_TITLE = 'Вы провели скидку {discount_percent} %'
