DISCOUNT_NOTIFICATION_MODE = 'discount'
SUBSCRIPTION_NOTIFICATION_MODE = 'subscription'
SYSTEM_NOTIFICATION_MODE = 'system'
PERSONAL_NOTIFICATION_MODE = 'personal'
PARTNER_MODE = 'partner'
PERSONAL_MODE = 'personal'

NOTIFICATION_MODES = (
    (DISCOUNT_NOTIFICATION_MODE, DISCOUNT_NOTIFICATION_MODE.capitalize()),
    (SUBSCRIPTION_NOTIFICATION_MODE, SUBSCRIPTION_NOTIFICATION_MODE.capitalize()),
    (SYSTEM_NOTIFICATION_MODE, SYSTEM_NOTIFICATION_MODE.capitalize()),
    (PARTNER_MODE, PARTNER_MODE.capitalize()),
    (PERSONAL_NOTIFICATION_MODE, PERSONAL_NOTIFICATION_MODE.capitalize())
)

ACCEPT_PARTNERSHIP_TYPE = 'accept_partnership'
DECLINE_PARTNERSHIP_TYPE = 'decline_partnership'
REQUEST_PARTNERSHIP_TYPE = 'request_partnership'

RECRUIT_JOB_TYPE = 'recruited'
CHANGE_JOB_POSITION_TYPE = 'changed_position'
DISMISS_JOB_TYPE = 'dismissed'

ACCEPT_DISCOUNT_TYPE = 'accept_discount'
ACCEPT_SELLER_DISCOUNT_TYPE = 'accepted_seller_discount'
DECLINE_DISCOUNT_TYPE = 'decline_discount'
NEW_DISCOUNT_TYPE = 'new_discount'
NEW_ORGANIZATION = 'new_organization'
FOLLOWED_TO_ORGANIZATION_TYPE = 'followed_to_organization'
ORGANIZATION_FOLLOWED_TYPE = 'organization_followed'
SYSTEM_TYPE = 'system'

NOTIFICATION_TYPES = (
    (ACCEPT_DISCOUNT_TYPE, ACCEPT_DISCOUNT_TYPE),
    (DECLINE_DISCOUNT_TYPE, DECLINE_DISCOUNT_TYPE),
    (NEW_DISCOUNT_TYPE, NEW_DISCOUNT_TYPE),
    (NEW_ORGANIZATION, NEW_ORGANIZATION),
    (FOLLOWED_TO_ORGANIZATION_TYPE, FOLLOWED_TO_ORGANIZATION_TYPE),
    (ORGANIZATION_FOLLOWED_TYPE, ORGANIZATION_FOLLOWED_TYPE),
    (SYSTEM_TYPE, SYSTEM_TYPE),
    (ACCEPT_PARTNERSHIP_TYPE, ACCEPT_PARTNERSHIP_TYPE),
    (DECLINE_PARTNERSHIP_TYPE, DECLINE_PARTNERSHIP_TYPE),
    (REQUEST_PARTNERSHIP_TYPE, REQUEST_PARTNERSHIP_TYPE),
    (ACCEPT_SELLER_DISCOUNT_TYPE, ACCEPT_SELLER_DISCOUNT_TYPE),
    (RECRUIT_JOB_TYPE, RECRUIT_JOB_TYPE),
    (CHANGE_JOB_POSITION_TYPE, CHANGE_JOB_POSITION_TYPE),
    (DISMISS_JOB_TYPE, DISMISS_JOB_TYPE)

)

FOLLOWED_TO_ORGANIZATION_TITLE = 'На вашу организацию подписались'
ORGANIZATION_FOLLOWED_TITLE = 'Вы подписались на {org_title}'
DISCOUNT_COMPLETE_USER_TITLE = 'Вам провели скидку {discount_percent} %'
DISCOUNT_COMPLETE_DESCRIPTION = 'Итого со скидкой: {final_amount} {currency}'
DISCOUNT_COMPLETE_TITLE = 'Вы провели скидку {discount_percent} %'

NEW_DISCOUNT_TITLE = 'Доступна новая скидка {percent}%'
NEW_DISCOUNT_DESCRIPTION = '{address} '
PARTNERSHIP_REQUEST_TITLE = '{sender_organization} хочет стать партнером {recipient_organization}'
PARTNERSHIP_REQUEST_DESCRIPTION = '{address} '
SUBSCRIPTION_NOTIFICATION_DESCRIPTION = '{address} '
TRANSACTION_DECLINED_NOTIFICATION_TITLE = 'Вам отменили сделку'
YOU_DECLINED_NOTIFICATION_TITLE = 'Вы отменили сделку'
TRANSACTION_DECLINED_NOTIFICATION_DESCRIPTION = 'Скидка {savings} {currency}'

NEW_ORGANIZATION_TITLE = 'Новая организация доступна для вас'
NEW_ORGANIZATION_DESCRIPTION = '{organization_title} '

RECRUIT_JOB_TITLE = 'Вас приняли на работу'
RECRUIT_JOB_DESCRIPTION = '{position} '

CHANGE_JOB_POSITION_TITLE = 'Вы перешли на другую должность'
CHANGE_JOB_POSITION_DESCRIPTION = '{old_position} на {new_position}'
