DISCOUNT_NOTIFICATION_MODE = 'discount'
SUBSCRIPTION_NOTIFICATION_MODE = 'subscription'
SYSTEM_NOTIFICATION_MODE = 'system'
PARTNER_MODE = 'partner'
PERSONAL_MODE = 'personal'

NOTIFICATION_MODES = (
    (DISCOUNT_NOTIFICATION_MODE, DISCOUNT_NOTIFICATION_MODE.capitalize()),
    (SUBSCRIPTION_NOTIFICATION_MODE, SUBSCRIPTION_NOTIFICATION_MODE.capitalize()),
    (SYSTEM_NOTIFICATION_MODE, SYSTEM_NOTIFICATION_MODE.capitalize()),
    (PARTNER_MODE, PARTNER_MODE.capitalize()),
    (PERSONAL_MODE, PERSONAL_MODE.capitalize())
)

ACCEPT_PARTNERSHIP_TYPE = 'accepted_partnership'
DECLINE_PARTNERSHIP_TYPE = 'declined_partnership'
REQUEST_PARTNERSHIP_TYPE = 'requested_partnership'

ACCEPT_PARTNERSHIP_RECIPIENT_TYPE = 'accepted_partnership_recipient'
DECLINE_PARTNERSHIP_RECIPIENT_TYPE = 'declined_partnership_recipient'
REQUEST_PARTNERSHIP_RECIPIENT_TYPE = 'requested_partnership_recipient'

RECRUIT_JOB_TYPE = 'recruit'
GET_JOB_TYPE = 'get_job'
CHANGE_JOB_POSITION_TYPE = 'changed_position'
CHANGE_JOB_POSITION_OWNER_TYPE = 'changed_position_as_owner'
DISMISS_JOB_TYPE = 'dismissed'
QUIT_JOB_TYPE = 'quit'

ACCEPT_DISCOUNT_TYPE = 'accept_discount'
ACCEPT_SELLER_DISCOUNT_TYPE = 'accepted_seller_discount'
DECLINE_DISCOUNT_TYPE = 'decline_discount'
NEW_DISCOUNT_TYPE = 'new_discount'
NEW_ORGANIZATION = 'new_organization'
FOLLOWED_TO_ORGANIZATION_TYPE = 'followed_to_organization'
ORGANIZATION_FOLLOWED_TYPE = 'organization_followed'
SYSTEM_TYPE = 'system'
ORGANIZATION_MESSAGE_TYPE = 'organization_message'
ORGANIZATION_MESSAGE_SENDER_TYPE = 'sent_message'

ORGANIZATION_GAVE_TYPE = 'gave_organization'
ORGANIZATION_OWN_TYPE = 'owned_organization'

ATTENDANCE_IN = 'attendance_in'
ATTENDANCE_OUT = 'attendance_out'
CHECK_ATTENDANCE_IN = 'check_attendance_in'
CHECK_ATTENDANCE_OUT = 'check_attendance_out'

WITHDRAW_CASHBACK_CLIENT = 'withdraw_cashback_client'
CHARGE_CASHBACK_CLIENT = 'charge_cashback_client'

WITHDRAW_CASHBACK_SELLER = 'withdraw_cashback_seller'
CHARGE_CASHBACK_SELLER = 'charge_cashback_seller'

NOTIFICATION_TYPES = (
    (WITHDRAW_CASHBACK_CLIENT, WITHDRAW_CASHBACK_CLIENT),
    (CHARGE_CASHBACK_CLIENT, CHARGE_CASHBACK_CLIENT),
    (WITHDRAW_CASHBACK_SELLER, WITHDRAW_CASHBACK_SELLER),
    (CHARGE_CASHBACK_SELLER, CHARGE_CASHBACK_SELLER),
    (CHECK_ATTENDANCE_IN, CHECK_ATTENDANCE_IN),
    (CHECK_ATTENDANCE_OUT, CHECK_ATTENDANCE_OUT),
    (ATTENDANCE_IN, ATTENDANCE_IN),
    (ATTENDANCE_OUT, ATTENDANCE_OUT),
    (ACCEPT_DISCOUNT_TYPE, ACCEPT_DISCOUNT_TYPE),
    (DECLINE_DISCOUNT_TYPE, DECLINE_DISCOUNT_TYPE),
    (NEW_DISCOUNT_TYPE, NEW_DISCOUNT_TYPE),
    (NEW_ORGANIZATION, NEW_ORGANIZATION),
    (FOLLOWED_TO_ORGANIZATION_TYPE, FOLLOWED_TO_ORGANIZATION_TYPE),
    (ORGANIZATION_FOLLOWED_TYPE, ORGANIZATION_FOLLOWED_TYPE),
    (SYSTEM_TYPE, SYSTEM_TYPE),
    (ACCEPT_PARTNERSHIP_TYPE, ACCEPT_PARTNERSHIP_TYPE),
    (DECLINE_PARTNERSHIP_TYPE, DECLINE_PARTNERSHIP_TYPE),
    (REQUEST_PARTNERSHIP_TYPE, REQUEST_PARTNERSHIP_TYPE),
    (ACCEPT_SELLER_DISCOUNT_TYPE, ACCEPT_SELLER_DISCOUNT_TYPE),
    (RECRUIT_JOB_TYPE, RECRUIT_JOB_TYPE),
    (CHANGE_JOB_POSITION_TYPE, CHANGE_JOB_POSITION_TYPE),
    (DISMISS_JOB_TYPE, DISMISS_JOB_TYPE),
    (QUIT_JOB_TYPE, QUIT_JOB_TYPE),
    (CHANGE_JOB_POSITION_OWNER_TYPE, CHANGE_JOB_POSITION_OWNER_TYPE),
    (ORGANIZATION_MESSAGE_TYPE, ORGANIZATION_MESSAGE_TYPE),
    (ORGANIZATION_GAVE_TYPE, ORGANIZATION_GAVE_TYPE),
    (ORGANIZATION_OWN_TYPE, ORGANIZATION_OWN_TYPE),
    (ORGANIZATION_MESSAGE_SENDER_TYPE, ORGANIZATION_MESSAGE_SENDER_TYPE),
    (ACCEPT_PARTNERSHIP_RECIPIENT_TYPE, ACCEPT_PARTNERSHIP_RECIPIENT_TYPE),
    (DECLINE_PARTNERSHIP_RECIPIENT_TYPE, DECLINE_PARTNERSHIP_RECIPIENT_TYPE),
    (REQUEST_PARTNERSHIP_RECIPIENT_TYPE, REQUEST_PARTNERSHIP_RECIPIENT_TYPE)
)
ATTENDANCE_IN_TITLE = 'Вход {organization}'
ATTENDANCE_OUT_TITLE = 'Выход {organization}'
CHECK_ATTENDANCE_IN_TITLE = 'Пропуск на вход {organization}'
CHECK_ATTENDANCE_OUT_TITLE = 'Пропуск на выход {organization}'

ATTENDANCE_DESCRIPTION = 'Пропуск:'

FOLLOWED_TO_ORGANIZATION_TITLE = 'На вашу организацию подписались'
ORGANIZATION_FOLLOWED_TITLE = 'Вы подписались на {org_title}'
DISCOUNT_COMPLETE_USER_TITLE = 'Вам провели скидку {discount_percent} %'
DISCOUNT_COMPLETE_DESCRIPTION = 'Итого со скидкой: {final_amount} {currency}'
DISCOUNT_COMPLETE_TITLE = 'Вы провели скидку {discount_percent} %'

NEW_DISCOUNT_TITLE = 'Доступна новая скидка {percent} %'
NEW_CASHBACK_TITLE = 'Доступен новый кэшбек {percent} %'

NEW_DISCOUNT_DESCRIPTION = '{address} '
PARTNERSHIP_REQUEST_TITLE = '{sender_organization} хочет стать партнером {recipient_organization}'
PARTNERSHIP_REQUEST_DESCRIPTION = '{address} '
SUBSCRIPTION_NOTIFICATION_DESCRIPTION = '{address} '
TRANSACTION_DECLINED_NOTIFICATION_TITLE = 'Вам отменили сделку'
YOU_DECLINED_NOTIFICATION_TITLE = 'Вы отменили сделку'
TRANSACTION_DECLINED_NOTIFICATION_DESCRIPTION = 'Скидка {savings} {currency}'

NEW_ORGANIZATION_TITLE = 'Новая организация доступна для вас'
NEW_ORGANIZATION_DESCRIPTION = '{organization_title} '

RECRUIT_JOB_TITLE = 'Вы приняли на работу'
RECRUIT_JOB_DESCRIPTION = '{position} '

GET_JOB_TITLE = 'Вас приняли на работу {organization}'
GET_JOB_DESCRIPTION = '{position} '

CHANGE_JOB_POSITION_TITLE = 'Вас назначили на новую должность'
CHANGE_JOB_POSITION_DESCRIPTION = '{old_position} на {new_position}'

CHANGE_JOB_POSITION_OWNER_TITLE = 'Вы назначили другую должность'
CHANGE_JOB_POSITION_OWNER_DESCRIPTION = '{old_position} на {new_position}'

QUIT_JOB_TITLE = 'Вас уволили с работы {organization}'
QUIT_JOB_DESCRIPTION = '{position} '

DISMISS_JOB_TITLE = 'Вы уволили с работы'
DISMISS_JOB_DESCRIPTION = '{position} '

ORGANIZATION_MESSAGE_TITLE = 'Сообщение от '
ORGANIZATION_MESSAGE_PARTNERS_TITLE = 'Сообщение для партнеров '
ORGANIZATION_MESSAGE_PARTNERS_FOLLOWERS_TITLE = 'Сообщение подписчикам партнеров '
ORGANIZATION_MESSAGE_DESCRIPTION = '{content} '
ORGANIZATION_OWNER_MESSAGE_TITLE = 'Вы отправили сообщение'
ORGANIZATION_OWNER_MESSAGE_PARTNERS_TITLE = 'Вы отправили сообщение партнерам'
ORGANIZATION_OWNER_MESSAGE_PARTNERS_FOLLOWERS_TITLE = 'Вы отправили сообщение подписчикам партнеров'

ORGANIZATION_GAVE_TITLE = 'Вы передали права собственника {organization}'
ORGANIZATION_GAVE_DESCRIPTION = ' '

ORGANIZATION_OWN_TITLE = 'Поздравляем Вы стали собственником {organization}'
ORGANIZATION_OWN_DESCRIPTION = ' '

WITHDRAW_CASHBACK_CLIENT_TITLE = 'Поздравляем Вам сняли {amount} {currency} с кешбэка'
CHARGE_CASHBACK_CLIENT_TITLE = 'Поздравляем вам начислили кешбэк {amount} {currency}'

WITHDRAW_CASHBACK_SELLER_TITLE = 'Вы сняли {amount} {currency} с кешбека'
CHARGE_CASHBACK_SELLER_TITLE = 'Вы начислили кешбек {amount} {currency}'

