# Generated by Django 3.0.8 on 2020-12-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_parsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='http_s',
            field=models.CharField(blank=True, help_text='Example : 91.238.224.165:20196', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='socks5',
            field=models.CharField(blank=True, help_text='Example : 91.238.224.165:20196', max_length=25, null=True),
        ),
    ]
