# Generated by Django 3.1.7 on 2021-05-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_parsers', '0002_auto_20201224_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settings', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
