# Generated by Django 3.1.7 on 2021-05-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_parsers', '0003_logindevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindevice',
            name='for_getting_username',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proxy',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proxy',
            name='for_getting_username',
            field=models.BooleanField(default=False),
        ),
    ]
