# Generated by Django 3.1.7 on 2021-08-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_parsers', '0004_auto_20210527_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindevice',
            name='password',
            field=models.CharField(default='1234qwer/', max_length=255),
        ),
        migrations.AddField(
            model_name='logindevice',
            name='username',
            field=models.CharField(default='nikabenod', max_length=255),
        ),
    ]
