# Generated by Django 3.1.7 on 2022-11-22 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_parsers', '0006_auto_20210818_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindevice',
            name='proxy',
            field=models.OneToOneField(blank=True, help_text='Proxy server', null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram_parsers.proxy'),
        ),
    ]
