# Generated by Django 3.1.7 on 2022-12-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_parsers', '0007_logindevice_proxy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logindevice',
            name='proxy',
        ),
        migrations.AddField(
            model_name='logindevice',
            name='proxy_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logindevice',
            name='proxy_http_s',
            field=models.CharField(blank=True, help_text='Example : 91.238.224.165:20196', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='logindevice',
            name='proxy_login',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logindevice',
            name='proxy_password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logindevice',
            name='proxy_socks5',
            field=models.CharField(blank=True, help_text='Example : 91.238.224.165:20196', max_length=25, null=True),
        ),
    ]
