# Generated by Django 3.1.7 on 2022-12-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_parsers', '0008_auto_20221207_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindevice',
            name='is_broke',
            field=models.BooleanField(default=False, help_text='This login_device broke, please update settings'),
        ),
    ]
