# Generated by Django 3.1.7 on 2026-01-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_parsers', '0010_instagramapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramapi',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instagramapi',
            name='login',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
