# Generated by Django 3.1.7 on 2025-12-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0168_maalypayorganizationpaymentsystem_bank_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaalyPayOrganizationPaymentSystem',
            fields=[
            ],
            options={
                'verbose_name': 'Maaly Pay Organization Payment System',
                'verbose_name_plural': 'Maaly Pay Organization Payment Systems',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('organizations.maalypayorganizationpaymentsystem',),
        ),
        migrations.CreateModel(
            name='PaymentSystemMethod',
            fields=[
            ],
            options={
                'verbose_name': 'Payment System Method',
                'verbose_name_plural': 'Payment System Methods',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('organizations.paymentsystemmethod',),
        ),
        migrations.CreateModel(
            name='RegionalPaymentSystemSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Regional Payment System Settings',
                'verbose_name_plural': 'Regional Payment System Settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('organizations.regionalpaymentsystemsettings',),
        ),
    ]
