# Generated by Django 3.1.7 on 2026-03-13 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0072_alter_aipromptsettings_defaults'),
        ('organizations', '0194_auto_20260313_2210'),
        ('payments', '0002_proxy_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitgateSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Profitgate',
                'verbose_name_plural': 'Profitgate - Настройки регионов',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('organizations.regionalpaymentsystemsettings',),
        ),
        migrations.CreateModel(
            name='ProfitgateIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=255, verbose_name='Merchant ID')),
                ('endpoint_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endpoint ID')),
                ('api_secret', models.CharField(max_length=255, verbose_name='API Secret')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('currencies', models.ManyToManyField(blank=True, to='common.Currency', verbose_name='Поддерживаемые валюты')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profitgate_integration', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Profitgate - Настройка организации',
                'verbose_name_plural': 'Profitgate - Настройки организаций',
            },
        ),
        migrations.CreateModel(
            name='ProfitgateOrganizationPaymentSystem',
            fields=[
            ],
            options={
                'verbose_name': 'Настройки Profitgate для организации',
                'verbose_name_plural': 'Profitgate - Настройки организаций',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.profitgateintegration',),
        ),
    ]
