# Generated by Django 3.1.7 on 2021-07-16 12:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_transaction_display_time'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=225)),
                ('apartment', models.CharField(blank=True, max_length=36, null=True)),
                ('intercom', models.CharField(blank=True, max_length=36, null=True)),
                ('entrance', models.CharField(blank=True, max_length=36, null=True)),
                ('floor', models.CharField(blank=True, max_length=36, null=True)),
                ('phone', models.CharField(max_length=36)),
                ('comment', models.CharField(blank=True, max_length=150, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Customer location coordinates', null=True, srid=4326)),
                ('status', models.CharField(choices=[('delivery_status_taken_for_delivery', 'Taken for delivery'), ('delivery_status_set_for_delivery', 'Set for delivery'), ('delivery_status_rejected_by_delivery_service', 'Rejected by delivery service'), ('delivery_status_accepted_by_delivery_service', 'Accepted by delivery service'), ('delivery_status_delivered', 'Delivered'), ('delivery_status_rejected_by_customer', 'Rejected by customer')], default='delivery_status_set_for_delivery', max_length=255)),
                ('transaction', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_info', to='transactions.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
