# Generated by Django 3.1.7 on 2021-07-20 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_auto_20210216_1404'),
        ('delivery', '0002_deliveryinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfo',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_infos', to='common.city'),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='country',
            field=models.ForeignKey(default='KG', on_delete=django.db.models.deletion.PROTECT, related_name='delivery_infos', to='common.country'),
        ),
    ]
