# Generated by Django 3.1.7 on 2021-07-20 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0049_auto_20210716_0817'),
        ('delivery', '0003_auto_20210720_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfo',
            name='delivery_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_infos', to='organizations.organization'),
        ),
    ]
