# Generated by Django 3.1.7 on 2021-08-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliveryinfo_delivery_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfo',
            name='who_pays',
            field=models.CharField(choices=[('organization', 'Organization pays'), ('client', 'Client pays')], max_length=255, null=True),
        ),
    ]
