# Generated by Django 3.1.7 on 2021-08-05 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_version'),
        ('delivery', '0005_deliveryinfo_who_pays'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfo',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.currency'),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='status',
            field=models.CharField(choices=[('delivery_status_taken_for_delivery', 'Taken for delivery'), ('delivery_status_set_for_delivery', 'Set for delivery'), ('delivery_status_rejected_by_delivery_service', 'Rejected by delivery service'), ('delivery_status_accepted_by_delivery_service', 'Accepted by delivery service'), ('delivery_status_delivered', 'Delivered'), ('delivery_status_rejected_by_customer', 'Rejected by customer')], default=None, max_length=255, null=True),
        ),
    ]
