# Generated by Django 3.1.7 on 2021-08-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_auto_20210805_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=16, null=True),
        ),
    ]
