# Generated by Django 3.1.7 on 2021-08-10 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_version'),
        ('delivery', '0007_auto_20210810_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='currency',
            field=models.ForeignKey(default='KGS', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.currency'),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='status',
            field=models.CharField(choices=[('delivery_status_taken_for_delivery', 'Taken for delivery'), ('delivery_status_set_for_delivery', 'Set for delivery'), ('delivery_status_rejected_by_delivery_service', 'Rejected by delivery service'), ('delivery_status_delivered', 'Delivered'), ('delivery_status_rejected_by_customer', 'Rejected by customer')], default=None, max_length=255, null=True),
        ),
    ]
