# Generated by Django 3.1.7 on 2021-08-11 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0054_auto_20210811_1147'),
        ('delivery', '0008_auto_20210810_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryActionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('delivery_status_taken_for_delivery', 'Taken for delivery'), ('delivery_status_set_for_delivery', 'Set for delivery'), ('delivery_status_rejected_by_delivery_service', 'Rejected by delivery service'), ('delivery_status_delivered', 'Delivered'), ('delivery_status_rejected_by_customer', 'Rejected by customer')], max_length=255)),
                ('delivery_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='delivery.deliveryinfo')),
                ('delivery_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_history', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
