# Generated by Django 3.1.7 on 2021-08-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_deliveryactionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfo',
            name='delivery_finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='delivery_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
