# Generated by Django 3.1.7 on 2021-08-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_auto_20210816_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfo',
            name='delivery_rejected',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
