# Generated by Django 3.0.7 on 2020-06-26 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200625_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarycode',
            name='expiration_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
