# Generated by Django 3.0.7 on 2020-07-02 09:09
import uuid

from django.db import migrations


def generate_random_email(apps, schema_editor):
    User = apps.get_model('users', 'User')

    users = User.objects.all()

    for user in users:
        user.email = "{}@example.com".format(uuid.uuid4().hex[:6].upper())

        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_phonenumber_socialnetworkcontact'),
    ]

    operations = [
        migrations.RunPython(generate_random_email)
    ]
