# Generated by Django 3.1.7 on 2021-04-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210216_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_common_client',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
