# Generated by Django 3.1.7 on 2022-09-14 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210910_0528'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyOwnToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=40, verbose_name='Key')),
                ('user_agent', models.CharField(max_length=256)),
                ('ip', models.CharField(blank=True, max_length=256, null=True)),
                ('expired_time', models.DateTimeField(blank=True, null=True, verbose_name='expired_date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
    ]
