# Generated by Django 3.1.7 on 2022-09-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_myowntoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='myowntoken',
            name='device',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='myowntoken',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
