# Generated by Django 3.1.7 on 2022-09-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20220915_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myowntoken',
            name='user_agent',
        ),
    ]
