# Generated by Django 3.1.7 on 2022-09-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_myowntoken_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='myowntoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='myowntoken',
            name='expired_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
