# Generated by Django 3.1.7 on 2022-09-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20220916_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='myowntoken',
            name='log_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
