# Generated by Django 3.1.7 on 2022-09-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_myowntoken_log_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myowntoken',
            name='log_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
