# Generated by Django 3.1.7 on 2022-09-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20220916_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='myowntoken',
            name='version_app',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
