# Generated by Django 3.1.7 on 2022-09-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_myowntoken_version_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='myowntoken',
            name='operating_system',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
