# Generated by Django 3.1.7 on 2022-09-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_myowntoken_operating_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='myowntoken',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
