# Generated by Django 3.1.7 on 2022-09-27 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_myowntoken_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='myowntoken',
            name='last_active',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
