# Generated by Django 3.1.7 on 2022-09-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_myowntoken_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='myowntoken',
            name='expired_time_choice',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
