# Generated by Django 3.1.7 on 2024-05-02 06:21

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20230117_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=225)),
                ('apartment', models.CharField(blank=True, max_length=36, null=True)),
                ('intercom', models.CharField(blank=True, max_length=36, null=True)),
                ('entrance', models.CharField(blank=True, max_length=36, null=True)),
                ('floor', models.CharField(blank=True, max_length=36, null=True)),
                ('phone', models.CharField(max_length=36)),
                ('comment', models.CharField(blank=True, max_length=150, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Delivery location coordinates', null=True, srid=4326)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
