# Generated by Django 3.1.7 on 2024-05-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_deliveryaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='by_default',
            field=models.BooleanField(default=False),
        ),
    ]
