# Generated by Django 3.1.7 on 2025-05-21 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_deliveryaddress_by_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('profit_percent', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
