# Generated by Django 3.1.7 on 2025-05-22 10:05

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0146_paymentsystemmethod_code'),
        ('common', '0055_country_is_paid_subscription'),
        ('users', '0026_promocode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='total_profit',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='usage_count',
        ),
        migrations.CreateModel(
            name='ReferralTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profit_amount_usdt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_currency', models.ForeignKey(default='USD', on_delete=django.db.models.deletion.PROTECT, related_name='referral_transactions', to='common.currency')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_profits', to=settings.AUTH_USER_MODEL)),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_transactions', to='users.promocode')),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_promocodes', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.userorgsubscription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferralBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
