# Generated by Django 3.1.7 on 2025-05-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20250522_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralbalance',
            name='currency',
            field=models.CharField(default='USDT', max_length=255),
        ),
    ]
