# Generated by Django 3.1.7 on 2022-06-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitemsize',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='shopitemsize',
            unique_together={('format_size', 'order')},
        ),
    ]
