# Generated by Django 3.1.7 on 2022-06-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20220615_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatsize',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formatsize',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formatsize',
            name='name_tr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
