# Generated by Django 3.1.7 on 2022-06-16 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20220615_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriteriaSubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_tr', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormatCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_tr', models.CharField(max_length=255, null=True)),
                ('criteria_subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criteria_subcategories', to='stock.criteriasubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SizeFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('format_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_formats', to='stock.formatcriteria')),
            ],
            options={
                'unique_together': {('format_criteria', 'order')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='shopitemsize',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='shopitemsize',
            name='format_size',
        ),
        migrations.DeleteModel(
            name='FormatSize',
        ),
        migrations.DeleteModel(
            name='ShopItemSize',
        ),
    ]
