# Generated by Django 3.1.7 on 2022-06-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20220616_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criteriasubcategory',
            options={'verbose_name': 'Criterion of subcategory', 'verbose_name_plural': 'Criteria of subcategory'},
        ),
    ]
