# Generated by Django 3.1.7 on 2022-06-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20220616_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formatcriteria',
            name='criteria_subcategory',
        ),
        migrations.AddField(
            model_name='criteriasubcategory',
            name='format_criteria',
            field=models.ManyToManyField(blank=True, null=True, related_name='criteria_subcategories', to='stock.FormatCriteria'),
        ),
    ]
