# Generated by Django 3.1.7 on 2022-06-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20220616_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteriasubcategory',
            name='format_criteria',
            field=models.ManyToManyField(blank=True, related_name='criteria_subcategories', to='stock.FormatCriteria'),
        ),
    ]
