# Generated by Django 3.1.7 on 2022-06-23 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_auto_20220620_1305'),
        ('stock', '0007_auto_20220616_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_size', models.ManyToManyField(blank=True, related_name='stock_carts', to='stock.SizeFormat')),
                ('shop_item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_carts', to='shop.shopitem')),
            ],
        ),
        migrations.CreateModel(
            name='ShopItemSizeCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('size_format', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_item_size_counts', to='stock.sizeformat')),
                ('stock_cart', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_item_size_counts', to='stock.stockcart')),
            ],
        ),
        migrations.CreateModel(
            name='ShopItemCollections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_collections', to='shop.shopitem')),
                ('related_items', models.ManyToManyField(blank=True, related_name='shop_item_collections', to='shop.ShopItem')),
            ],
        ),
    ]
