# Generated by Django 3.1.7 on 2022-06-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_shopitemcollections_shopitemsizecount_stockcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItemLinkForCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Shop item link for collection',
                'verbose_name_plural': 'Shop item links for collection',
            },
        ),
        migrations.AlterModelOptions(
            name='shopitemcollections',
            options={'verbose_name': 'Shop item collection', 'verbose_name_plural': 'Shop item collections'},
        ),
        migrations.AlterModelOptions(
            name='shopitemsizecount',
            options={'verbose_name': 'Shop item size quantity', 'verbose_name_plural': 'Shop item sizes quantity'},
        ),
        migrations.AlterModelOptions(
            name='stockcart',
            options={'verbose_name': 'Shop item stock cart', 'verbose_name_plural': 'Shop item stock carts'},
        ),
        migrations.AlterField(
            model_name='stockcart',
            name='available_size',
            field=models.ManyToManyField(related_name='stock_carts', to='stock.SizeFormat'),
        ),
        migrations.AddField(
            model_name='shopitemcollections',
            name='related_item_links',
            field=models.ManyToManyField(blank=True, related_name='shop_item_link_collections', to='stock.ShopItemLinkForCollection'),
        ),
    ]
