# Generated by Django 3.1.7 on 2022-07-06 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_auto_20220620_1305'),
        ('stock', '0009_auto_20220629_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_sizes', models.ManyToManyField(blank=True, related_name='stock_collections', to='stock.SizeFormat')),
                ('criteria', models.ManyToManyField(blank=True, related_name='stock_collections', to='stock.CriteriaSubcategory')),
                ('shop_item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_collections', to='shop.shopitem')),
            ],
            options={
                'verbose_name': 'Stock collection',
                'verbose_name_plural': 'Stock collections',
            },
        ),
        migrations.RemoveField(
            model_name='shopitemsizecount',
            name='size_format',
        ),
        migrations.RemoveField(
            model_name='shopitemsizecount',
            name='stock_cart',
        ),
        migrations.RemoveField(
            model_name='stockcart',
            name='available_size',
        ),
        migrations.RemoveField(
            model_name='stockcart',
            name='shop_item',
        ),
        migrations.DeleteModel(
            name='ShopItemCollections',
        ),
        migrations.DeleteModel(
            name='ShopItemLinkForCollection',
        ),
        migrations.DeleteModel(
            name='ShopItemSizeCount',
        ),
        migrations.DeleteModel(
            name='StockCart',
        ),
    ]
