# Generated by Django 3.1.7 on 2022-07-06 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_auto_20220620_1305'),
        ('stock', '0010_auto_20220706_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockcollection',
            name='criteria',
        ),
        migrations.AddField(
            model_name='stockcollection',
            name='criteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_collections', to='stock.criteriasubcategory'),
        ),
        migrations.AlterField(
            model_name='stockcollection',
            name='shop_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_collections', to='shop.shopitem'),
        ),
    ]
