# Generated by Django 3.1.7 on 2022-07-07 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_auto_20220706_1208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockCollection',
        ),
    ]
