# Generated by Django 3.1.7 on 2022-07-07 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_shopitem_available_sizes'),
        ('stock', '0012_delete_stockcollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItemSetStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_shop_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_shop_items_set_stocks', to='shop.shopitem')),
                ('shop_item', models.ManyToManyField(blank=True, related_name='shop_items_set_stocks', to='shop.ShopItem')),
            ],
        ),
        migrations.CreateModel(
            name='ShopItemLinksSetStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, max_length=1000, null=True)),
                ('main_shop_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_item_link_set_stocks', to='shop.shopitem')),
                ('shop_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_items_link_set_stocks', to='shop.shopitem')),
            ],
        ),
    ]
