# Generated by Django 3.1.7 on 2022-07-07 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_shopitem_available_sizes'),
        ('stock', '0013_shopitemlinkssetstock_shopitemsetstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitemlinkssetstock',
            name='shop_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_items_link_set_stocks', to='shop.shopitem'),
        ),
    ]
