# Generated by Django 3.1.7 on 2022-07-07 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_shopitem_available_sizes'),
        ('stock', '0014_auto_20220707_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItemSizeCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, max_length=1000, null=True)),
                ('main_shop_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_item_size_counts', to='shop.shopitem')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_item_size_counts', to='stock.sizeformat')),
            ],
        ),
    ]
