# Generated by Django 3.1.7 on 2022-07-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_shopitem_available_sizes'),
        ('stock', '0015_shopitemsizecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitemsizecount',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='shopitemsizecount',
            unique_together={('main_shop_item', 'size')},
        ),
    ]
