# Generated by Django 3.1.7 on 2022-07-21 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0037_linkapp'),
        ('stock', '0016_auto_20220708_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteriasubcategory',
            name='icon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.file'),
        ),
    ]
