# Generated by Django 3.1.7 on 2022-08-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_criteriasubcategory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitemsizecount',
            name='count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
