# Generated by Django 3.1.7 on 2024-01-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_auto_20220822_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteriasubcategory',
            name='name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='criteriasubcategory',
            name='name_zh',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formatcriteria',
            name='name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formatcriteria',
            name='name_zh',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
