# Generated by Django 3.1.7 on 2022-10-05 05:34

from django.db import migrations


def add_criteria(apps, _):
    ItemSubcategory = apps.get_model('shop', 'ItemSubcategory')
    FormatCriteria = apps.get_model('stock', 'FormatCriteria')

    categories = {
        'adult_clothes' : [1, 2],
        'child_clothes' : [3, 27],
        'adult_shoes' : [7, 8],
        'child_shoes' : [9]
    }

    criteria_subcategories = {
        'adult_clothes': 1,
        'child_clothes': 2,
        'adult_shoes': 3,
        'child_shoes': 4
    }

    try:
        for category_name, ids in categories.items():
            subcategories = ItemSubcategory.objects.filter(category_id__in=ids)
            for subcategory in subcategories:
                criteria_subcategory = FormatCriteria.objects.get(id=criteria_subcategories[category_name])
                subcategory.criteria_subcategory.add(criteria_subcategory)
    except Exception as e:
        print(e, 'FAIL!!!')

def reverse_func(apps, schema_editor):
    print('FAIL!!!')
    # ItemSubcategory = apps.get_model('shop', 'ItemSubcategory')
    #
    # categories = {
    #     'adult_clothes': [1, 2],
    #     'child_clothes': [3, 27],
    #     'adult_shoes': [7, 8],
    #     'child_shoes': [9]
    # }
    #
    # try:
    #     for category_name, ids in categories.items():
    #         subcategories = ItemSubcategory.objects.filter(category_id__in=ids)
    #         for subcategory in subcategories:
    #             subcategory.criteria_subcategory.clear()
    # except Exception as e:
    #     print(e, 'FAIL!!!')


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_auto_20220822_0711'),
    ]

    operations = [
        migrations.RunPython(add_criteria, reverse_func),
    ]