# Generated by Django 3.1.7 on 2025-06-02 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0055_country_is_paid_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAppCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'UserApp categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserAppType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_adult', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='applications.userappcategory')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='UserAppBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_default', models.BooleanField(default=False, help_text='Системный баннер, удаляется только из админки')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_app_banners', to='common.file')),
            ],
            options={
                'verbose_name': 'Баннер приложения',
                'verbose_name_plural': 'Баннеры приложений',
            },
        ),
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('title_lang', models.CharField(blank=True, max_length=8, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_lang', models.CharField(blank=True, max_length=8, null=True)),
                ('app_link', models.URLField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('youtube_links', models.JSONField(blank=True, null=True)),
                ('support_link', models.URLField(blank=True, null=True)),
                ('company_link', models.URLField(blank=True, null=True)),
                ('terms_link', models.URLField(blank=True, null=True)),
                ('app_images', models.ManyToManyField(blank=True, related_name='user_app_images', to='common.File')),
                ('banners', models.ManyToManyField(blank=True, related_name='user_apps', to='applications.UserAppBanner')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_apps', to='common.file')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_user_apps', to=settings.AUTH_USER_MODEL)),
                ('selected_banner', models.ForeignKey(blank=True, help_text="The banner shown on the UserApp's detail page", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_user_apps', to='applications.userappbanner')),
                ('types', models.ManyToManyField(blank=True, related_name='user_apps', to='applications.UserAppType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
