# Generated by Django 3.1.7 on 2025-06-04 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_userapppurchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userapp',
            old_name='company_link',
            new_name='company_name',
        ),
    ]
