# Generated by Django 3.1.7 on 2025-06-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20250604_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
