# Generated by Django 3.1.7 on 2025-06-05 09:07

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0055_country_is_paid_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0005_auto_20250605_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAppReferralTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.ForeignKey(default='USD', on_delete=django.db.models.deletion.PROTECT, related_name='user_app_sale_transactions', to='common.currency')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_sales_profits', to=settings.AUTH_USER_MODEL)),
                ('user_app_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_transactions', to='applications.userapppurchase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAppReferralBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_app_referral_balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformCommission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_commissions', to='applications.userapp')),
                ('currency', models.ForeignKey(default='USD', on_delete=django.db.models.deletion.PROTECT, related_name='platform_commissions_currency', to='common.currency')),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_commission', to='applications.userapppurchase')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
