# Generated by Django 3.1.7 on 2025-06-05 09:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0055_country_is_paid_subscription'),
        ('applications', '0006_platformcommission_userappreferralbalance_userappreferraltransaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAppReferralBalance',
            new_name='UserAppBalance',
        ),
        migrations.RenameModel(
            old_name='UserAppReferralTransaction',
            new_name='UserAppTransaction',
        ),
    ]
