# Generated by Django 3.1.7 on 2025-06-05 09:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_auto_20250605_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformcommission',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5),
        ),
    ]
