# Generated by Django 3.1.7 on 2025-06-06 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_platformcommission_commission_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformcommission',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='platformcommission',
            name='app',
        ),
        migrations.RemoveField(
            model_name='platformcommission',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='platformcommission',
            name='purchase',
        ),
    ]
