# Generated by Django 3.1.7 on 2025-06-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_auto_20250606_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
