# Generated by Django 3.1.7 on 2025-06-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_userapp_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
