# Generated by Django 3.1.7 on 2025-10-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_userapp_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('server', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'System information',
                'verbose_name_plural': 'System informations',
                'db_table': 'system_accounts',
            },
        ),
    ]
