# Generated by Django

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0174_auto_20260109_1430"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramBot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bot_token",
                    models.CharField(
                        help_text="Telegram Bot API token from @BotFather",
                        max_length=100,
                    ),
                ),
                (
                    "bot_username",
                    models.CharField(
                        blank=True,
                        help_text="Bot username without @",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "webhook_secret",
                    models.CharField(
                        blank=True,
                        help_text="Secret token for webhook verification",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "webhook_url",
                    models.URLField(
                        blank=True,
                        help_text="Webhook URL set on Telegram",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True,
                        help_text="Last error message from Telegram API",
                        null=True,
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_bot",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram Bot",
                "verbose_name_plural": "Telegram Bots",
            },
        ),
        migrations.CreateModel(
            name="WhatsAppBot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone_number_id",
                    models.CharField(
                        help_text="WhatsApp Business Phone Number ID",
                        max_length=50,
                    ),
                ),
                (
                    "business_account_id",
                    models.CharField(
                        help_text="WhatsApp Business Account ID",
                        max_length=50,
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        help_text="Permanent access token from Meta Developer Portal",
                    ),
                ),
                (
                    "verify_token",
                    models.CharField(
                        help_text="Custom verification token for webhook setup",
                        max_length=64,
                    ),
                ),
                (
                    "webhook_secret",
                    models.CharField(
                        blank=True,
                        help_text="App Secret for signature verification",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "display_phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Display phone number",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "last_error",
                    models.TextField(
                        blank=True,
                        help_text="Last error message from WhatsApp API",
                        null=True,
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_bot",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Bot",
                "verbose_name_plural": "WhatsApp Bots",
            },
        ),
        migrations.CreateModel(
            name="BotChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[("telegram", "Telegram"), ("whatsapp", "WhatsApp")],
                        max_length=20,
                    ),
                ),
                (
                    "platform_chat_id",
                    models.CharField(
                        help_text="Chat ID from the platform (Telegram chat_id or WhatsApp phone)",
                        max_length=100,
                    ),
                ),
                (
                    "platform_user_id",
                    models.CharField(
                        blank=True,
                        help_text="User ID from the platform",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        blank=True,
                        help_text="User's name or username from the platform",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "user_phone",
                    models.CharField(
                        blank=True,
                        help_text="User's phone number (for WhatsApp)",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_chats",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot Chat",
                "verbose_name_plural": "Bot Chats",
            },
        ),
        migrations.AddConstraint(
            model_name="botchat",
            constraint=models.UniqueConstraint(
                fields=("organization", "platform", "platform_chat_id"),
                name="unique_bot_chat_per_org_platform",
            ),
        ),
        migrations.CreateModel(
            name="BotMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sender",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        default="user",
                        max_length=25,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "platform_message_id",
                    models.CharField(
                        blank=True,
                        help_text="Message ID from the platform",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="messenger_bots.botchat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot Message",
                "verbose_name_plural": "Bot Messages",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="TelegramUserbot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Phone number of the Telegram account (with country code, e.g., +79001234567)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "api_id",
                    models.CharField(
                        help_text="Telegram API ID from my.telegram.org",
                        max_length=20,
                    ),
                ),
                (
                    "api_hash",
                    models.CharField(
                        help_text="Telegram API Hash from my.telegram.org",
                        max_length=64,
                    ),
                ),
                (
                    "session_string",
                    models.TextField(
                        blank=True,
                        help_text="Telethon session string (generated after auth)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this userbot available for creating bots",
                    ),
                ),
                (
                    "is_authenticated",
                    models.BooleanField(
                        default=False,
                        help_text="Has this userbot been authenticated",
                    ),
                ),
                (
                    "auth_state",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("code_sent", "Code Sent"),
                            ("awaiting_2fa", "Awaiting 2FA Password"),
                            ("authenticated", "Authenticated"),
                            ("error", "Error"),
                        ],
                        default="not_started",
                        help_text="Current authentication state",
                        max_length=20,
                    ),
                ),
                (
                    "phone_code_hash",
                    models.CharField(
                        blank=True,
                        help_text="Phone code hash from Telegram (for auth flow)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "auth_state_message",
                    models.TextField(
                        blank=True,
                        help_text="Current authentication state message/instruction",
                        null=True,
                    ),
                ),
                (
                    "bots_created_today",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of bots created today (BotFather limit ~20/day)",
                    ),
                ),
                (
                    "total_bots_created",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of bots created",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "Telegram Userbot",
                "verbose_name_plural": "Telegram Userbots",
            },
        ),
        migrations.CreateModel(
            name="BotCreationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "bot_name",
                    models.CharField(
                        help_text="Desired bot name (e.g., 'OrgName APZ')",
                        max_length=64,
                    ),
                ),
                (
                    "bot_username",
                    models.CharField(
                        blank=True,
                        help_text="Generated bot username",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "bot_token",
                    models.CharField(
                        blank=True,
                        help_text="Received bot token",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_creation_requests",
                        to="organizations.organization",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bot_creation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "userbot_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creation_requests",
                        to="messenger_bots.telegramuserbot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot Creation Request",
                "verbose_name_plural": "Bot Creation Requests",
                "ordering": ("-created_at",),
            },
        ),
    ]
