# Generated by Django - WhatsApp WAHA Integration

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("messenger_bots", "0001_initial"),
    ]

    operations = [
        # Add provider field to WhatsAppBot
        migrations.AddField(
            model_name="whatsappbot",
            name="provider",
            field=models.CharField(
                choices=[
                    ("waha", "WAHA (Self-hosted)"),
                    ("twilio", "Twilio"),
                    ("meta_cloud", "Meta Cloud API"),
                ],
                default="waha",
                help_text="WhatsApp service provider",
                max_length=20,
            ),
        ),
        # Add WAHA specific fields
        migrations.AddField(
            model_name="whatsappbot",
            name="waha_session_name",
            field=models.CharField(
                blank=True,
                help_text="WAHA session name (auto-generated as org_<id>)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="whatsappbot",
            name="session_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending QR Scan"),
                    ("scan_qr", "Scan QR Code"),
                    ("authenticated", "Authenticated"),
                    ("failed", "Failed"),
                    ("disconnected", "Disconnected"),
                ],
                default="pending",
                help_text="Current session status (for WAHA)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="whatsappbot",
            name="connected_phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number connected via QR (for WAHA)",
                max_length=20,
                null=True,
            ),
        ),
        # Add Twilio specific field
        migrations.AddField(
            model_name="whatsappbot",
            name="twilio_phone_number",
            field=models.CharField(
                blank=True,
                help_text="Twilio WhatsApp phone number",
                max_length=20,
                null=True,
            ),
        ),
        # Add last_activity_at field
        migrations.AddField(
            model_name="whatsappbot",
            name="last_activity_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last activity timestamp",
                null=True,
            ),
        ),
        # Make Meta Cloud API fields nullable (they were required before)
        migrations.AlterField(
            model_name="whatsappbot",
            name="phone_number_id",
            field=models.CharField(
                blank=True,
                help_text="WhatsApp Business Phone Number ID (Meta Cloud)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="whatsappbot",
            name="business_account_id",
            field=models.CharField(
                blank=True,
                help_text="WhatsApp Business Account ID (Meta Cloud)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="whatsappbot",
            name="access_token",
            field=models.TextField(
                blank=True,
                help_text="Permanent access token from Meta Developer Portal",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="whatsappbot",
            name="verify_token",
            field=models.CharField(
                blank=True,
                help_text="Custom verification token for webhook setup",
                max_length=64,
                null=True,
            ),
        ),
        # Create WhatsAppFailoverLog model
        migrations.CreateModel(
            name="WhatsAppFailoverLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_provider",
                    models.CharField(
                        choices=[
                            ("waha", "WAHA (Self-hosted)"),
                            ("twilio", "Twilio"),
                            ("meta_cloud", "Meta Cloud API"),
                        ],
                        help_text="Provider before failover",
                        max_length=20,
                    ),
                ),
                (
                    "to_provider",
                    models.CharField(
                        choices=[
                            ("waha", "WAHA (Self-hosted)"),
                            ("twilio", "Twilio"),
                            ("meta_cloud", "Meta Cloud API"),
                        ],
                        help_text="Provider after failover",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Reason for failover"),
                ),
                (
                    "whatsapp_bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failover_logs",
                        to="messenger_bots.whatsappbot",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Failover Log",
                "verbose_name_plural": "WhatsApp Failover Logs",
                "ordering": ("-created_at",),
            },
        ),
    ]
