# Generated by Django 3.1.7 on 2026-01-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_bots', '0004_auto_20260115_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcreationrequest',
            name='base_url',
            field=models.CharField(blank=True, help_text='Base URL for webhook (auto-detected from request)', max_length=255, null=True),
        ),
    ]
