image: dind-local:latest

#variables:
#  DOCKER_HOST: tcp://docker:2375/

stages:
  - test

run_tests:
  stage: test
  script:
    - docker-compose -f docker-compose.base.yml -f docker-compose.tests.yml -p backend_$CI_COMMIT_SHORT_SHA up --build --exit-code-from app app
    - docker-compose -f docker-compose.base.yml -f docker-compose.tests.yml -p backend_$CI_COMMIT_SHORT_SHA down
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  artifacts:
    reports:
      cobertura: coverage.xml
      junit: junittestreport.xml
  only:
    refs:
      - merge_requests
      - dev
      - master
