version: "2.4"

services:
  django:
    build:
      context: .
      target: prod
    restart: always
    container_name: qrcode_django
    image: django
    depends_on:
      - postgis
    environment:
      - SECRET_KEY=notasecret
      - DEBUG=true
      - DJANGO_SETTINGS_MODULE=project.settings.base
      - ALLOWED_HOSTS=*
      - POSTGRES_DB=qrcode
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - NIKITA_USERNAME=nikita
      - NIKITA_PASSWORD=nikitapass
      - NIKITA_SENDER=nikitasender
      - NIKITA_TEST_MODE=1
      - OER_APP_ID=oerappid
    ports:
      - "5000:5000"
  postgis:
    restart: always
    container_name: qrcode_postgis
    image: postgis/postgis:latest
    environment:
      - POSTGRES_DB=qrcode
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
