version: "3.7"

services:
  app:
    build:
      context: .
    depends_on:
      - postgres
      - celery
  rabbit:
    image: rabbitmq:3.8-alpine
  postgres:
    image: postgis/postgis:latest
    environment:
      POSTGRES_DB: "qrcode"
      POSTGRES_PASSWORD: "qrcode"
      POSTGRES_USER: "qrcode"
