version: "3.7"

services:
  app:
    command: ["true"]
  postgres:
    volumes:
      - ./.postgres:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
  rabbit:
    image: rabbitmq:3.8-alpine
    ports:
      - 127.0.0.1:5672:5672