version: "3.7"

services:
  app:
    build:
      context: .
    depends_on:
      - postgres
  postgres:
    image: postgis/postgis:latest
    environment:
      - POSTGRES_DB=qrcode
      - POSTGRES_PASSWORD=qrcode
      - POSTGRES_USER=qrcode
