export const GET_NOTIFICATIONS = {
  REQUEST: 'GET_NOTIFICATIONS_REQUEST',
  SUCCESS: 'GET_NOTIFICATIONS_SUCCESS',
  FAILURE: 'GET_NOTIFICATIONS_FAILURE',
}

export const GET_NOTIFICATION_SETTINGS = {
  REQUEST: 'GET_NOTIFICATION_SETTINGS_REQUEST',
  SUCCESS: 'GET_NOTIFICATION_SETTINGS_SUCCESS',
  FAILURE: 'GET_NOTIFICATION_SETTINGS_FAILURE',
}

export const UPDATE_NOTIFICATION_SETTINGS = {
  REQUEST: 'UPDATE_NOTIFICATION_SETTINGS_REQUEST',
  SUCCESS: 'UPDATE_NOTIFICATION_SETTINGS_SUCCESS',
  FAILURE: 'UPDATE_NOTIFICATION_SETTINGS_FAILURE',
}

export const SET_NOTIFICATION_COUNT = 'SET_NOTIFICATION_COUNT';