export const GET_ORG_PARTNERS = {
  REQUEST: 'GET_ORG_PARTNERS_REQUEST',
  SUCCESS: 'GET_ORG_PARTNERS_SUCCESS',
  FAILURE: 'GET_ORG_PARTNERS_FAILURE',
}

export const GET_ORG_PARTNERSHIPS = {
  REQUEST: 'GET_ORG_PARTNERSHIPS_REQUEST',
  SUCCESS: 'GET_ORG_PARTNERSHIPS_SUCCESS',
  FAILURE: 'GET_ORG_PARTNERSHIPS_FAILURE',
}

export const GET_PARTNERSHIP_DETAIL = {
  REQUEST: 'GET_PARTNERSHIP_DETAIL_REQUEST',
  SUCCESS: 'GET_PARTNERSHIP_DETAIL_SUCCESS',
  FAILURE: 'GET_PARTNERSHIP_DETAIL_FAILURE',
}