export const GET_STATISTIC_SUMMARY = 'GET_STATISTIC_SUMMARY';
export const GET_ORG_STATISTIC_SUMMARY = 'GET_ORG_STATISTIC_SUMMARY';
export const GET_ORG_PARTNERS_STATISTIC_SUMMARY = 'GET_ORG_PARTNERS_STATISTIC_SUMMARY';

export const GET_ALL_STATISTICS = {
  REQUEST: "GET_ALL_STATISTICS_REQUEST",
  SUCCESS: "GET_ALL_STATISTICS_SUCCESS",
  FAILURE: "GET_ALL_STATISTICS_FAILURE",
}

export const GET_RECEIPTS = {
  REQUEST: "GET_RECEIPTS_REQUEST",
  SUCCESS: "GET_RECEIPTS_SUCCESS",
  FAILURE: "GET_RECEIPTS_FAILURE",
}

export const GET_RECEIPT_DETAIL = {
  REQUEST: "GET_RECEIPT_DETAIL_REQUEST",
  SUCCESS: "GET_RECEIPT_DETAIL_SUCCESS",
  FAILURE: "GET_RECEIPT_DETAIL_FAILURE",
}