# Generated by Django 3.0.7 on 2020-06-25 10:32

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(help_text='File that you want to store', upload_to=common.utils.upload_file_with_original_file_name)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
