# Generated by Django 3.0.7 on 2020-07-08 00:52

from django.db import migrations


def create_countries_with_currencies(apps, _):
    Country = apps.get_model('common', 'Country')
    Currency = apps.get_model('common', 'Currency')
    currency, _ = Currency.objects.get_or_create(code='AUD', name='Австралийский доллар')
    Country.objects.create(currency=currency, code='AU', name='Австралия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/AU.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='AT', name='Австрия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/AT.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='AZN', name='Азербайджанский манат')
    Country.objects.create(currency=currency, code='AZ', name='Азербайджан',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/AZ.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='AX', name='Аландские о-ва',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/AX.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='ALL', name='Албанский лек')
    Country.objects.create(currency=currency, code='AL', name='Албания',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/AL.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='DZD', name='Алжирский динар')
    Country.objects.create(currency=currency, code='DZ', name='Алжир',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/DZ.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='USD', name='Доллар США')
    Country.objects.create(currency=currency, code='AS', name='Американское Самоа',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/AS.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='XCD', name='Восточно-карибский доллар')
    Country.objects.create(currency=currency, code='AI', name='Ангилья',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/AI.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='AOA', name='Ангольская кванза')
    Country.objects.create(currency=currency, code='AO', name='Ангола',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/AO.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='AD', name='Андорра',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/AD.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='XCD', name='Восточно-карибский доллар')
    Country.objects.create(currency=currency, code='AG', name='Антигуа и Барбуда',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/AG.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='ARS', name='Аргентинское песо')
    Country.objects.create(currency=currency, code='AR', name='Аргентина',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/AR.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='AMD', name='Армянский драм')
    Country.objects.create(currency=currency, code='AM', name='Армения', is_priority=True,
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/AM.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='AWG', name='Арубанский флорин')
    Country.objects.create(currency=currency, code='AW', name='Аруба',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/AW.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='AFN', name='Афгани')
    Country.objects.create(currency=currency, code='AF', name='Афганистан',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/AF.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='BSD', name='Багамский доллар')
    Country.objects.create(currency=currency, code='BS', name='Багамы',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/BS.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='BDT', name='Бангладешская така')
    Country.objects.create(currency=currency, code='BD', name='Бангладеш',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/BD.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='BBD', name='Барбадосский доллар')
    Country.objects.create(currency=currency, code='BB', name='Барбадос',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/BB.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='BHD', name='Бахрейнский динар')
    Country.objects.create(currency=currency, code='BH', name='Бахрейн',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/BH.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='BYR', name='Белорусский рубль')
    Country.objects.create(currency=currency, code='BY', name='Беларусь', is_priority=True,
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/BY.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='BZD', name='Белизский доллар')
    Country.objects.create(currency=currency, code='BZ', name='Белиз',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/BZ.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='BE', name='Бельгия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/BE.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='XOF', name='Франк КФА ВСЕАО')
    Country.objects.create(currency=currency, code='BJ', name='Бенин',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/BJ.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='BMD', name='Бермудский доллар')
    Country.objects.create(currency=currency, code='BM', name='Бермудские о-ва',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/BM.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='BGN', name='Болгарский лев')
    Country.objects.create(currency=currency, code='BG', name='Болгария',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/BG.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='BOB', name='Боливийский боливиано')
    Country.objects.create(currency=currency, code='BO', name='Боливия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/BO.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='USD', name='Доллар США')
    Country.objects.create(currency=currency, code='BQ', name='Бонэйр, Синт-Эстатиус и Саба',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/BQ.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='BAM', name='Конвертируемая марка Боснии и Герцеговины')
    Country.objects.create(currency=currency, code='BA', name='Босния и Герцеговина',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/BA.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='BWP', name='Ботсванская пула')
    Country.objects.create(currency=currency, code='BW', name='Ботсвана',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/BW.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='BRL', name='Бразильский реал')
    Country.objects.create(currency=currency, code='BR', name='Бразилия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/BR.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='USD', name='Доллар США')
    Country.objects.create(currency=currency, code='IO', name='Британская территория в Индийском океане',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/IO.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='BND', name='Брунейский доллар')
    Country.objects.create(currency=currency, code='BN', name='Бруней-Даруссалам',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/BN.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='XOF', name='Франк КФА ВСЕАО')
    Country.objects.create(currency=currency, code='BF', name='Буркина-Фасо',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/BF.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='BIF', name='Бурундийский франк')
    Country.objects.create(currency=currency, code='BI', name='Бурунди',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/BI.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='BTN', name='Бутанский нгултрум')
    Country.objects.create(currency=currency, code='BT', name='Бутан',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/BT.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='VUV', name='Вату Вануату')
    Country.objects.create(currency=currency, code='VU', name='Вануату',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/VU.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='VA', name='Ватикан',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/VA.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='GBP', name='Британский фунт стерлингов')
    Country.objects.create(currency=currency, code='GB', name='Великобритания',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/GB.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='HUF', name='Венгерский форинт')
    Country.objects.create(currency=currency, code='HU', name='Венгрия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/HU.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='VEF', name='Венесуэльский боливар')
    Country.objects.create(currency=currency, code='VE', name='Венесуэла',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/VE.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='USD', name='Доллар США')
    Country.objects.create(currency=currency, code='VG', name='Виргинские о-ва (Великобритания)',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/VG.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='USD', name='Доллар США')
    Country.objects.create(currency=currency, code='VI', name='Виргинские о-ва (США)',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/VI.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='USD', name='Доллар США')
    Country.objects.create(currency=currency, code='UM', name='Внешние малые о-ва (США)',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/UM.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='USD', name='Доллар США')
    Country.objects.create(currency=currency, code='TL', name='Восточный Тимор',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/TL.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='VND', name='Вьетнамский донг')
    Country.objects.create(currency=currency, code='VN', name='Вьетнам',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/VN.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='XAF', name='Франк КФА ВЕАС')
    Country.objects.create(currency=currency, code='GA', name='Габон',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/GA.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='HTG', name='Гаитянский гурд')
    Country.objects.create(currency=currency, code='HT', name='Гаити',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/HT.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='GYD', name='Гайанский доллар')
    Country.objects.create(currency=currency, code='GY', name='Гайана',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/GY.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='GMD', name='Гамбийский даласи')
    Country.objects.create(currency=currency, code='GM', name='Гамбия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/GM.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='GHS', name='Ганский седи')
    Country.objects.create(currency=currency, code='GH', name='Гана',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/GH.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='GP', name='Гваделупа',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/GP.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='GTQ', name='Гватемальский кетсаль')
    Country.objects.create(currency=currency, code='GT', name='Гватемала',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/GT.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='GNF', name='Гвинейский франк')
    Country.objects.create(currency=currency, code='GN', name='Гвинея',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/GN.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='XOF', name='Франк КФА ВСЕАО')
    Country.objects.create(currency=currency, code='GW', name='Гвинея-Бисау',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/GW.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='DE', name='Германия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/DE.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='GBP', name='Британский фунт стерлингов')
    Country.objects.create(currency=currency, code='GG', name='Гернси',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/GG.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='GIP', name='Гибралтарский фунт')
    Country.objects.create(currency=currency, code='GI', name='Гибралтар',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/GI.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='HNL', name='Гондурасская лемпира')
    Country.objects.create(currency=currency, code='HN', name='Гондурас',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/HN.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='HKD', name='Гонконгский доллар')
    Country.objects.create(currency=currency, code='HK', name='Гонконг (САР)',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/HK.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='XCD', name='Восточно-карибский доллар')
    Country.objects.create(currency=currency, code='GD', name='Гренада',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/GD.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='DKK', name='Датская крона')
    Country.objects.create(currency=currency, code='GL', name='Гренландия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/GL.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='GR', name='Греция',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/GR.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='GEL', name='Грузинский лари')
    Country.objects.create(currency=currency, code='GE', name='Грузия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/GE.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='USD', name='Доллар США')
    Country.objects.create(currency=currency, code='GU', name='Гуам',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/GU.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='DKK', name='Датская крона')
    Country.objects.create(currency=currency, code='DK', name='Дания',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/DK.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='GBP', name='Британский фунт стерлингов')
    Country.objects.create(currency=currency, code='JE', name='Джерси',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/JE.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='DJF', name='Франк Джибути')
    Country.objects.create(currency=currency, code='DJ', name='Джибути',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/DJ.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='XCD', name='Восточно-карибский доллар')
    Country.objects.create(currency=currency, code='DM', name='Доминика',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/DM.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='DOP', name='Доминиканское песо')
    Country.objects.create(currency=currency, code='DO', name='Доминиканская Республика',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/DO.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EGP', name='Египетский фунт')
    Country.objects.create(currency=currency, code='EG', name='Египет',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/EG.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='ZMK', name='Квача (замбийская)')
    Country.objects.create(currency=currency, code='ZM', name='Замбия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/ZM.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='MAD', name='Марокканский дирхам')
    Country.objects.create(currency=currency, code='EH', name='Западная Сахара',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/EH.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='ZWL', name='Доллар Зимбабве')
    Country.objects.create(currency=currency, code='ZW', name='Зимбабве',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/ZW.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='ILS', name='Новый израильский шекель')
    Country.objects.create(currency=currency, code='IL', name='Израиль',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/IL.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='INR', name='Индийская рупия')
    Country.objects.create(currency=currency, code='IN', name='Индия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/IN.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='IDR', name='Индонезийская рупия')
    Country.objects.create(currency=currency, code='ID', name='Индонезия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/ID.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='JOD', name='Иорданский динар')
    Country.objects.create(currency=currency, code='JO', name='Иордания',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/JO.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='IQD', name='Иракский динар')
    Country.objects.create(currency=currency, code='IQ', name='Ирак',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/IQ.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='IRR', name='Иранский риал')
    Country.objects.create(currency=currency, code='IR', name='Иран',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/IR.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='IE', name='Ирландия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/IE.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='ISK', name='Исландская крона')
    Country.objects.create(currency=currency, code='IS', name='Исландия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/IS.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='ES', name='Испания',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/ES.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='IT', name='Италия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/IT.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='YER', name='Йеменский риал')
    Country.objects.create(currency=currency, code='YE', name='Йемен',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/YE.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='CVE', name='Эскудо Кабо-Верде')
    Country.objects.create(currency=currency, code='CV', name='Кабо-Верде',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/CV.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='KZT', name='Казахский тенге')
    Country.objects.create(currency=currency, code='KZ', name='Казахстан', is_priority=True,
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/KZ.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='KHR', name='Камбоджийский риель')
    Country.objects.create(currency=currency, code='KH', name='Камбоджа',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/KH.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='XAF', name='Франк КФА ВЕАС')
    Country.objects.create(currency=currency, code='CM', name='Камерун',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/CM.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='CAD', name='Канадский доллар')
    Country.objects.create(currency=currency, code='CA', name='Канада',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/CA.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='QAR', name='Катарский риал')
    Country.objects.create(currency=currency, code='QA', name='Катар',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/QA.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='KES', name='Кенийский шиллинг')
    Country.objects.create(currency=currency, code='KE', name='Кения',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/KE.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='CY', name='Кипр',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/CY.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='KGS', name='Кыргызский сом')
    Country.objects.create(currency=currency, code='KG', name='Кыргызстан', is_priority=True,
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/KG.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='AUD', name='Австралийский доллар')
    Country.objects.create(currency=currency, code='KI', name='Кирибати',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/KI.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='CNY', name='Китайский юань')
    Country.objects.create(currency=currency, code='CN', name='Китай',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/CN.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='KPW', name='Северокорейская вона')
    Country.objects.create(currency=currency, code='KP', name='КНДР',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/KP.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='AUD', name='Австралийский доллар')
    Country.objects.create(currency=currency, code='CC', name='Кокосовые о-ва',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/CC.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='COP', name='Колумбийское песо')
    Country.objects.create(currency=currency, code='CO', name='Колумбия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/CO.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='KMF', name='Франк Коморских Островов')
    Country.objects.create(currency=currency, code='KM', name='Коморы',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/KM.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='XAF', name='Франк КФА ВЕАС')
    Country.objects.create(currency=currency, code='CG', name='Конго - Браззавиль',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/CG.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='CDF', name='Конголезский франк')
    Country.objects.create(currency=currency, code='CD', name='Конго - Киншаса',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/CD.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='CRC', name='Костариканский колон')
    Country.objects.create(currency=currency, code='CR', name='Коста-Рика',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/CR.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='XOF', name='Франк КФА ВСЕАО')
    Country.objects.create(currency=currency, code='CI', name='Кот-д’Ивуар',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/CI.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='CUP', name='Кубинское песо')
    Country.objects.create(currency=currency, code='CU', name='Куба',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/CU.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='KWD', name='Кувейтский динар')
    Country.objects.create(currency=currency, code='KW', name='Кувейт',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/KW.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='ANG', name='Нидерландский антильский гульден')
    Country.objects.create(currency=currency, code='CW', name='Кюрасао',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/CW.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='LAK', name='Лаосский кип')
    Country.objects.create(currency=currency, code='LA', name='Лаос',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/LA.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='LV', name='Латвия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/LV.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='LSL', name='Лоти')
    Country.objects.create(currency=currency, code='LS', name='Лесото',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/LS.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='LRD', name='Либерийский доллар')
    Country.objects.create(currency=currency, code='LR', name='Либерия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/LR.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='LBP', name='Ливанский фунт')
    Country.objects.create(currency=currency, code='LB', name='Ливан',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/LB.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='LYD', name='Ливийский динар')
    Country.objects.create(currency=currency, code='LY', name='Ливия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/LY.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='LTL', name='Литовский лит')
    Country.objects.create(currency=currency, code='LT', name='Литва',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/LT.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='CHF', name='Швейцарский франк')
    Country.objects.create(currency=currency, code='LI', name='Лихтенштейн',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/LI.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='LU', name='Люксембург',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/LU.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='MUR', name='Маврикийская рупия')
    Country.objects.create(currency=currency, code='MU', name='Маврикий',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/MU.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='MRO', name='Мавританская угия')
    Country.objects.create(currency=currency, code='MR', name='Мавритания',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/MR.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='MGA', name='Малагасийский ариари')
    Country.objects.create(currency=currency, code='MG', name='Мадагаскар',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/MG.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='YT', name='Майотта',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/YT.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='MOP', name='Патака Макао')
    Country.objects.create(currency=currency, code='MO', name='Макао (САР)',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/MO.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='MWK', name='Малавийская квача')
    Country.objects.create(currency=currency, code='MW', name='Малави',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/MW.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='MYR', name='Малайзийский ринггит')
    Country.objects.create(currency=currency, code='MY', name='Малайзия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/MY.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='XOF', name='Франк КФА ВСЕАО')
    Country.objects.create(currency=currency, code='ML', name='Мали',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/ML.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='MVR', name='Мальдивская руфия')
    Country.objects.create(currency=currency, code='MV', name='Мальдивы',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/MV.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='MT', name='Мальта',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/MT.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='MAD', name='Марокканский дирхам')
    Country.objects.create(currency=currency, code='MA', name='Марокко',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/MA.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='MQ', name='Мартиника',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/MQ.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='USD', name='Доллар США')
    Country.objects.create(currency=currency, code='MH', name='Маршалловы Острова',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/MH.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='MXN', name='Мексиканское песо')
    Country.objects.create(currency=currency, code='MX', name='Мексика',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/MX.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='MZN', name='Мозамбикский метикал')
    Country.objects.create(currency=currency, code='MZ', name='Мозамбик',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/MZ.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='MDL', name='Молдавский лей')
    Country.objects.create(currency=currency, code='MD', name='Молдова',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/MD.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='MC', name='Монако',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/MC.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='MNT', name='Монгольский тугрик')
    Country.objects.create(currency=currency, code='MN', name='Монголия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/MN.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='XCD', name='Восточно-карибский доллар')
    Country.objects.create(currency=currency, code='MS', name='Монтсеррат',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/MS.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='MMK', name='Мьянманский кьят')
    Country.objects.create(currency=currency, code='MM', name='Мьянма (Бирма)',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/MM.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='NAD', name='Доллар Намибии')
    Country.objects.create(currency=currency, code='NA', name='Намибия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/NA.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='AUD', name='Австралийский доллар')
    Country.objects.create(currency=currency, code='NR', name='Науру',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/NR.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='NPR', name='Непальская рупия')
    Country.objects.create(currency=currency, code='NP', name='Непал',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/NP.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='XOF', name='Франк КФА ВСЕАО')
    Country.objects.create(currency=currency, code='NE', name='Нигер',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/NE.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='NGN', name='Нигерийская найра')
    Country.objects.create(currency=currency, code='NG', name='Нигерия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/NG.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='NL', name='Нидерланды',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/NL.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='NIO', name='Никарагуанская кордоба')
    Country.objects.create(currency=currency, code='NI', name='Никарагуа',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/NI.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='NZD', name='Новозеландский доллар')
    Country.objects.create(currency=currency, code='NU', name='Ниуэ',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/NU.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='NZD', name='Новозеландский доллар')
    Country.objects.create(currency=currency, code='NZ', name='Новая Зеландия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/NZ.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='XPF', name='Французский тихоокеанский франк')
    Country.objects.create(currency=currency, code='NC', name='Новая Каледония',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/NC.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='NOK', name='Норвежская крона')
    Country.objects.create(currency=currency, code='NO', name='Норвегия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/NO.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='NOK', name='Норвежская крона')
    Country.objects.create(currency=currency, code='BV', name='о-в Буве',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/BV.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='GBP', name='Британский фунт стерлингов')
    Country.objects.create(currency=currency, code='IM', name='о-в Мэн',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/IM.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='AUD', name='Австралийский доллар')
    Country.objects.create(currency=currency, code='NF', name='о-в Норфолк',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/NF.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='AUD', name='Австралийский доллар')
    Country.objects.create(currency=currency, code='CX', name='о-в Рождества',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/CX.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='SHP', name='Фунт острова Святой Елены')
    Country.objects.create(currency=currency, code='SH', name='о-в Св. Елены',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/SH.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='NZD', name='Новозеландский доллар')
    Country.objects.create(currency=currency, code='PN', name='о-ва Питкэрн',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/PN.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='USD', name='Доллар США')
    Country.objects.create(currency=currency, code='TC', name='о-ва Тёркс и Кайкос',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/TC.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='AUD', name='Австралийский доллар')
    Country.objects.create(currency=currency, code='HM', name='о-ва Херд и Макдональд',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/HM.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='AED', name='Дирхам ОАЭ')
    Country.objects.create(currency=currency, code='AE', name='ОАЭ',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/AE.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='OMR', name='Оманский риал')
    Country.objects.create(currency=currency, code='OM', name='Оман',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/OM.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='KYD', name='Доллар Каймановых островов')
    Country.objects.create(currency=currency, code='KY', name='Острова Кайман',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/KY.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='NZD', name='Новозеландский доллар')
    Country.objects.create(currency=currency, code='CK', name='Острова Кука',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/CK.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='PKR', name='Пакистанская рупия')
    Country.objects.create(currency=currency, code='PK', name='Пакистан',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/PK.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='USD', name='Доллар США')
    Country.objects.create(currency=currency, code='PW', name='Палау',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/PW.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='ILS', name='Новый израильский шекель')
    Country.objects.create(currency=currency, code='PS', name='Палестинские территории',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/PS.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='PAB', name='Панамское бальбоа')
    Country.objects.create(currency=currency, code='PA', name='Панама',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/PA.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='PGK', name='Кина Папуа – Новой Гвинеи')
    Country.objects.create(currency=currency, code='PG', name='Папуа — Новая Гвинея',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/PG.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='PYG', name='Парагвайский гуарани')
    Country.objects.create(currency=currency, code='PY', name='Парагвай',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/PY.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='PEN', name='Перуанский соль')
    Country.objects.create(currency=currency, code='PE', name='Перу',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/PE.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='PLN', name='Польский злотый')
    Country.objects.create(currency=currency, code='PL', name='Польша',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/PL.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='PT', name='Португалия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/PT.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='USD', name='Доллар США')
    Country.objects.create(currency=currency, code='PR', name='Пуэрто-Рико',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/PR.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='KRW', name='Южнокорейская вона')
    Country.objects.create(currency=currency, code='KR', name='Республика Корея',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/KR.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='RE', name='Реюньон',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/RE.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='RUB', name='Российский рубль')
    Country.objects.create(currency=currency, code='RU', name='Россия', is_priority=True,
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/RU.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='RWF', name='Франк Руанды')
    Country.objects.create(currency=currency, code='RW', name='Руанда',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/RW.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='RON', name='Румынский лей')
    Country.objects.create(currency=currency, code='RO', name='Румыния',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/RO.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='USD', name='Доллар США')
    Country.objects.create(currency=currency, code='SV', name='Сальвадор',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/SV.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='WST', name='Самоанская тала')
    Country.objects.create(currency=currency, code='WS', name='Самоа',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/WS.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='SM', name='Сан-Марино',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/SM.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='STD', name='Добра Сан-Томе и Принсипи')
    Country.objects.create(currency=currency, code='ST', name='Сан-Томе и Принсипи',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/ST.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='SAR', name='Саудовский риял')
    Country.objects.create(currency=currency, code='SA', name='Саудовская Аравия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/SA.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='MKD', name='Македонский денар')
    Country.objects.create(currency=currency, code='MK', name='Северная Македония',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/MK.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='USD', name='Доллар США')
    Country.objects.create(currency=currency, code='MP', name='Северные Марианские о-ва',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/MP.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='SCR', name='Сейшельская рупия')
    Country.objects.create(currency=currency, code='SC', name='Сейшельские Острова',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/SC.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='BL', name='Сен-Бартелеми',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/BL.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='MF', name='Сен-Мартен',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/MF.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='PM', name='Сен-Пьер и Микелон',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/PM.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='XOF', name='Франк КФА ВСЕАО')
    Country.objects.create(currency=currency, code='SN', name='Сенегал',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/SN.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='XCD', name='Восточно-карибский доллар')
    Country.objects.create(currency=currency, code='VC', name='Сент-Винсент и Гренадины',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/VC.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='XCD', name='Восточно-карибский доллар')
    Country.objects.create(currency=currency, code='KN', name='Сент-Китс и Невис',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/KN.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='XCD', name='Восточно-карибский доллар')
    Country.objects.create(currency=currency, code='LC', name='Сент-Люсия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/LC.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='RSD', name='Сербский динар')
    Country.objects.create(currency=currency, code='RS', name='Сербия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/RS.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='SGD', name='Сингапурский доллар')
    Country.objects.create(currency=currency, code='SG', name='Сингапур',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/SG.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='ANG', name='Нидерландский антильский гульден')
    Country.objects.create(currency=currency, code='SX', name='Синт-Мартен',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/SX.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='SYP', name='Сирийский фунт')
    Country.objects.create(currency=currency, code='SY', name='Сирия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/SY.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='SK', name='Словакия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/SK.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='SI', name='Словения',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/SI.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='USD', name='Доллар США')
    Country.objects.create(currency=currency, code='US', name='Соединенные Штаты',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/US.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='SBD', name='Доллар Соломоновых Островов')
    Country.objects.create(currency=currency, code='SB', name='Соломоновы Острова',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/SB.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='SOS', name='Сомалийский шиллинг')
    Country.objects.create(currency=currency, code='SO', name='Сомали',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/SO.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='SDG', name='Суданский фунт')
    Country.objects.create(currency=currency, code='SD', name='Судан',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/SD.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='SRD', name='Суринамский доллар')
    Country.objects.create(currency=currency, code='SR', name='Суринам',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/SR.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='SLL', name='Леоне')
    Country.objects.create(currency=currency, code='SL', name='Сьерра-Леоне',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/SL.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='TJS', name='Таджикский сомони')
    Country.objects.create(currency=currency, code='TJ', name='Таджикистан',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/TJ.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='THB', name='Таиландский бат')
    Country.objects.create(currency=currency, code='TH', name='Таиланд',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/TH.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='TWD', name='Новый тайваньский доллар')
    Country.objects.create(currency=currency, code='TW', name='Тайвань',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/TW.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='TZS', name='Танзанийский шиллинг')
    Country.objects.create(currency=currency, code='TZ', name='Танзания',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/TZ.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='XOF', name='Франк КФА ВСЕАО')
    Country.objects.create(currency=currency, code='TG', name='Того',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/TG.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='NZD', name='Новозеландский доллар')
    Country.objects.create(currency=currency, code='TK', name='Токелау',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/TK.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='TOP', name='Тонганская паанга')
    Country.objects.create(currency=currency, code='TO', name='Тонга',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/TO.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='TTD', name='Доллар Тринидада и Тобаго')
    Country.objects.create(currency=currency, code='TT', name='Тринидад и Тобаго',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/TT.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='AUD', name='Австралийский доллар')
    Country.objects.create(currency=currency, code='TV', name='Тувалу',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/TV.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='TND', name='Тунисский динар')
    Country.objects.create(currency=currency, code='TN', name='Тунис',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/TN.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='TMT', name='Новый туркменский манат')
    Country.objects.create(currency=currency, code='TM', name='Туркменистан',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/TM.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='TRY', name='Турецкая лира')
    Country.objects.create(currency=currency, code='TR', name='Турция',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/TR.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='UGX', name='Угандийский шиллинг')
    Country.objects.create(currency=currency, code='UG', name='Уганда',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/UG.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='UZS', name='Узбекский сум')
    Country.objects.create(currency=currency, code='UZ', name='Узбекистан',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/UZ.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='UAH', name='Украинская гривна')
    Country.objects.create(currency=currency, code='UA', name='Украина',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/UA.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='XPF', name='Французский тихоокеанский франк')
    Country.objects.create(currency=currency, code='WF', name='Уоллис и Футуна',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/WF.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='UYU', name='Уругвайское песо')
    Country.objects.create(currency=currency, code='UY', name='Уругвай',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/UY.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='DKK', name='Датская крона')
    Country.objects.create(currency=currency, code='FO', name='Фарерские о-ва',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/FO.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='USD', name='Доллар США')
    Country.objects.create(currency=currency, code='FM', name='Федеративные Штаты Микронезии',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/FM.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='FJD', name='Доллар Фиджи')
    Country.objects.create(currency=currency, code='FJ', name='Фиджи',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/FJ.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='PHP', name='Филиппинское песо')
    Country.objects.create(currency=currency, code='PH', name='Филиппины',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/PH.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='FI', name='Финляндия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/FI.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='FKP', name='Фунт Фолклендских островов')
    Country.objects.create(currency=currency, code='FK', name='Фолклендские о-ва',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/FK.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='FR', name='Франция',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/FR.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='GF', name='Французская Гвиана',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/GF.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='XPF', name='Французский тихоокеанский франк')
    Country.objects.create(currency=currency, code='PF', name='Французская Полинезия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/PF.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='TF', name='Французские Южные территории',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/TF.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='HRK', name='Хорватская куна')
    Country.objects.create(currency=currency, code='HR', name='Хорватия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/HR.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='XAF', name='Франк КФА ВЕАС')
    Country.objects.create(currency=currency, code='CF', name='Центрально-Африканская Республика',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/CF.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='XAF', name='Франк КФА ВЕАС')
    Country.objects.create(currency=currency, code='TD', name='Чад',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/TD.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='ME', name='Черногория',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/ME.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='CZK', name='Чешская крона')
    Country.objects.create(currency=currency, code='CZ', name='Чехия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/CZ.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='CLP', name='Чилийское песо')
    Country.objects.create(currency=currency, code='CL', name='Чили',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/CL.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='CHF', name='Швейцарский франк')
    Country.objects.create(currency=currency, code='CH', name='Швейцария',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/CH.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='SEK', name='Шведская крона')
    Country.objects.create(currency=currency, code='SE', name='Швеция',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/SE.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='NOK', name='Норвежская крона')
    Country.objects.create(currency=currency, code='SJ', name='Шпицберген и Ян-Майен',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/SJ.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='LKR', name='Шри-ланкийская рупия')
    Country.objects.create(currency=currency, code='LK', name='Шри-Ланка',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/LK.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='USD', name='Доллар США')
    Country.objects.create(currency=currency, code='EC', name='Эквадор',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/EC.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='XAF', name='Франк КФА ВЕАС')
    Country.objects.create(currency=currency, code='GQ', name='Экваториальная Гвинея',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/GQ.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='ERN', name='Накфа')
    Country.objects.create(currency=currency, code='ER', name='Эритрея',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/ER.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='SZL', name='Свазилендский лилангени')
    Country.objects.create(currency=currency, code='SZ', name='Эсватини',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/SZ.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='EUR', name='Евро')
    Country.objects.create(currency=currency, code='EE', name='Эстония',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/EE.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='ETB', name='Эфиопский быр')
    Country.objects.create(currency=currency, code='ET', name='Эфиопия',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/ET.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='GBP', name='Британский фунт стерлингов')
    Country.objects.create(currency=currency, code='GS', name='Южная Георгия и Южные Сандвичевы о-ва',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/GS.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='ZAR', name='Южноафриканский рэнд')
    Country.objects.create(currency=currency, code='ZA', name='Южно-Африканская Республика',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/ZA.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='SSP', name='Южносуданский фунт')
    Country.objects.create(currency=currency, code='SS', name='Южный Судан',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/SS.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='JMD', name='Ямайский доллар')
    Country.objects.create(currency=currency, code='JM', name='Ямайка',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/JM.png?raw=True')
    currency, _ = Currency.objects.get_or_create(code='JPY', name='Японская иена')
    Country.objects.create(currency=currency, code='JP', name='Япония',
                           flag='https://github.com/IainMcManus/FlagAndCountryData/blob/master/flags/flags-iso/flat/64/JP.png?raw=True')


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0002_country_currency'),
    ]

    operations = [
        migrations.RunPython(create_countries_with_currencies),
    ]
