# Generated by Django 3.0.8 on 2020-07-12 20:09

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_countries_currencies_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.ImageField(help_text='Image that you want to store', upload_to=common.utils.upload_file_with_original_file_name),
        ),
    ]
