# Generated by Django 3.0.8 on 2020-08-11 01:20

from django.db import migrations
from django.db.models import F, Value
from django.db.models.functions import Concat


def delete_countries_without_flags(apps, _):
    Country = apps.get_model('common', 'Country')

    Country.objects.filter(code='BV').delete()
    Country.objects.filter(code='BQ').delete()
    Country.objects.filter(code='GF').delete()
    Country.objects.filter(code='GP').delete()
    Country.objects.filter(code='HM').delete()
    Country.objects.filter(code='IO').delete()
    Country.objects.filter(code='PM').delete()
    Country.objects.filter(code='RE').delete()
    Country.objects.filter(code='SJ').delete()
    Country.objects.filter(code='SX').delete()
    Country.objects.filter(code='UM').delete()


def update_flag_locations(apps, _):
    Country = apps.get_model('common', 'Country')
    Country.objects.all().update(flag=Concat(Concat(Value('/media/flags-iso/'), 'code'), Value('.png')))


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0004_auto_20200712_2009'),
    ]

    operations = [
        migrations.RunPython(delete_countries_without_flags),
        migrations.RunPython(update_flag_locations),
    ]
