# Generated by Django 3.0.8 on 2020-08-25 05:14

from django.db import migrations


def update_belarus_ruble_code(apps, _):
    Country = apps.get_model('common', 'Country')
    Currency = apps.get_model('common', 'Currency')

    temp_currency = Currency.objects.get(code='KGS')

    belarus = Country.objects.get(code='BY')
    belarus.currency = temp_currency
    belarus.save()

    Currency.objects.filter(code='BYR').update(code='BYN')
    belarus.currency = Currency.objects.get(code='BYN')
    belarus.save()


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0005_flags_data_migration'),
    ]

    operations = [
        migrations.RunPython(update_belarus_ruble_code),
    ]
