# Generated by Django 3.0.8 on 2020-09-23 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_belarusian_ruble_fix_data_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='common.Country')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ('name', 'country'),
            },
        ),
    ]
