# Generated by Django 3.0.8 on 2020-09-26 14:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_english_countries_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='city',
            name='postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
