# Generated by Django 3.0.8 on 2020-10-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20200926_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_watermarked',
            field=models.BooleanField(default=False),
        ),
    ]
