# Generated by Django 3.0.8 on 2020-10-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_file_is_watermarked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='file',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='is_watermarked',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
