# Generated by Django 3.0.8 on 2020-12-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20201028_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
