# Generated by Django 3.0.8 on 2020-12-18 12:34

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_file_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.ImageField(help_text='Image that you want to store', max_length=1000, upload_to=common.utils.upload_file_with_original_file_name),
        ),
    ]
