# Generated by Django 3.1.6 on 2021-02-16 14:04

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_auto_20201218_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.ImageField(help_text='Image that you want to store', max_length=1000, upload_to=common.utils.upload_file_with_unique_name),
        ),
    ]
