# Generated by Django 3.1.7 on 2021-10-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenExchangeRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'id for exchange service',
                'verbose_name_plural': 'id for exchange service',
            },
        ),
    ]
