# Generated by Django 3.1.7 on 2021-10-18 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_openexchangerates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openexchangerates',
            options={'verbose_name': 'id for exchange service', 'verbose_name_plural': 'id for exchange services'},
        ),
    ]
