# Generated by Django 3.1.7 on 2021-10-27 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_auto_20211018_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('language_en', models.CharField(max_length=255)),
                ('language_ru', models.CharField(max_length=255)),
                ('national_language', models.CharField(max_length=255)),
                ('flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language', to='common.file')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
    ]
