# Generated by Django 3.1.7 on 2021-10-27 10:02

from django.db import migrations

def transfer_languages(apps, schema_editor):
    Languages = apps.get_model('common', 'Languages')
    Languages.objects.create(code="af", language_en="afrikaans", language_ru="африкаанс", national_language="afrikaans")
    Languages.objects.create(code="sq", language_en="albanian", language_ru="албанский", national_language="shqip")
    Languages.objects.create(code="am", language_en="amharic", language_ru="амхарский", national_language="አማርኛ")
    Languages.objects.create(code="ar", language_en="arabic", language_ru="арабский", national_language="عربي")
    Languages.objects.create(code="hy", language_en="armenian", language_ru="армянский", national_language="հայերեն")
    Languages.objects.create(code="az", language_en="azerbaijani", language_ru="азербайджанский",
                             national_language="azərbaycanlı")
    Languages.objects.create(code="eu", language_en="basque", language_ru="басков", national_language="euskalduna")
    Languages.objects.create(code="be", language_en="belarusian", language_ru="белорусский",
                             national_language="беларуская")
    Languages.objects.create(code="bn", language_en="bengali", language_ru="бенгальский", national_language="বাংলা")
    Languages.objects.create(code="bs", language_en="bosnian", language_ru="боснийский", national_language="bosanski")
    Languages.objects.create(code="bg", language_en="bulgarian", language_ru="болгарский",
                             national_language="български")
    Languages.objects.create(code="ca", language_en="catalan", language_ru="каталонский", national_language="català")
    Languages.objects.create(code="ceb", language_en="cebuano", language_ru="Cebuano", national_language="Cebuano")
    Languages.objects.create(code="ny", language_en="chichewa", language_ru="чичева", national_language="chichewa")
    Languages.objects.create(code="zh-CN", language_en="chinese", language_ru="китайский язык", national_language="中国人")
    Languages.objects.create(code="zh-TW", language_en="chinese", language_ru="китайский язык", national_language="中國人")
    Languages.objects.create(code="co", language_en="corsican", language_ru="корсиканский", national_language="Corsu")
    Languages.objects.create(code="hr", language_en="croatian", language_ru="хорватский", national_language="Hrvatski")
    Languages.objects.create(code="cs", language_en="czech", language_ru="чешский язык", national_language="čeština")
    Languages.objects.create(code="da", language_en="danish", language_ru="датский", national_language="dansk")
    Languages.objects.create(code="nl", language_en="dutch", language_ru="Голландский", national_language="Nederlands")
    Languages.objects.create(code="en", language_en="english", language_ru="английский", national_language="english")
    Languages.objects.create(code="eo", language_en="esperanto", language_ru="эсперанто", national_language="esperanto")
    Languages.objects.create(code="et", language_en="estonian", language_ru="эстонский", national_language="eesti keel")
    Languages.objects.create(code="tl", language_en="filipino", language_ru="филиппинский",
                             national_language="pilipino")
    Languages.objects.create(code="fi", language_en="finnish", language_ru="финский", national_language="Suomalainen")
    Languages.objects.create(code="fr", language_en="french", language_ru="французкий язык",
                             national_language="français")
    Languages.objects.create(code="fy", language_en="frisian", language_ru="фризский", national_language="frysk")
    Languages.objects.create(code="gl", language_en="galician", language_ru="галицкий", national_language="galego")
    Languages.objects.create(code="ka", language_en="georgian", language_ru="грузинский", national_language="ქართველი")
    Languages.objects.create(code="de", language_en="german", language_ru="Немецкий", national_language="Deutsch")
    Languages.objects.create(code="el", language_en="greek", language_ru="греческий", national_language="Ελληνικά")
    Languages.objects.create(code="gu", language_en="gujarati", language_ru="гуджарати", national_language="ગુજરાતી")
    Languages.objects.create(code="ht", language_en="haitian", language_ru="гаитянин", national_language="ayisyen")
    Languages.objects.create(code="ha", language_en="hausa", language_ru="хауса", national_language="hausa")
    Languages.objects.create(code="haw", language_en="hawaiian", language_ru="гавайский",
                             national_language="Ōlelo Hawaiʻi")
    Languages.objects.create(code="iw", language_en="hebrew", language_ru="иврит", national_language="עִברִית")
    Languages.objects.create(code="he", language_en="hebrew", language_ru="иврит", national_language="hebrew")
    Languages.objects.create(code="hi", language_en="hindi", language_ru="хинди", national_language="हिंदी")
    Languages.objects.create(code="hmn", language_en="hmong", language_ru="хмонг", national_language="hmoob")
    Languages.objects.create(code="hu", language_en="hungarian", language_ru="венгерский язык",
                             national_language="Magyar")
    Languages.objects.create(code="is", language_en="icelandic", language_ru="исландский", national_language="íslensku")
    Languages.objects.create(code="ig", language_en="igbo", language_ru="игбо", national_language="igbo")
    Languages.objects.create(code="id", language_en="indonesian", language_ru="индонезийский",
                             national_language="bahasa Indonesia")
    Languages.objects.create(code="ga", language_en="irish", language_ru="ирландский", national_language="Gaeilge")
    Languages.objects.create(code="it", language_en="italian", language_ru="итальянский", national_language="italiano")
    Languages.objects.create(code="ja", language_en="japanese", language_ru="Японский", national_language="日本")
    Languages.objects.create(code="jw", language_en="javanese", language_ru="яванский", national_language="basa jawa")
    Languages.objects.create(code="kn", language_en="kannada", language_ru="каннада", national_language="ಕನ್ನಡ")
    Languages.objects.create(code="kk", language_en="kazakh", language_ru="казах", national_language="қазақ")
    Languages.objects.create(code="km", language_en="khmer", language_ru="кхмерский", national_language="ខ្មែរ")
    Languages.objects.create(code="ko", language_en="korean", language_ru="корейский язык", national_language="한국인")
    Languages.objects.create(code="ku", language_en="kurdish", language_ru="курдский", national_language="Kurdî")
    Languages.objects.create(code="ky", language_en="kyrgyz", language_ru="киргизский", national_language="Кыргызча")
    Languages.objects.create(code="lo", language_en="lao", language_ru="труд", national_language="ແຮງ​ງານ")
    Languages.objects.create(code="la", language_en="latin", language_ru="латинский", national_language="latin")
    Languages.objects.create(code="lv", language_en="latvian", language_ru="Латышский", national_language="latviski")
    Languages.objects.create(code="lt", language_en="lithuanian", language_ru="Литовский язык",
                             national_language="lietuvis")
    Languages.objects.create(code="lb", language_en="luxembourgish", language_ru="люксембургский",
                             national_language="Lëtzebuergesch")
    Languages.objects.create(code="mk", language_en="macedonian", language_ru="македонский",
                             national_language="македонски")
    Languages.objects.create(code="mg", language_en="malagasy", language_ru="малагасийский",
                             national_language="malagasy")
    Languages.objects.create(code="ms", language_en="malay", language_ru="малайский", national_language="melayu")
    Languages.objects.create(code="ml", language_en="malayalam", language_ru="малаялам", national_language="മലയാളം")
    Languages.objects.create(code="mt", language_en="maltese", language_ru="мальтийский", national_language="malti")
    Languages.objects.create(code="mi", language_en="maori", language_ru="маори", national_language="maori")
    Languages.objects.create(code="mr", language_en="marathi", language_ru="маратхи", national_language="मराठी")
    Languages.objects.create(code="mn", language_en="mongolian", language_ru="монгольский", national_language="монгол")
    Languages.objects.create(code="my", language_en="myanmar", language_ru="мьянма", national_language="မြန်မာ")
    Languages.objects.create(code="ne", language_en="nepali", language_ru="непальский", national_language="नेपाली")
    Languages.objects.create(code="no", language_en="norwegian", language_ru="Норвежский", national_language="norsk")
    Languages.objects.create(code="or", language_en="odia", language_ru="ненавидит", national_language="ଘୃଣା କରେ")
    Languages.objects.create(code="ps", language_en="pashto", language_ru="пушту", national_language="پښتو")
    Languages.objects.create(code="fa", language_en="persian", language_ru="персидский", national_language="فارسی")
    Languages.objects.create(code="pl", language_en="polish", language_ru="полировать", national_language="Polskie")
    Languages.objects.create(code="pt", language_en="portuguese", language_ru="португальский",
                             national_language="português")
    Languages.objects.create(code="pa", language_en="punjabi", language_ru="пенджаби", national_language="ਪੰਜਾਬੀ")
    Languages.objects.create(code="ro", language_en="romanian", language_ru="румынский", national_language="Română")
    Languages.objects.create(code="ru", language_en="russian", language_ru="русский", national_language="русский")
    Languages.objects.create(code="sm", language_en="samoan", language_ru="самоан", national_language="samoa")
    Languages.objects.create(code="gd", language_en="scots", language_ru="шотландцы", national_language="Albannaich")
    Languages.objects.create(code="sr", language_en="serbian", language_ru="сербский", national_language="Српски")
    Languages.objects.create(code="st", language_en="sesotho", language_ru="сесото", national_language="sesotho")
    Languages.objects.create(code="sn", language_en="shona", language_ru="шона", national_language="shona")
    Languages.objects.create(code="sd", language_en="sindhi", language_ru="синдхи", national_language="سنڌي")
    Languages.objects.create(code="si", language_en="sinhala", language_ru="сингала", national_language="සිංහල")
    Languages.objects.create(code="sk", language_en="slovak", language_ru="словацкий", national_language="slovenský")
    Languages.objects.create(code="sl", language_en="slovenian", language_ru="словенский",
                             national_language="Slovenščina")
    Languages.objects.create(code="so", language_en="somali", language_ru="сомали", national_language="somaliyeed")
    Languages.objects.create(code="es", language_en="spanish", language_ru="испанский", national_language="Español")
    Languages.objects.create(code="su", language_en="sundanese", language_ru="сунданский",
                             national_language="basa sunda")
    Languages.objects.create(code="sw", language_en="swahili", language_ru="суахили", national_language="kiswahili")
    Languages.objects.create(code="sv", language_en="swedish", language_ru="шведский", national_language="svenska")
    Languages.objects.create(code="tg", language_en="tajik", language_ru="таджик", national_language="тоҷикӣ")
    Languages.objects.create(code="ta", language_en="tamil", language_ru="тамильский", national_language="தமிழ்")
    Languages.objects.create(code="te", language_en="telugu", language_ru="телугу", national_language="తెలుగు")
    Languages.objects.create(code="th", language_en="thai", language_ru="тайский", national_language="ไทย")
    Languages.objects.create(code="tr", language_en="turkish", language_ru="турецкий", national_language="Türk")
    Languages.objects.create(code="uk", language_en="ukrainian", language_ru="украинец",
                             national_language="український")
    Languages.objects.create(code="ur", language_en="urdu", language_ru="урду", national_language="اردو")
    Languages.objects.create(code="ug", language_en="uyghur", language_ru="уйгурский", national_language="uyghur")
    Languages.objects.create(code="uz", language_en="uzbek", language_ru="узбек", national_language="o'zbek")
    Languages.objects.create(code="vi", language_en="vietnamese", language_ru="вьетнамский",
                             national_language="Tiếng Việt")
    Languages.objects.create(code="cy", language_en="welsh", language_ru="валлийский", national_language="Cymraeg")
    Languages.objects.create(code="xh", language_en="xhosa", language_ru="xhosa", national_language="isiXhosa")
    Languages.objects.create(code="yi", language_en="yiddish", language_ru="идиш", national_language="ייִדיש")
    Languages.objects.create(code="yo", language_en="yoruba", language_ru="йоруба", national_language="yoruba")
    Languages.objects.create(code="zu", language_en="zulu", language_ru="зулусский", national_language="zulu")


def rollback_transfer(apps, schema_editor):
    Languages = apps.get_model('common', 'Languages')
    Languages.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_languages'),
    ]

    operations = [
        migrations.RunPython(transfer_languages, rollback_transfer)
    ]
