# Generated by Django 3.1.7 on 2021-10-28 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_auto_20211028_0523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languages',
            options={'ordering': ('code',), 'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
    ]
