# Generated by Django 3.1.7 on 2021-11-02 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_auto_20211028_0539'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmaiWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.SmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(1000)])),
                ('activate', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Registration payment',
                'verbose_name_plural': 'Registration payments',
            },
        ),
    ]
