# Generated by Django 3.1.7 on 2021-11-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_umaiwallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='*unique', max_length=255, unique=True, verbose_name='Message name, unique')),
                ('name_ru', models.CharField(help_text='*unique', max_length=255, null=True, unique=True, verbose_name='Message name, unique')),
                ('name_en', models.CharField(help_text='*unique', max_length=255, null=True, unique=True, verbose_name='Message name, unique')),
                ('name_tr', models.CharField(help_text='*unique', max_length=255, null=True, unique=True, verbose_name='Message name, unique')),
                ('body', models.TextField(max_length=2000, verbose_name='Message text')),
                ('body_ru', models.TextField(max_length=2000, null=True, verbose_name='Message text')),
                ('body_en', models.TextField(max_length=2000, null=True, verbose_name='Message text')),
                ('body_tr', models.TextField(max_length=2000, null=True, verbose_name='Message text')),
            ],
            options={
                'verbose_name': 'Message text',
                'verbose_name_plural': 'Messages Text',
            },
        ),
    ]
