# Generated by Django 3.1.7 on 2021-11-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_messagetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetext',
            name='message_type',
            field=models.CharField(choices=[('shadow_ban', 'shadow_ban')], default='shadow_ban', max_length=255, verbose_name='message type'),
            preserve_default=False,
        ),
    ]
