# Generated by Django 3.1.7 on 2022-01-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_messagetext_message_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmaiAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('version', models.CharField(default='2.14.8', max_length=10)),
            ],
            options={
                'verbose_name': 'Umai account',
                'verbose_name_plural': 'Umai accounts',
            },
        ),
    ]
