# Generated by Django 3.1.7 on 2022-01-10 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_umaiaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='umaiaccount',
            old_name='login',
            new_name='phone',
        ),
    ]
