# Generated by Django 3.1.7 on 2022-01-11 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_auto_20220110_1317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UmaiAccount',
        ),
    ]
