# Generated by Django 3.1.7 on 2022-01-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0028_delete_umaiaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='umaiwallet',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='umaiwallet',
            name='version',
            field=models.CharField(blank=True, default='2.14.8', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='umaiwallet',
            name='wallet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
