# Generated by Django 3.1.7 on 2022-04-05 07:11

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_auto_20220111_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('file', models.FileField(help_text='Image that you want to store', max_length=1000, upload_to=common.utils.upload_file_with_unique_name)),
                ('video_url', models.URLField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
