# Generated by Django 3.1.7 on 2022-04-08 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_filevideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filevideo',
            old_name='file',
            new_name='video',
        ),
        migrations.AddField(
            model_name='filevideo',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filevideos', to='common.file'),
        ),
    ]
