# Generated by Django 3.1.7 on 2022-04-15 11:51

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_auto_20220408_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filevideo',
            name='video',
            field=models.FileField(help_text='Image that you want to store', max_length=1000, upload_to=common.utils.upload_file_video_with_unique_name),
        ),
    ]
