# Generated by Django 3.1.7 on 2022-04-26 11:24

import common.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0033_auto_20220415_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsWallpaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('web_image', models.ImageField(help_text='Web wallpaper that you want to store', max_length=1000, upload_to=common.utils.upload_file_with_unique_name)),
                ('mobile_image', models.ImageField(help_text='Mobile wallpaper that you want to store', max_length=1000, upload_to=common.utils.upload_file_with_unique_name)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SetWallpaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallpaper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_wallpapers', to='common.commentswallpaper')),
            ],
            options={
                'verbose_name': 'Set wallpaper',
                'verbose_name_plural': 'Set wallpapers',
            },
        ),
    ]
