# Generated by Django 3.1.7 on 2022-04-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_commentswallpaper_setwallpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentswallpaper',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
