# Generated by Django 3.1.7 on 2022-04-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0035_commentswallpaper_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SetWallpaper',
        ),
    ]
