# Generated by Django 3.1.7 on 2022-06-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0036_delete_setwallpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_link', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
