# Generated by Django 3.1.7 on 2022-09-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0037_linkapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_service', models.BooleanField(default=True, verbose_name='Message name, unique')),
                ('nikita_service', models.BooleanField(default=True, verbose_name='Message text')),
            ],
            options={
                'verbose_name': 'Sms service',
                'verbose_name_plural': 'Sms services',
            },
        ),
    ]
