# Generated by Django 3.1.7 on 2022-09-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0038_smsservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsservices',
            name='nikita_service',
            field=models.BooleanField(default=True, verbose_name='Nikita Service'),
        ),
        migrations.AlterField(
            model_name='smsservices',
            name='twilio_service',
            field=models.BooleanField(default=True, verbose_name='Twilio service'),
        ),
    ]
