# Generated by Django 3.1.7 on 2022-09-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0040_blockedips'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsservices',
            name='bird_message',
            field=models.BooleanField(default=True, verbose_name='Bird message Service'),
        ),
    ]
