# Generated by Django 3.1.7 on 2022-10-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0041_smsservices_bird_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryCodeSwitcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enable', models.BooleanField(default=True, verbose_name='Enable')),
            ],
            options={
                'verbose_name': 'Temporary code switcher',
            },
        ),
    ]
