# Generated by Django 3.1.7 on 2022-12-28 04:21

import common.fields
import common.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0042_temporarycodeswitcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=common.fields.WEBPField(help_text='Image that you want to store', max_length=1000, upload_to=common.utils.upload_file_with_unique_name),
        ),
    ]
