# Generated by Django 3.1.7 on 2022-12-28 05:52

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0043_auto_20221228_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.ImageField(help_text='Image that you want to store', max_length=1000, upload_to=common.utils.upload_file_with_unique_name),
        ),
    ]
