# Generated by Django 3.1.7 on 2022-12-30 08:02

import common.utils
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0044_auto_20221228_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, help_text='Image that you want to store', keep_meta=True, max_length=1000, quality=-1, scale=None, size=[1920, 1080], upload_to=common.utils.upload_file_with_unique_name),
        ),
    ]
