# Generated by Django 3.1.7 on 2023-01-11 09:00

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0048_auto_20221230_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.ImageField(help_text='Image that you want to store', max_length=1000, upload_to=common.utils.upload_file_with_unique_name),
        ),
    ]
