# Generated by Django 3.1.7 on 2023-12-19 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0052_countryandcity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryAndCity',
        ),
    ]
