# Generated by Django 3.1.7 on 2024-01-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0053_delete_countryandcity'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='name_zh',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_zh',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='name_de',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='name_zh',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='messagetext',
            name='body_de',
            field=models.TextField(max_length=2000, null=True, verbose_name='Message text'),
        ),
        migrations.AddField(
            model_name='messagetext',
            name='body_zh',
            field=models.TextField(max_length=2000, null=True, verbose_name='Message text'),
        ),
        migrations.AddField(
            model_name='messagetext',
            name='name_de',
            field=models.CharField(help_text='*unique', max_length=255, null=True, unique=True, verbose_name='Message name, unique'),
        ),
        migrations.AddField(
            model_name='messagetext',
            name='name_zh',
            field=models.CharField(help_text='*unique', max_length=255, null=True, unique=True, verbose_name='Message name, unique'),
        ),
    ]
