# Generated by Django 3.1.7 on 2025-05-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0054_auto_20240118_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='is_paid_subscription',
            field=models.BooleanField(default=False, verbose_name='Платная подписка'),
        ),
    ]
