# Generated by Django 3.1.7 on 2025-09-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0055_country_is_paid_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.CharField(max_length=255),
        ),
    ]

