# Generated by Django 3.1.7 on 2025-10-01 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0056_auto_20250923_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
        migrations.CreateModel(
            name='CountryInvoiceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax', models.PositiveIntegerField(default=0)),
                ('tax_id', models.CharField(default='', max_length=255)),
                ('name', models.CharField(max_length=455)),
                ('city', models.CharField(default='', max_length=255)),
                ('address', models.CharField(max_length=455)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_info', to='common.country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
