# Generated by Django 3.1.7 on 2025-11-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0057_auto_20251001_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryinvoiceinfo',
            name='account_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='countryinvoiceinfo',
            name='account_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='countryinvoiceinfo',
            name='bank',
            field=models.CharField(default='', max_length=455),
        ),
        migrations.AddField(
            model_name='countryinvoiceinfo',
            name='iban',
            field=models.CharField(default='', max_length=455),
        ),
        migrations.AddField(
            model_name='countryinvoiceinfo',
            name='routing_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='countryinvoiceinfo',
            name='swift_code',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='countryinvoiceinfo',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='countryinvoiceinfo',
            name='tax',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='countryinvoiceinfo',
            name='tax_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
