# Generated by Django 3.1.7 on 2025-11-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0058_auto_20251111_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryinvoiceinfo',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='countryinvoiceinfo',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='countryinvoiceinfo',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='countryinvoiceinfo',
            name='iban',
        ),
        migrations.RemoveField(
            model_name='countryinvoiceinfo',
            name='routing_number',
        ),
        migrations.RemoveField(
            model_name='countryinvoiceinfo',
            name='swift_code',
        ),
        migrations.AlterField(
            model_name='countryinvoiceinfo',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
