# Generated by Django 3.1.7 on 2025-11-11 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0059_auto_20251111_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countryinvoiceinfo',
            old_name='title',
            new_name='bank_details',
        ),
    ]
