# Generated by Django 3.1.7 on 2025-12-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0060_auto_20251111_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('organization', 'organization'), ('coupon', 'coupon')], default='organization', max_length=50),
        ),
    ]
