# Generated by Django 3.1.7 on 2025-12-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0061_file_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_type',
        ),
    ]
