# Generated by Django 3.2 on 2026-01-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0062_remove_file_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGPTSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.CharField(help_text='API ключ для доступа к ChatGPT. Формат: sk-proj-...', max_length=255, verbose_name='OpenAI API Key')),
                ('model', models.CharField(default='gpt-3.5-turbo', help_text='Модель для использования (gpt-3.5-turbo, gpt-4, gpt-4o-mini и т.д.)', max_length=50, verbose_name='Модель GPT')),
                ('is_active', models.BooleanField(default=True, help_text='Включить/выключить интеграцию с ChatGPT', verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Настройки ChatGPT',
                'verbose_name_plural': 'Настройки ChatGPT',
            },
        ),
    ]
