# Generated by Django 3.1.7 on 2026-01-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0062_remove_file_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='image_url',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='filevideo',
            name='video_url',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
    ]
