# Generated by Django 3.2 on 2026-01-06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0063_chatgptsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgptsettings',
            name='temperature',
            field=models.FloatField(
                default=0.9,
                help_text='Уровень креативности ответов (0.0 - 2.0)',
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(2.0)
                ],
                verbose_name='Temperature'
            ),
        ),
    ]
