# Generated by Django 3.2 on 2026-01-06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0065_chatgptsettings_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgptsettings',
            name='max_tokens',
            field=models.PositiveIntegerField(
                default=500,
                help_text='Максимальное количество токенов в ответе (50-4000). 500 токенов ≈ 350-400 слов',
                validators=[
                    django.core.validators.MinValueValidator(50),
                    django.core.validators.MaxValueValidator(4000)
                ],
                verbose_name='Max Tokens'
            ),
        ),
        migrations.AddField(
            model_name='chatgptsettings',
            name='min_sentences',
            field=models.PositiveIntegerField(
                default=6,
                help_text='Минимальное количество предложений в описании',
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(20)
                ],
                verbose_name='Мин. предложений'
            ),
        ),
        migrations.AddField(
            model_name='chatgptsettings',
            name='max_sentences',
            field=models.PositiveIntegerField(
                default=10,
                help_text='Максимальное количество предложений в описании',
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(30)
                ],
                verbose_name='Макс. предложений'
            ),
        ),
        migrations.AddField(
            model_name='chatgptsettings',
            name='min_words',
            field=models.PositiveIntegerField(
                default=150,
                help_text='Примерное минимальное количество слов в описании',
                validators=[
                    django.core.validators.MinValueValidator(20),
                    django.core.validators.MaxValueValidator(1000)
                ],
                verbose_name='Мин. слов'
            ),
        ),
        migrations.AddField(
            model_name='chatgptsettings',
            name='max_words',
            field=models.PositiveIntegerField(
                default=250,
                help_text='Примерное максимальное количество слов в описании',
                validators=[
                    django.core.validators.MinValueValidator(50),
                    django.core.validators.MaxValueValidator(2000)
                ],
                verbose_name='Макс. слов'
            ),
        ),
    ]
