# Generated by Django 3.1.7 on 2026-01-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0066_chatgptsettings_generation_params'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatgptsettings',
            options={'verbose_name': 'ChatGPT Settings', 'verbose_name_plural': 'ChatGPT Settings'},
        ),
    ]
