# Generated by Django 3.1.7 on 2026-01-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0067_auto_20260108_1111'),
        ('common', '0067_auto_20260107_1354'),
    ]

    operations = [
    ]
