# Generated by Django 3.1.7 on 2026-01-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0067_auto_20260108_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgptsettings',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatgptsettings',
            name='login',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatgptsettings',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
