# Generated by Django 3.1.7 on 2026-01-09 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0068_auto_20260109_0900'),
        ('common', '0068_merge_20260108_1608'),
    ]

    operations = [
    ]
