export const AUTHENTICATE_USER = {
  REQUEST: 'AUTHENTICATE_USER_REQUEST',
  SUCCESS: 'AUTHENTICATE_USER_SUCCESS',
  FAILURE: 'AUTHENTICATE_USER_FAILURE'
}

export const PROFILE_UPDATE = {
  REQUEST: 'PROFILE_UPDATE_REQUEST',
  SUCCESS: 'PROFILE_UPDATE_SUCCESS',
  FAILURE: 'PROFILE_UPDATE_FAILURE'
}

export const GET_USER = {
  REQUEST: 'GET_USER_REQUEST',
  SUCCESS: 'GET_USER_SUCCESS',
  FAILURE: 'GET_USER_FAILURE'
}

export const LOGIN_USER = {
  REQUEST: 'LOGIN_USER_REQUEST',
  SUCCESS: 'LOGIN_USER_SUCCESS',
  FAILURE: 'LOGIN_USER_FAILURE'
}

export const GET_PHONE_NUMBERS = {
  REQUEST: 'GET_PHONE_NUMBERS_REQUEST',
  SUCCESS: 'GET_PHONE_NUMBERS_SUCCESS',
  FAILURE: 'GET_PHONE_NUMBERS_FAILURE'
}

export const SET_PHONE_NUMBERS = {
  REQUEST: 'SET_PHONE_NUMBERS_REQUEST',
  SUCCESS: 'SET_PHONE_NUMBERS_SUCCESS',
  FAILURE: 'SET_PHONE_NUMBERS_FAILURE'
}

export const GET_SOCIALS = {
  REQUEST: 'GET_SOCIALS_REQUEST',
  SUCCESS: 'GET_SOCIALS_SUCCESS',
  FAILURE: 'GET_SOCIALS_FAILURE'
}

export const SET_SOCIALS = {
  REQUEST: 'SET_SOCIALS_REQUEST',
  SUCCESS: 'SET_SOCIALS_SUCCESS',
  FAILURE: 'SET_SOCIALS_FAILURE'
}

export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_USER_LOCATION = 'SET_USER_LOCATION';

export const CREATE_ORG = {
  REQUEST: 'CREATE_ORG_REQUEST',
  SUCCESS: 'CREATE_ORG_SUCCESS',
  FAILURE: 'CREATE_ORG_FAILURE'
}

export const GET_ORG = {
  REQUEST: 'GET_ORG_REQUEST',
  SUCCESS: 'GET_ORG_SUCCESS',
  FAILURE: 'GET_ORG_FAILURE'
}

export const GET_ORG_LIST = {
  REQUEST: 'GET_ORG_LIST_REQUEST',
  SUCCESS: 'GET_ORG_LIST_SUCCESS',
  FAILURE: 'GET_ORG_LIST_FAILURE'
}

export const GET_ORG_TYPES = {
  REQUEST: 'GET_ORG_TYPES_REQUEST',
  SUCCESS: 'GET_ORG_TYPES_SUCCESS',
  FAILURE: 'GET_ORG_TYPES_FAILURE'
}

export const GET_CURRENCY = {
  REQUEST: 'GET_CURRENCY_REQUEST',
  SUCCESS: 'GET_CURRENCY_SUCCESS',
  FAILURE: 'GET_CURRENCY_FAILURE'
}

export const GET_CARD_BACKGROUNDS = {
  REQUEST: 'GET_CARD_BACKGROUNDS_REQUEST',
  SUCCESS: 'GET_CARD_BACKGROUNDS_SUCCESS',
  FAILURE: 'GET_CARD_BACKGROUNDS_FAILURE'
}

export const SUBSCRIBE_ORGANIZATION = 'SUBSCRIBE_ORGANIZATION';
export const SET_AUTH_CHANGE_CODE = 'SET_AUTH_CHANGE_CODE';
export const TOGGLE_SHOW_CONTACT = 'TOGGLE_SHOW_CONTACT';
export const SET_PRE_ORGANIZATION = 'SET_PRE_ORGANIZATION';
export const SET_USER_GEO = 'SET_USER_GEO';

export const GET_ORG_RECEIPTS = {
  REQUEST: 'GET_ORG_RECEIPTS_REQUEST',
  SUCCESS: 'GET_ORG_RECEIPTS_SUCCESS',
  FAILURE: 'GET_ORG_RECEIPTS_FAILURE'
}

export const GET_ORG_RECEIPT_DETAIL = {
  REQUEST: 'GET_ORG_RECEIPT_DETAIL_REQUEST',
  SUCCESS: 'GET_ORG_RECEIPT_DETAIL_SUCCESS',
  FAILURE: 'GET_ORG_RECEIPT_DETAIL_FAILURE'
}