# Generated by Django 3.0.7 on 2020-07-07 17:52

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Для создания местоположения', null=True, srid=4326),
        ),
    ]
