# Generated by Django 3.0.7 on 2020-07-07 18:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Для создания местоположения', null=True, srid=4326),
        ),
    ]
