# Generated by Django 3.0.7 on 2020-07-08 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_countries_currencies_data_migration'),
        ('organizations', '0004_organization_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('fixed', 'fixed'), ('cumulative', 'cumulative')], default='fixed', max_length=20)),
                ('percent', models.PositiveSmallIntegerField()),
                ('limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='common.Currency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='organizations.Organization')),
            ],
            options={
                'ordering': ('type', 'percent', 'limit'),
            },
        ),
    ]
