# Generated by Django 3.0.7 on 2020-07-08 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_countries_currencies_data_migration'),
        ('organizations', '0005_discountcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcard',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.File'),
        ),
    ]
