# Generated by Django 3.0.7 on 2020-07-10 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_countries_currencies_data_migration'),
        ('organizations', '0006_discountcard_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='currency',
            field=models.ForeignKey(default='KGS', on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='common.Currency'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='show_contacts',
            field=models.BooleanField(default=False),
        ),
    ]
