# Generated by Django 3.0.7 on 2020-07-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_organization_types_data_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationcategory',
            options={'ordering': ('name',), 'verbose_name_plural': 'Organization categories'},
        ),
        migrations.AlterModelOptions(
            name='organizationtype',
            options={'ordering': ('title',)},
        ),
    ]
