# Generated by Django 3.0.8 on 2020-07-14 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20200712_2009'),
        ('organizations', '0010_organization_types_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.ForeignKey(default='KG', on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='common.Country'),
        ),
    ]
