# Generated by Django 3.0.8 on 2020-07-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_organization_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
