# Generated by Django 3.0.8 on 2020-07-15 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0012_organization_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='discountcard',
            options={'ordering': ('organization', 'type', 'percent', 'limit')},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='discountcard',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='discountcard',
            constraint=models.UniqueConstraint(fields=('organization', 'type', 'percent'), name='unique_cards_of_organization'),
        ),
        migrations.AddField(
            model_name='cardownership',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owners', to='organizations.DiscountCard'),
        ),
        migrations.AddField(
            model_name='cardownership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='cardownership',
            constraint=models.UniqueConstraint(fields=('card', 'user'), name='unique_cards_of_user'),
        ),
    ]
