# Generated by Django 3.0.8 on 2020-07-16 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0013_auto_20200715_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationClientFinancialStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16)),
                ('total_saved', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16)),
            ],
            options={
                'verbose_name_plural': 'Organization client financial statuses',
            },
        ),
        migrations.RemoveField(
            model_name='cardownership',
            name='card',
        ),
        migrations.RemoveField(
            model_name='cardownership',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='discountcard',
            options={'ordering': ('organization', 'type', 'limit', 'percent')},
        ),
        migrations.RemoveConstraint(
            model_name='discountcard',
            name='unique_cards_of_organization',
        ),
        migrations.AddField(
            model_name='discountcard',
            name='next_cumulative',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_cumulative', to='organizations.DiscountCard'),
        ),
        migrations.AddConstraint(
            model_name='discountcard',
            constraint=models.UniqueConstraint(fields=('organization', 'type', 'percent'), name='unique_percents_of_organization'),
        ),
        migrations.AddConstraint(
            model_name='discountcard',
            constraint=models.UniqueConstraint(fields=('organization', 'type', 'limit'), name='unique_limits_of_organization'),
        ),
        migrations.DeleteModel(
            name='CardOwnership',
        ),
        migrations.AddField(
            model_name='organizationclientfinancialstatus',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='organizations.DiscountCard'),
        ),
        migrations.AddField(
            model_name='organizationclientfinancialstatus',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_statuses', to='organizations.Organization'),
        ),
        migrations.AddField(
            model_name='organizationclientfinancialstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='organizationclientfinancialstatus',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='unique_statuses_of_user_in_organization'),
        ),
    ]
