# Generated by Django 3.0.8 on 2020-07-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_auto_20200714_1501'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='discountcard',
            constraint=models.UniqueConstraint(fields=('organization', 'type', 'percent'), name='unique_cards'),
        ),
    ]
