# Generated by Django 3.0.8 on 2020-07-16 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20200712_2009'),
        ('organizations', '0014_auto_20200716_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backgrounds', to='common.File')),
            ],
        ),
    ]
