# Generated by Django 3.0.8 on 2020-07-21 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_cardbackground'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('can_check_attendance', models.BooleanField(default=False)),
                ('can_see_stats', models.BooleanField(default=False)),
                ('can_edit_organization', models.BooleanField(default=False)),
                ('accepted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_partnerships', to='organizations.Organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_partnerships', to='organizations.Organization')),
            ],
        ),
        migrations.AddConstraint(
            model_name='partnership',
            constraint=models.UniqueConstraint(fields=('requested_by', 'accepted_by'), name='unique_partnerships'),
        ),
    ]
