# Generated by Django 3.0.8 on 2020-07-22 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20200712_2009'),
        ('organizations', '0016_auto_20200721_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_banners', to='organizations.Organization')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='common.File')),
                ('linked_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leading_banners', to='organizations.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
