# Generated by Django 3.0.8 on 2020-07-23 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('msg_content', models.CharField(max_length=800)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_organization', to='organizations.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
