# Generated by Django 3.0.8 on 2020-07-26 11:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_auto_20200725_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='host_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_banners', to='organizations.Organization'),
        ),
    ]
