# Generated by Django 3.0.8 on 2020-07-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_send_message',
            field=models.BooleanField(default=False),
        ),
    ]
