# Generated by Django 3.0.8 on 2020-07-30 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_auto_20200726_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationclientfinancialstatus',
            name='total_saved',
        ),
        migrations.RemoveField(
            model_name='organizationclientfinancialstatus',
            name='total_spent',
        ),
    ]
