# Generated by Django 3.0.8 on 2020-08-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_auto_20200730_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receivers_count',
            field=models.IntegerField(default=0),
        ),
    ]
