# Generated by Django 3.0.8 on 2020-08-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_message_receivers_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='organization_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
