# Generated by Django 3.0.8 on 2020-08-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0022_message_organization_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-created_at',)},
        ),
    ]
