# Generated by Django 3.0.8 on 2020-08-14 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0024_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ('-arrival_time',)},
        ),
    ]
