# Generated by Django 3.0.8 on 2020-08-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0025_auto_20200814_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='arrival_checker_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='departure_checker_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
