# Generated by Django 3.0.8 on 2020-08-26 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0026_auto_20200825_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receivers_count',
        ),
        migrations.AddField(
            model_name='message',
            name='message_to',
            field=models.CharField(choices=[('organization_followers', 'organization_followers'), ('partners_members', 'partners_members'), ('partners_followers', 'partners_followers')], default='organization_followers', max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_partners',
            field=models.ManyToManyField(related_name='receiver_partners', to='organizations.Organization'),
        ),
        migrations.AddField(
            model_name='message',
            name='receivers',
            field=models.ManyToManyField(related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
