# Generated by Django 3.0.8 on 2020-08-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0026_auto_20200825_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receivers_count',
        ),
        migrations.AddField(
            model_name='attendance',
            name='arrival_checker_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='departure_checker_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_partners',
            field=models.ManyToManyField(related_name='receiver_partners', to='organizations.Organization'),
        ),
    ]
