# Generated by Django 3.0.8 on 2020-09-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0026_auto_20200825_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
