# Generated by Django 3.0.8 on 2020-08-26 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0026_auto_20200825_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receivers_count',
        ),
    ]
