# Generated by Django 3.0.8 on 2020-08-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0027_remove_message_receivers_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver_partners',
            field=models.ManyToManyField(related_name='receiver_partners', to='organizations.Organization'),
        ),
    ]
