# Generated by Django 3.0.8 on 2020-09-03 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0027_auto_20200826_1059'),
        ('organizations', '0027_attendance_organization_name'),
    ]

    operations = [
    ]
