# Generated by Django 3.0.8 on 2020-09-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0028_merge_20200903_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcard',
            name='type',
            field=models.CharField(choices=[('fixed', 'fixed'), ('cumulative', 'cumulative'), ('cashback', 'cashback')], default='fixed', max_length=20),
        ),
    ]
