# Generated by Django 3.0.8 on 2020-09-14 00:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0028_merge_20200903_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationclientfinancialstatus',
            name='accrued_cashback',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='discountcard',
            name='percent',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='discountcard',
            name='type',
            field=models.CharField(choices=[('fixed', 'fixed'), ('cumulative', 'cumulative'), ('cashback', 'cashback')], default='fixed', max_length=20),
        ),
    ]
