# Generated by Django 3.0.8 on 2020-09-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0029_auto_20200914_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='can_share_cashback',
            field=models.BooleanField(default=False),
        ),
    ]
