# Generated by Django 3.0.7 on 2020-09-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0030_partnership_can_share_cashback'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='can_share_cumulative',
            field=models.BooleanField(default=False),
        ),
    ]
