# Generated by Django 3.0.8 on 2020-09-23 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_city'),
        ('organizations', '0033_auto_20200920_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='common.City'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.ForeignKey(default='KG', on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='common.Country'),
        ),
    ]
