# Generated by Django 3.0.8 on 2020-09-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0034_auto_20200923_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationcategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizationcategory',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizationcategory',
            name='name_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='title_tr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
