# Generated by Django 3.0.8 on 2020-12-04 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0036_types_categories_translation_data_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=255)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_integration_link', to='organizations.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
