# Generated by Django 3.0.8 on 2020-12-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0037_instagramintegration'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramintegration',
            name='account_full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instagramintegration',
            name='account_user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instagramintegration',
            name='account_user_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instagramintegration',
            name='profile_photo',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
