# Generated by Django 3.1.7 on 2021-04-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0038_auto_20201221_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
