# Generated by Django 3.1.7 on 2021-04-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0039_organization_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='running_purchase_id',
            field=models.PositiveIntegerField(default=1, help_text='For transaction purchase ids'),
        ),
    ]
