# Generated by Django 3.1.7 on 2021-05-20 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0040_organization_running_purchase_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonItemsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='partnership',
            name='can_share_items',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='items_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='organizations.commonitemsgroup'),
        ),
    ]
