# Generated by Django 3.1.7 on 2021-05-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0041_auto_20210520_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='has_delivery',
            field=models.BooleanField(default=True, help_text='Does organization have courier delivery?'),
        ),
        migrations.AddField(
            model_name='organization',
            name='has_self_pick_up',
            field=models.BooleanField(default=True, help_text='Does organization have self pick up?'),
        ),
    ]
