# Generated by Django 3.1.7 on 2021-05-26 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_auto_20210216_1404'),
        ('organizations', '0042_auto_20210521_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramintegration',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instagram_integrations', to='common.file'),
        ),
    ]
