# Generated by Django 3.1.7 on 2021-06-01 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_auto_20210216_1404'),
        ('organizations', '0043_instagramintegration_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link', models.URLField(max_length=500)),
                ('link_type', models.CharField(choices=[('item', 'item'), ('organization', 'organization'), ('external', 'external')], default='external', max_length=25)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotlinks', to='common.file')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotlinks', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
