# Generated by Django 3.1.7 on 2021-06-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0044_hotlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotlink',
            name='linked_item_id',
            field=models.SlugField(blank=True, max_length=225, null=True),
        ),
    ]
