# Generated by Django 3.1.7 on 2021-06-02 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_remove_iteminstagramdata_post_pk'),
        ('organizations', '0045_hotlink_linked_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotlink',
            name='linked_item_id',
        ),
        migrations.AddField(
            model_name='hotlink',
            name='linked_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotlinks_to_organization', to='shop.shopitem'),
        ),
        migrations.AddField(
            model_name='hotlink',
            name='linked_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotlinks_to_organization', to='organizations.organization'),
        ),
    ]
