# Generated by Django 3.1.7 on 2021-06-19 17:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_auto_20210216_1404'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0046_auto_20210602_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPromo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_cashback', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('cashback', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_promos', to='common.file')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promo', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromoEditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_role', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_edit_logs', to=settings.AUTH_USER_MODEL)),
                ('employee_avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.file')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='organizations.organizationpromo')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
