# Generated by Django 3.1.7 on 2021-07-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0047_auto_20210626_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotlink',
            name='link',
        ),
        migrations.AddField(
            model_name='hotlink',
            name='content',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotlink',
            name='link_type',
            field=models.CharField(choices=[('link', 'link'), ('contact', 'contact'), ('collection', 'collection')], max_length=25),
        ),
    ]
