# Generated by Django 3.1.7 on 2021-07-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0047_auto_20210626_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_delivery_service',
            field=models.BooleanField(default=False),
        ),
    ]
