# Generated by Django 3.1.7 on 2021-07-16 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_auto_20210216_1404'),
        ('organizations', '0048_organization_is_delivery_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='common.city'),
        ),
    ]
