# Generated by Django 3.1.7 on 2021-07-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0048_auto_20210720_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='description_lang',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='title_lang',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
