# Generated by Django 3.1.7 on 2021-07-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0049_auto_20210716_0817'),
        ('organizations', '0048_auto_20210720_1741'),
    ]

    operations = [
    ]
