# Generated by Django 3.1.7 on 2021-07-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0050_merge_20210722_0915'),
        ('organizations', '0049_auto_20210722_1303'),
    ]

    operations = [
    ]
