# Generated by Django 3.1.7 on 2021-08-06 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_merge_20210723_1022'),
        ('organizations', '0051_merge_20210723_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotlinkCollectionSubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotlink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_subcategories', to='organizations.hotlink')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotlinks', to='shop.itemsubcategory')),
            ],
            options={
                'verbose_name_plural': 'hotlink collection subcategories',
            },
        ),
        migrations.CreateModel(
            name='HotlinkCollectionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotlink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='organizations.hotlink')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotlinks', to='shop.shopitem')),
            ],
        ),
        migrations.AddConstraint(
            model_name='hotlinkcollectionsubcategory',
            constraint=models.UniqueConstraint(fields=('hotlink', 'subcategory'), name='one_subcategory_per_hotlink_collection'),
        ),
        migrations.AddConstraint(
            model_name='hotlinkcollectionitem',
            constraint=models.UniqueConstraint(fields=('hotlink', 'item'), name='one_item_per_hotlink_collection'),
        ),
    ]
