# Generated by Django 3.1.7 on 2021-08-09 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_merge_20210723_1022'),
        ('organizations', '0052_auto_20210806_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotlinkCollectionLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=500)),
                ('hotlink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_links', to='organizations.hotlink')),
                ('linked_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_in_collections', to='shop.shopitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
