# Generated by Django 3.1.7 on 2021-08-11 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0053_hotlinkcollectionlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationpromo',
            name='total_cashback',
            field=models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999)]),
        ),
    ]
