# Generated by Django 3.1.7 on 2021-08-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0054_auto_20210811_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotlink',
            name='link_type',
            field=models.CharField(choices=[('link', 'link'), ('contact', 'contact'), ('collection', 'collection'), ('partners', 'partners')], max_length=25),
        ),
    ]
