# Generated by Django 3.1.7 on 2021-09-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0055_auto_20210830_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='has_adult_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='is_adult',
            field=models.BooleanField(default=False),
        ),
    ]
