# Generated by Django 3.1.7 on 2021-09-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0055_auto_20210830_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_bank',
            field=models.BooleanField(default=False),
        ),
    ]
