# Generated by Django 3.1.7 on 2021-09-09 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0056_auto_20210909_0416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='has_adult_content',
        ),
    ]
