# Generated by Django 3.1.7 on 2021-09-13 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0056_organization_is_bank'),
        ('organizations', '0057_remove_organization_has_adult_content'),
    ]

    operations = [
    ]
