# Generated by Django 3.1.7 on 2021-09-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0058_merge_20210913_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbackgroup',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='commonitemsgroup',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cumulativegroup',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
