# Generated by Django 3.1.7 on 2021-09-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0059_auto_20210920_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_deliver',
            field=models.BooleanField(default=False),
        ),
    ]
