# Generated by Django 3.1.7 on 2021-09-21 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_version'),
        ('organizations', '0059_auto_20210920_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название сервиса')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='common.file')),
                ('subcategory', models.ManyToManyField(related_name='services', to='organizations.OrganizationType')),
            ],
        ),
    ]
