# Generated by Django 3.1.7 on 2021-09-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0061_merge_20210923_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название сервиса'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название сервиса'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Название сервиса'),
        ),
    ]
