# Generated by Django 3.1.7 on 2021-09-28 05:06

import django.core.validators
from django.db import migrations, models

def transfer_ordering(apps, schema_editor):
    Service = apps.get_model('organizations.Service')
    count = 1
    for service in Service.objects.all():
        service.ordering = count
        count += 1
        service.save()


def rollback_transfer(apps, schema_editor):
    Service = apps.get_model('webapp.Article')
    for service in Service.objects.all():
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0062_auto_20210923_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='service',
            name='ordering',
            field=models.SmallIntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Service ordering'),
        ),
        migrations.RunPython(transfer_ordering, rollback_transfer)
    ]
