# Generated by Django 3.1.7 on 2021-09-28 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0063_auto_20210928_0506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('ordering',), 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
