# Generated by Django 3.1.7 on 2021-09-28 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0064_auto_20210928_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='ordering',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Service ordering'),
        ),
    ]
