# Generated by Django 3.1.7 on 2021-09-28 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0066_auto_20210928_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='ordering',
            field=models.SmallIntegerField(blank=True, help_text='Не заполнять при создании!', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Service ordering'),
        ),
    ]
