# Generated by Django 3.1.7 on 2021-10-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0068_auto_20211018_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_discounts',
            field=models.BooleanField(default=False),
        ),
    ]
