# Generated by Django 3.1.7 on 2021-11-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0069_service_is_discounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_under_review',
            field=models.BooleanField(default=False),
        ),
    ]
