# Generated by Django 3.1.7 on 2021-12-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0070_organization_is_under_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='verification_status',
            field=models.CharField(choices=[('verified', 'verified'), ('not_verified', 'not_verified'), ('under_review', 'under_review')], default='not_verified', max_length=255),
        ),
    ]
