# Generated by Django 3.1.7 on 2021-12-08 04:47

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0071_organization_verification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationVerificationUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=255, verbose_name='User name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=255, region=None, unique=True, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Users data for verification organization',
                'verbose_name_plural': 'Users data for verification organization',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='verification_users_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='organizations.organizationverificationusers'),
        ),
    ]
