# Generated by Django 3.1.7 on 2021-12-08 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0072_auto_20211208_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='verification_users_data',
        ),
        migrations.AddField(
            model_name='organizationverificationusers',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_users_data', to='organizations.organization'),
        ),
    ]
