# Generated by Django 3.1.7 on 2021-12-08 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0073_auto_20211208_0600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Users data for verification organization', 'verbose_name_plural': 'Users data for verification organization'},
        ),
        migrations.DeleteModel(
            name='OrganizationVerificationUsers',
        ),
    ]
