# Generated by Django 3.1.7 on 2021-12-08 12:19

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0074_auto_20211208_0935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('title',)},
        ),
        migrations.CreateModel(
            name='OrganizationVerificationUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=255, verbose_name='User name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=255, region=None, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_users_data', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Users data for verification organization',
                'verbose_name_plural': 'Users data for verification organization',
            },
        ),
    ]
