# Generated by Django 3.1.7 on 2021-12-09 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0075_auto_20211208_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationverificationusers',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_users_data', to='organizations.organization'),
        ),
    ]
