# Generated by Django 3.1.7 on 2022-02-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0076_auto_20211209_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='avg_check',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
