# Generated by Django 3.1.7 on 2022-02-16 07:10

from django.db import migrations, models


def fill_add_item_date(apps, schema_editor):

    Organization = apps.get_model('organizations', 'Organization')

    for row in Organization.objects.all():
        if row.shop_items.exists():
            row.add_item_date = row.shop_items.last().created_at
            row.save()
        else:
            row.add_item_date = row.created_at
            row.save()


class Migration(migrations.Migration):
    dependencies = [
        ('organizations', '0077_organization_avg_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='add_item_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(fill_add_item_date),
        migrations.AlterField(
            model_name='organization',
            name='add_item_date',
            field=models.DateTimeField(),
        )
    ]
