# Generated by Django 3.1.7 on 2022-02-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0078_organization_add_item_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='add_item_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
