# Generated by Django 3.1.7 on 2022-03-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_auto_20211206_1122'),
        ('organizations', '0079_auto_20220216_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category_of_item',
            field=models.ManyToManyField(related_name='services', to='shop.ItemCategory'),
        ),
    ]
