# Generated by Django 3.1.7 on 2022-02-16 08:55

from django.db import migrations, models


def add_data_in_subscriptions(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    Subscription = apps.get_model('organizations', 'Subscription')
    User = apps.get_model('users', 'User')
    Organization = apps.get_model('organizations', 'Organization')
    apofiz_org = Organization.objects.get(title='Apofiz.com')
    for user in User.objects.all():
        subscription, created = Subscription.objects.get_or_create(user=user, organization=apofiz_org)



class Migration(migrations.Migration):
    dependencies = [
        ('organizations', '0079_auto_20220216_0855'),
    ]

    operations = [
        # migrations.RunPython(add_data_in_subscriptions),
    ]
