# Generated by Django 3.1.7 on 2022-03-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_auto_20211206_1122'),
        ('organizations', '0080_service_category_of_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category_of_item',
            field=models.ManyToManyField(blank=True, null=True, related_name='services', to='shop.ItemCategory'),
        ),
    ]
