# Generated by Django 3.1.7 on 2022-02-16 07:10

from django.db import migrations, models


def create_partnership(apps, schema_editor):
    Organization = apps.get_model('organizations', 'Organization')
    Partnership = apps.get_model('organizations', 'Partnership')

    orgs = Organization.objects.filter(address='Nakheel Mall 10/2, Palm Jumeirah Road, The Palm Jumeirah, Dubai')
    nakhell_mall = Organization.objects.get(title='Nakheel Mall')
    for org in orgs:
        Partnership.objects.create(requested_by=nakhell_mall, accepted_by=org, is_accepted=True)
        Partnership.objects.create(requested_by=org, accepted_by=nakhell_mall, is_accepted=True)




class Migration(migrations.Migration):
    dependencies = [
        ('organizations', '0081_auto_20220319_1020'),
    ]

    operations = [
        migrations.RunPython(create_partnership),
    ]
