# Generated by Django 3.1.7 on 2022-02-16 07:10

from django.db import migrations, models


def create_partnership(apps, schema_editor):
    Organization = apps.get_model('organizations', 'Organization')
    Partnership = apps.get_model('organizations', 'Partnership')

    orgs = Organization.objects.filter(address='Dubai Marina Mall 70, Al Marsa Street, Marsa Dubai, Dubai')
    try:
        marina_mall = Organization.objects.get(title='Marina Mall')
        for org in orgs:
            if org != marina_mall:
                Partnership.objects.get_or_create(requested_by=marina_mall, accepted_by=org, is_accepted=True)
                Partnership.objects.get_or_create(requested_by=org, accepted_by=marina_mall, is_accepted=True)
    except Organization.DoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ('organizations', '0082_create_partnerships_for_Marina_Mall'),
    ]

    operations = [
        migrations.RunPython(create_partnership),
    ]
