# Generated by Django 3.1.7 on 2022-02-16 07:10

from django.db import migrations, models


def delete_unnamed_subscribers(apps, schema_editor):
    Subscription = apps.get_model('organizations', 'Subscription')
    try:
        Subscription.objects.filter(user__full_name=None).delete()
    except Subscription.DoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ('organizations', '0082_create_partnerships_for_Marina_Mall'),
    ]

    operations = [
        migrations.RunPython(delete_unnamed_subscribers),
    ]
