# Generated by Django 3.1.7 on 2022-03-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0082_create_partnerships_for_Marina_Mall'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
