# Generated by Django 3.1.7 on 2022-03-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0083_organization_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('subscribed', 'subscribed'), ('not_subscribed', 'not_subscribed'), ('pending', 'pending')], default='subscribed', max_length=20),
        ),
    ]
