# Generated by Django 3.1.7 on 2022-03-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_auto_20220323_0804'),
        ('organizations', '0084_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category_of_item',
            field=models.ManyToManyField(blank=True, related_name='services', to='shop.ItemCategory'),
        ),
    ]
