# Generated by Django 3.1.7 on 2022-05-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0085_auto_20220330_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='switcher',
            field=models.CharField(choices=[('cards', 'cards'), ('web', 'web')], default='web', max_length=20),
        ),
    ]
