# Generated by Django 3.1.7 on 2022-02-16 07:10

from django.db import migrations, models
from django.db.models.query_utils import Q


def add_verified(apps, schema_editor):
    Organization = apps.get_model('organizations', 'Organization')
    Organization.objects.filter(shop_items__subcategory__category__is_adult=True).exclude(
        Q(is_banned=True) | Q(is_deleted=True)).update(verification_status='verified')
    Organization.objects.filter(
        memberships__user__id__in=(2442, 2443, 2447, 2446, 2445, 2444, 1541)).exclude(
        Q(is_banned=True) | Q(is_deleted=True)).update(verification_status='verified')


class Migration(migrations.Migration):
    dependencies = [
        ('organizations', '0085_auto_20220330_0944'),
    ]

    operations = [
        migrations.RunPython(add_verified),
    ]
