# Generated by Django 3.1.7 on 2022-06-03 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0086_organization_switcher'),
        ('organizations', '0086_Update_verification_status_for_adult_organization'),
    ]

    operations = [
    ]
