# Generated by Django 3.1.7 on 2022-08-18 11:25

from django.db import migrations


def add_employees(apps, _):
    print('applying')

def reverse_func(apps, schema_editor):
    print('REVERSED')

class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0087_merge_20220603_1003'),
    ]

    operations = [
        migrations.RunPython(add_employees, reverse_func),
    ]
