# Generated by Django 3.1.7 on 2022-07-02 07:10

from django.db import migrations, models


def create_partnership(apps, schema_editor):
    Organization = apps.get_model('organizations', 'Organization')
    Partnership = apps.get_model('organizations', 'Partnership')

    orgs = Organization.objects.filter(address='Golden Mile Galleria Mall 200/1, Palm Jumeirah')
    try:
        golden_mile = Organization.objects.get(title='Golden Mile')
        for org in orgs:
            if org != golden_mile:
                Partnership.objects.create(requested_by=golden_mile, accepted_by=org, is_accepted=True)
                Partnership.objects.create(requested_by=org, accepted_by=golden_mile, is_accepted=True)
    except Organization.DoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ('organizations', '0087_merge_20220603_1003'),
    ]

    operations = [
        migrations.RunPython(create_partnership),
    ]
