# Generated by Django 3.1.7 on 2022-08-18 11:25

from django.db import migrations


def add_employees(apps, _):
    Organization = apps.get_model('organizations', 'Organization')
    Role = apps.get_model('organizations', 'Role')
    Membership = apps.get_model('organizations', 'Membership')
    kover_employees_ids = [26, 32, 962, 2442, 2445, 2444, 1541, 2453, 2447, 2443, 2455, 3128, 3129, 2457, 3054]
    service_org_ids = [{'org_id': 1673, 'role_id': 447}, {'org_id': 1677, 'role_id': 448}, {'org_id': 127, 'role_id': 341},
                       {'org_id': 128, 'role_id': 368}, {'org_id': 130, 'role_id': 321}, {'org_id': 131, 'role_id': 467},
                       {'org_id': 135, 'role_id': 253}, {'org_id': 142, 'role_id': 234}, {'org_id': 143, 'role_id': 468},
                       {'org_id': 146, 'role_id': 147}, {'org_id': 154, 'role_id': 464}, {'org_id': 155, 'role_id': 470},
                       {'org_id': 163, 'role_id': 446}, {'org_id': 164, 'role_id': 450}, {'org_id': 166, 'role_id': 369},
                       {'org_id': 192, 'role_id': 370}, {'org_id': 195, 'role_id': 322}, {'org_id': 196, 'role_id': 457},
                       {'org_id': 206, 'role_id': 323}, {'org_id': 208, 'role_id': 471}, {'org_id': 210, 'role_id': 449},
                       {'org_id': 212, 'role_id': 324}, {'org_id': 221, 'role_id': 371}, {'org_id': 222, 'role_id': 344},
                       {'org_id': 262, 'role_id': 389}, {'org_id': 263, 'role_id': 390}, {'org_id': 265, 'role_id': 345},
                       {'org_id': 269, 'role_id': 473}, {'org_id': 274, 'role_id': 372}, {'org_id': 291, 'role_id': 325},
                       {'org_id': 298, 'role_id': 245}, {'org_id': 299, 'role_id': 391}, {'org_id': 303, 'role_id': 326},
                       {'org_id': 309, 'role_id': 392}, {'org_id': 314, 'role_id': 507}, {'org_id': 326, 'role_id': 393},
                       {'org_id': 330, 'role_id': 347}, {'org_id': 337, 'role_id': 445}, {'org_id': 338, 'role_id': 327},
                       {'org_id': 343, 'role_id': 444}, {'org_id': 364, 'role_id': 394}, {'org_id': 366, 'role_id': 373},
                       {'org_id': 381, 'role_id': 328}, {'org_id': 387, 'role_id': 329}, {'org_id': 395, 'role_id': 395},
                       {'org_id': 396, 'role_id': 312}, {'org_id': 416, 'role_id': 374}, {'org_id': 425, 'role_id': 375},
                       {'org_id': 426, 'role_id': 453}, {'org_id': 427, 'role_id': 396}, {'org_id': 431, 'role_id': 454},
                       {'org_id': 441, 'role_id': 443}, {'org_id': 447, 'role_id': 348}, {'org_id': 451, 'role_id': 330},
                       {'org_id': 467, 'role_id': 458}, {'org_id': 469, 'role_id': 349}, {'org_id': 475, 'role_id': 350},
                       {'org_id': 483, 'role_id': 397}, {'org_id': 493, 'role_id': 351}, {'org_id': 497, 'role_id': 331},
                       {'org_id': 503, 'role_id': 352}, {'org_id': 506, 'role_id': 376}, {'org_id': 532, 'role_id': 377},
                       {'org_id': 534, 'role_id': 353}, {'org_id': 554, 'role_id': 398}, {'org_id': 575, 'role_id': 378},
                       {'org_id': 645, 'role_id': 440}, {'org_id': 774, 'role_id': 399}, {'org_id': 778, 'role_id': 400},
                       {'org_id': 779, 'role_id': 332}, {'org_id': 1430, 'role_id': 403}, {'org_id': 1435, 'role_id': 333},
                       {'org_id': 1437, 'role_id': 379}, {'org_id': 1572, 'role_id': 334}, {'org_id': 1574, 'role_id': 335},
                       {'org_id': 1575, 'role_id': 336}, {'org_id': 1576, 'role_id': 337}, {'org_id': 1577, 'role_id': 338},
                       {'org_id': 1584, 'role_id': 339}, {'org_id': 1590, 'role_id': 355}, {'org_id': 1591, 'role_id': 356},
                       {'org_id': 1592, 'role_id': 357}, {'org_id': 1593, 'role_id': 358}, {'org_id': 1594, 'role_id': 359},
                       {'org_id': 1595, 'role_id': 360}, {'org_id': 1596, 'role_id': 361}, {'org_id': 1597, 'role_id': 362},
                       {'org_id': 1599, 'role_id': 363}, {'org_id': 1601, 'role_id': 364}, {'org_id': 1603, 'role_id': 365},
                       {'org_id': 1609, 'role_id': 380}, {'org_id': 1610, 'role_id': 381}, {'org_id': 1611, 'role_id': 382},
                       {'org_id': 1612, 'role_id': 383}, {'org_id': 1613, 'role_id': 384}, {'org_id': 1614, 'role_id': 404},
                       {'org_id': 1616, 'role_id': 405}, {'org_id': 1618, 'role_id': 406}, {'org_id': 1621, 'role_id': 407},
                       {'org_id': 1622, 'role_id': 408}, {'org_id': 1624, 'role_id': 409}, {'org_id': 1629, 'role_id': 410},
                       {'org_id': 1630, 'role_id': 411}, {'org_id': 1631, 'role_id': 412}, {'org_id': 1636, 'role_id': 413},
                       {'org_id': 1643, 'role_id': 414}, {'org_id': 1644, 'role_id': 415}, {'org_id': 1645, 'role_id': 416},
                       {'org_id': 1648, 'role_id': 417}, {'org_id': 1651, 'role_id': 418}, {'org_id': 1653, 'role_id': 419},
                       {'org_id': 1654, 'role_id': 420}, {'org_id': 1655, 'role_id': 421}, {'org_id': 1656, 'role_id': 422},
                       {'org_id': 1657, 'role_id': 439}, {'org_id': 1658, 'role_id': 423}, {'org_id': 1660, 'role_id': 424},
                       {'org_id': 1661, 'role_id': 425}, {'org_id': 1662, 'role_id': 472}, {'org_id': 1665, 'role_id': 426},
                       {'org_id': 1666, 'role_id': 438}, {'org_id': 1667, 'role_id': 427}, {'org_id': 1670, 'role_id': 434},
                       {'org_id': 1671, 'role_id': 455}, {'org_id': 1672, 'role_id': 437}, {'org_id': 1675, 'role_id': 459},
                       {'org_id': 1676, 'role_id': 460}, {'org_id': 1678, 'role_id': 436}, {'org_id': 1680, 'role_id': 463},
                       {'org_id': 1681, 'role_id': 428}, {'org_id': 1682, 'role_id': 429}, {'org_id': 1683, 'role_id': 465},
                       {'org_id': 1684, 'role_id': 466}, {'org_id': 1688, 'role_id': 430}, {'org_id': 1690, 'role_id': 431},
                       {'org_id': 1701, 'role_id': 456}, {'org_id': 1703, 'role_id': 461}, {'org_id': 1706, 'role_id': 462},
                       {'org_id': 1710, 'role_id': 469}, {'org_id': 1712, 'role_id': 474}, {'org_id': 1714, 'role_id': 475},
                       {'org_id': 1716, 'role_id': 479}, {'org_id': 1659, 'role_id': 433}, {'org_id': 1687, 'role_id': 435},
                       {'org_id': 1114, 'role_id': 148}]
    for org in service_org_ids:
        organization = Organization.objects.get(id=org['org_id'])
        role = Role.objects.get(id=org['role_id'])
        for empl in kover_employees_ids:
            employee, created = Membership.objects.get_or_create(user_id=empl,
                                                                 organization=organization,
                                                                 added_by_id=26,
                                                                 role=role
                                                                 )
            employee.save()


def reverse_func(apps, schema_editor):
    Organization = apps.get_model('organizations', 'Organization')
    Role = apps.get_model('organizations', 'Role')
    Membership = apps.get_model('organizations', 'Membership')
    kover_employees_ids = [26, 32, 962, 2442, 2445, 2444, 1541, 2453, 2447, 2443, 2455, 3128, 3129, 2457, 3054]
    service_org_ids = [{'org_id': 1673, 'role_id': 447}, {'org_id': 1677, 'role_id': 448},
                       {'org_id': 127, 'role_id': 341},
                       {'org_id': 128, 'role_id': 368}, {'org_id': 130, 'role_id': 321},
                       {'org_id': 131, 'role_id': 467},
                       {'org_id': 135, 'role_id': 253}, {'org_id': 142, 'role_id': 234},
                       {'org_id': 143, 'role_id': 468},
                       {'org_id': 146, 'role_id': 147}, {'org_id': 154, 'role_id': 464},
                       {'org_id': 155, 'role_id': 470},
                       {'org_id': 163, 'role_id': 446}, {'org_id': 164, 'role_id': 450},
                       {'org_id': 166, 'role_id': 369},
                       {'org_id': 192, 'role_id': 370}, {'org_id': 195, 'role_id': 322},
                       {'org_id': 196, 'role_id': 457},
                       {'org_id': 206, 'role_id': 323}, {'org_id': 208, 'role_id': 471},
                       {'org_id': 210, 'role_id': 449},
                       {'org_id': 212, 'role_id': 324}, {'org_id': 221, 'role_id': 371},
                       {'org_id': 222, 'role_id': 344},
                       {'org_id': 262, 'role_id': 389}, {'org_id': 263, 'role_id': 390},
                       {'org_id': 265, 'role_id': 345},
                       {'org_id': 269, 'role_id': 473}, {'org_id': 274, 'role_id': 372},
                       {'org_id': 291, 'role_id': 325},
                       {'org_id': 298, 'role_id': 245}, {'org_id': 299, 'role_id': 391},
                       {'org_id': 303, 'role_id': 326},
                       {'org_id': 309, 'role_id': 392}, {'org_id': 314, 'role_id': 507},
                       {'org_id': 326, 'role_id': 393},
                       {'org_id': 330, 'role_id': 347}, {'org_id': 337, 'role_id': 445},
                       {'org_id': 338, 'role_id': 327},
                       {'org_id': 343, 'role_id': 444}, {'org_id': 364, 'role_id': 394},
                       {'org_id': 366, 'role_id': 373},
                       {'org_id': 381, 'role_id': 328}, {'org_id': 387, 'role_id': 329},
                       {'org_id': 395, 'role_id': 395},
                       {'org_id': 396, 'role_id': 312}, {'org_id': 416, 'role_id': 374},
                       {'org_id': 425, 'role_id': 375},
                       {'org_id': 426, 'role_id': 453}, {'org_id': 427, 'role_id': 396},
                       {'org_id': 431, 'role_id': 454},
                       {'org_id': 441, 'role_id': 443}, {'org_id': 447, 'role_id': 348},
                       {'org_id': 451, 'role_id': 330},
                       {'org_id': 467, 'role_id': 458}, {'org_id': 469, 'role_id': 349},
                       {'org_id': 475, 'role_id': 350},
                       {'org_id': 483, 'role_id': 397}, {'org_id': 493, 'role_id': 351},
                       {'org_id': 497, 'role_id': 331},
                       {'org_id': 503, 'role_id': 352}, {'org_id': 506, 'role_id': 376},
                       {'org_id': 532, 'role_id': 377},
                       {'org_id': 534, 'role_id': 353}, {'org_id': 554, 'role_id': 398},
                       {'org_id': 575, 'role_id': 378},
                       {'org_id': 645, 'role_id': 440}, {'org_id': 774, 'role_id': 399},
                       {'org_id': 778, 'role_id': 400},
                       {'org_id': 779, 'role_id': 332}, {'org_id': 1430, 'role_id': 403},
                       {'org_id': 1435, 'role_id': 333},
                       {'org_id': 1437, 'role_id': 379}, {'org_id': 1572, 'role_id': 334},
                       {'org_id': 1574, 'role_id': 335},
                       {'org_id': 1575, 'role_id': 336}, {'org_id': 1576, 'role_id': 337},
                       {'org_id': 1577, 'role_id': 338},
                       {'org_id': 1584, 'role_id': 339}, {'org_id': 1590, 'role_id': 355},
                       {'org_id': 1591, 'role_id': 356},
                       {'org_id': 1592, 'role_id': 357}, {'org_id': 1593, 'role_id': 358},
                       {'org_id': 1594, 'role_id': 359},
                       {'org_id': 1595, 'role_id': 360}, {'org_id': 1596, 'role_id': 361},
                       {'org_id': 1597, 'role_id': 362},
                       {'org_id': 1599, 'role_id': 363}, {'org_id': 1601, 'role_id': 364},
                       {'org_id': 1603, 'role_id': 365},
                       {'org_id': 1609, 'role_id': 380}, {'org_id': 1610, 'role_id': 381},
                       {'org_id': 1611, 'role_id': 382},
                       {'org_id': 1612, 'role_id': 383}, {'org_id': 1613, 'role_id': 384},
                       {'org_id': 1614, 'role_id': 404},
                       {'org_id': 1616, 'role_id': 405}, {'org_id': 1618, 'role_id': 406},
                       {'org_id': 1621, 'role_id': 407},
                       {'org_id': 1622, 'role_id': 408}, {'org_id': 1624, 'role_id': 409},
                       {'org_id': 1629, 'role_id': 410},
                       {'org_id': 1630, 'role_id': 411}, {'org_id': 1631, 'role_id': 412},
                       {'org_id': 1636, 'role_id': 413},
                       {'org_id': 1643, 'role_id': 414}, {'org_id': 1644, 'role_id': 415},
                       {'org_id': 1645, 'role_id': 416},
                       {'org_id': 1648, 'role_id': 417}, {'org_id': 1651, 'role_id': 418},
                       {'org_id': 1653, 'role_id': 419},
                       {'org_id': 1654, 'role_id': 420}, {'org_id': 1655, 'role_id': 421},
                       {'org_id': 1656, 'role_id': 422},
                       {'org_id': 1657, 'role_id': 439}, {'org_id': 1658, 'role_id': 423},
                       {'org_id': 1660, 'role_id': 424},
                       {'org_id': 1661, 'role_id': 425}, {'org_id': 1662, 'role_id': 472},
                       {'org_id': 1665, 'role_id': 426},
                       {'org_id': 1666, 'role_id': 438}, {'org_id': 1667, 'role_id': 427},
                       {'org_id': 1670, 'role_id': 434},
                       {'org_id': 1671, 'role_id': 455}, {'org_id': 1672, 'role_id': 437},
                       {'org_id': 1675, 'role_id': 459},
                       {'org_id': 1676, 'role_id': 460}, {'org_id': 1678, 'role_id': 436},
                       {'org_id': 1680, 'role_id': 463},
                       {'org_id': 1681, 'role_id': 428}, {'org_id': 1682, 'role_id': 429},
                       {'org_id': 1683, 'role_id': 465},
                       {'org_id': 1684, 'role_id': 466}, {'org_id': 1688, 'role_id': 430},
                       {'org_id': 1690, 'role_id': 431},
                       {'org_id': 1701, 'role_id': 456}, {'org_id': 1703, 'role_id': 461},
                       {'org_id': 1706, 'role_id': 462},
                       {'org_id': 1710, 'role_id': 469}, {'org_id': 1712, 'role_id': 474},
                       {'org_id': 1714, 'role_id': 475},
                       {'org_id': 1716, 'role_id': 479}, {'org_id': 1659, 'role_id': 433},
                       {'org_id': 1687, 'role_id': 435},
                       {'org_id': 1114, 'role_id': 148}]

    for org in service_org_ids:
        organization = Organization.objects.get(id=org['org_id'])
        role = Role.objects.get(id=org['role_id'])
        for empl in kover_employees_ids:
            if Membership.objects.filter(user_id=empl, organization=organization, role=role).exists():
                Membership.objects.get(user_id=empl, organization=organization, role=role).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0087_merge_20220603_1003'),
    ]

    operations = [
        migrations.RunPython(add_employees, reverse_func),
    ]
