# Generated by Django 3.1.7 on 2022-11-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0088_auto_20221027_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_entertainment',
            field=models.BooleanField(default=False),
        ),
    ]
