# Generated by Django 3.1.7 on 2022-12-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0089_service_is_entertainment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='subcategory',
            field=models.ManyToManyField(blank=True, related_name='services', to='organizations.OrganizationType'),
        ),
    ]
