# Generated by Django 3.1.7 on 2022-12-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0090_auto_20221201_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_blacklist',
            field=models.BooleanField(default=False),
        ),
    ]
