# Generated by Django 3.1.7 on 2022-12-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0091_organization_is_blacklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='is_blacklist',
        ),
    ]
