# Generated by Django 3.1.7 on 2023-03-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0094_blockeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='has_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='has_self_pick_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
