# Generated by Django 3.1.7 on 2023-03-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0095_auto_20230329_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='has_license',
            field=models.BooleanField(default=False, help_text='Does organization have license?'),
        ),
        migrations.AddField(
            model_name='service',
            name='has_license',
            field=models.BooleanField(default=False),
        ),
    ]
