# Generated by Django 3.1.7 on 2023-07-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0097_auto_20230725_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='payment_system',
            field=models.ManyToManyField(blank=True, related_name='organization_payment', to='organizations.PaymentSystem'),
        ),
    ]
