# Generated by Django 3.1.7 on 2023-07-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0098_auto_20230725_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='payment_system',
        ),
        migrations.AddField(
            model_name='organization',
            name='cryptobox_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='cryptobox_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='embily_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='embily_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='freedompay_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='freedompay_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='payment_systems_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PaymentSystem',
        ),
    ]
