# Generated by Django 3.1.7 on 2023-07-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0099_auto_20230725_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='cryptobox_enabled',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='embily_enabled',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='freedompay_enabled',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='payment_systems_enabled',
        ),
        migrations.AddField(
            model_name='organization',
            name='cryptobox_activated',
            field=models.BooleanField(default=False, help_text='Activated in this organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='embily_activated',
            field=models.BooleanField(default=False, help_text='Activated in this organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='freedompay_activated',
            field=models.BooleanField(default=False, help_text='Activated in this organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='payment_systems_activated',
            field=models.BooleanField(default=False, help_text='All payment systems are activated'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='cryptobox_confirmed',
            field=models.BooleanField(default=False, help_text='Available in this organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='embily_confirmed',
            field=models.BooleanField(default=False, help_text='Available in this organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='freedompay_confirmed',
            field=models.BooleanField(default=False, help_text='Available in this organization'),
        ),
    ]
