# Generated by Django 3.1.7 on 2023-07-27 10:01

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0100_auto_20230726_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPaymentSystemUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=255, verbose_name='User name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=255, region=None, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_system_users_data', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Users data for payment settings of organization',
                'verbose_name_plural': 'Users data for payment settings of organization',
            },
        ),
    ]
