# Generated by Django 3.1.7 on 2023-08-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0101_organizationpaymentsystemusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='payment_with_confirmation',
            field=models.BooleanField(default=True, help_text='Payments with confirmation'),
        ),
    ]
