# Generated by Django 3.1.7 on 2023-09-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0102_organization_payment_with_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='show_followers',
            field=models.BooleanField(default=True),
        ),
    ]
