# Generated by Django 3.1.7 on 2023-09-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0103_organization_show_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_wholesale',
            field=models.BooleanField(default=False),
        ),
    ]
