# Generated by Django 3.1.7 on 2023-09-29 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0104_organization_is_wholesale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='embily_activated',
            new_name='paysy_activated',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='embily_confirmed',
            new_name='paysy_confirmed',
        ),
    ]
