# Generated by Django 3.1.7 on 2023-10-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0105_auto_20230929_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='can_update_is_wholesale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_wholesale_request_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
