# Generated by Django 3.1.7 on 2023-10-10 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0106_auto_20231004_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='cryptobox_activated',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='cryptobox_confirmed',
        ),
    ]
