# Generated by Django 3.1.7 on 2023-11-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0107_auto_20231010_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_map',
            field=models.BooleanField(default=False),
        ),
    ]
