# Generated by Django 3.1.7 on 2024-01-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0109_service_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationcategory',
            name='name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizationcategory',
            name='name_zh',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='title_zh',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Название сервиса'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_zh',
            field=models.CharField(max_length=255, null=True, verbose_name='Название сервиса'),
        ),
    ]
