# Generated by Django 3.1.7 on 2024-01-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0110_auto_20240118_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='libersave_activated',
            field=models.BooleanField(default=False, help_text='Activated in this organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='libersave_confirmed',
            field=models.BooleanField(default=False, help_text='Available in this organization'),
        ),
    ]
