# Generated by Django 3.1.7 on 2024-01-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0111_auto_20240124_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='betapay_activated',
            field=models.BooleanField(default=False, help_text='Activated in this organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='betapay_confirmed',
            field=models.BooleanField(default=False, help_text='Available in this organization'),
        ),
    ]
