# Generated by Django 3.1.7 on 2024-02-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0112_auto_20240130_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationtype',
            name='is_resume',
            field=models.BooleanField(default=False),
        ),
    ]
