# Generated by Django 3.1.7 on 2024-02-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0113_organizationtype_is_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_edit_own_resume',
            field=models.BooleanField(default=False),
        ),
    ]
