# Generated by Django 3.1.7 on 2024-02-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0114_role_can_edit_own_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_resume',
            field=models.BooleanField(default=False),
        ),
    ]
