# Generated by Django 3.1.7 on 2024-04-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0115_service_is_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_wholesale',
            field=models.BooleanField(default=False),
        ),
    ]
