# Generated by Django 3.1.7 on 2024-05-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0116_service_is_wholesale'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cryptocloud_activated',
            field=models.BooleanField(default=False, help_text='Activated in this organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='cryptocloud_confirmed',
            field=models.BooleanField(default=False, help_text='Available in this organization'),
        ),
    ]
