# Generated by Django 3.1.7 on 2024-05-30 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0054_auto_20240118_0509'),
        ('organizations', '0117_auto_20240521_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20)),
                ('position', models.CharField(max_length=255)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistants', to='common.file')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant', to='organizations.organization')),
            ],
        ),
    ]
