# Generated by Django 3.1.7 on 2024-05-31 09:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0054_auto_20240118_0509'),
        ('organizations', '0118_assistant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=5000)),
                ('ordering', models.SmallIntegerField(blank=True, help_text='Не заполнять при создании!', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Service ordering')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ('ordering',),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=5000)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='organizations.assistant')),
                ('files', models.ManyToManyField(blank=True, related_name='answers', to='common.File')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='organizations.question')),
            ],
        ),
    ]
