# Generated by Django 3.1.7 on 2024-05-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0119_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
