# Generated by Django 3.1.7 on 2024-05-31 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0120_auto_20240531_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ordering',
            field=models.SmallIntegerField(blank=True, help_text='Не заполнять при создании!', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Question ordering'),
        ),
    ]
