# Generated by Django 3.1.7 on 2024-06-03 12:05

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0122_auto_20240531_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('file', models.FileField(blank=True, help_text='File that you want to store', null=True, upload_to=common.utils.upload_file_with_unique_name)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AlterField(
            model_name='answer',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='answers', to='organizations.AnswerFile'),
        ),
    ]
