# Generated by Django 3.1.7 on 2024-06-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0124_auto_20240611_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistant',
            name='plan',
        ),
        migrations.AddField(
            model_name='assistant',
            name='plans',
            field=models.ManyToManyField(blank=True, related_name='assistants', to='organizations.Plan'),
        ),
    ]
