# Generated by Django 3.1.7 on 2024-06-11 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0054_auto_20240118_0509'),
        ('organizations', '0125_auto_20240611_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='common.currency'),
        ),
    ]
