# Generated by Django 3.1.7 on 2024-06-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0126_plan_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='additional_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_best_choice',
            field=models.BooleanField(default=False),
        ),
    ]
