# Generated by Django 3.1.7 on 2024-06-12 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0043_auto_20240612_1245'),
        ('organizations', '0127_auto_20240611_0630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistant',
            name='plans',
        ),
        migrations.CreateModel(
            name='UserAssistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('active_until', models.DateTimeField(blank=True, null=True)),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_assistants', to='organizations.assistant')),
                ('plans', models.ManyToManyField(blank=True, related_name='user_assistants', to='organizations.Plan')),
                ('transaction', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_assistants', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assistants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
