# Generated by Django 3.1.7 on 2024-06-24 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0129_auto_20240620_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='organization_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_user_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('user', 'user'), ('assistant', 'assistant'), ('org_user', 'org_user')], default='user', max_length=25),
        ),
    ]
