# Generated by Django 3.1.7 on 2024-06-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0130_auto_20240624_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='initiated_by_org_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
