# Generated by Django 3.1.7 on 2024-06-24 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0131_auto_20240624_0821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='is_enabled',
            new_name='assistant_enabled',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='initiated_by_org_user',
            new_name='chat_by_org_user',
        ),
    ]
