# Generated by Django 3.1.7 on 2024-06-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0133_chatmessage_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='assistant_enabled',
        ),
        migrations.AddField(
            model_name='assistant',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
