# Generated by Django 3.1.7 on 2025-05-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0134_auto_20240626_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='subscription_status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('cancelled', 'cancelled'), ('test', 'test')], default='test', max_length=255, null=True),
        ),
    ]
