# Generated by Django 3.1.7 on 2025-05-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0135_organization_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'active'), ('cancelled', 'cancelled'), ('test', 'test')], default='test', max_length=255),
        ),
    ]
