# Generated by Django 3.1.7 on 2025-05-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0136_auto_20250520_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'active'), ('cancelled', 'cancelled'), ('test', 'test')], default='active', max_length=255),
        ),
    ]
