# Generated by Django 3.1.7 on 2025-05-20 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0137_auto_20250520_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='subscription_status',
        ),
    ]
