# Generated by Django 3.1.7 on 2025-05-20 09:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0054_auto_20240118_0509'),
        ('organizations', '0140_paymentsystemmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalTariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_type', models.CharField(choices=[('starter', 'Стартовый'), ('standard', 'Стандартный'), ('profitable', 'Выгодный')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='common.country')),
            ],
            options={
                'verbose_name': 'Regional Tariff',
                'verbose_name_plural': 'Regional Tariffs',
                'unique_together': {('country', 'tariff_type')},
            },
        ),
    ]
