# Generated by Django 3.1.7 on 2025-05-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0141_regionaltariff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regionaltariff',
            old_name='price',
            new_name='original_price',
        ),
        migrations.AddField(
            model_name='regionaltariff',
            name='duration_months',
            field=models.PositiveIntegerField(blank=True, help_text='Срок действия тарифа в месяцах', null=True),
        ),
    ]
