# Generated by Django 3.1.7 on 2025-05-20 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0055_country_is_paid_subscription'),
        ('organizations', '0142_auto_20250520_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionaltariff',
            name='country',
            field=models.ForeignKey(limit_choices_to={'is_paid_subscription': True}, on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='common.country', verbose_name='Страна'),
        ),
    ]
