# Generated by Django 3.1.7 on 2025-05-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0143_auto_20250520_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsystemmethod',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
