# Generated by Django 3.1.7 on 2025-05-20 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0044_auto_20240612_1328'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0144_paymentsystemmethod_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrgSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('active_until', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_subscription', to='organizations.organization')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_subscription', to='organizations.regionaltariff')),
                ('transaction', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_subscription', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_org_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
