# Generated by Django 3.1.7 on 2025-05-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0145_userorgsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsystemmethod',
            name='code',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
