# Generated by Django 3.1.7 on 2025-05-23 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0055_country_is_paid_subscription'),
        ('organizations', '0146_paymentsystemmethod_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_default', models.BooleanField(default=False, help_text='Системный баннер, удаляется только из админки')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_banners', to='common.file')),
            ],
            options={
                'verbose_name': 'Баннер организации',
                'verbose_name_plural': 'Баннеры организаций',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='banners',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='organizations.OrganizationBanner'),
        ),
    ]
