# Generated by Django 3.1.7 on 2025-05-26 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0147_auto_20250523_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='selected_banner',
            field=models.ForeignKey(blank=True, help_text="The banner shown on the organization's detail page", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_organizations', to='organizations.organizationbanner'),
        ),
    ]
