# Generated by Django 3.1.7 on 2025-06-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0148_organization_selected_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_application',
            field=models.BooleanField(default=False),
        ),
    ]
