# Generated by Django 3.1.7 on 2025-06-09 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0055_country_is_paid_subscription'),
        ('organizations', '0149_service_is_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_banner', to='common.file'),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание сервиса'),
        ),
    ]
