# Generated by Django 3.1.7 on 2025-06-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0150_auto_20250609_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Описание сервиса'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание сервиса'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание сервиса'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Описание сервиса'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_zh',
            field=models.TextField(blank=True, null=True, verbose_name='Описание сервиса'),
        ),
    ]
