# Generated by Django 3.1.7 on 2025-09-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0152_auto_20250923_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_without_discount',
            field=models.BooleanField(default=False),
        ),
    ]
