# Generated by Django 3.1.7 on 2025-10-01 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0153_service_is_without_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='is_without_discount',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='OrganizationInvoiceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=600)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_info', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default='', max_length=60)),
                ('invoice_number', models.CharField(blank=True, max_length=455, null=True)),
                ('invoice_pdf', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('receipt_pdf', models.FileField(blank=True, null=True, upload_to='bills/')),
                ('invoice_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invoice_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(default='Bank', max_length=255)),
                ('organization_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='organizations.organizationinvoiceinfo')),
                ('subscription', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='organizations.userorgsubscription')),
                ('tariff', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='organizations.regionaltariff')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
