# Generated by Django 3.1.7 on 2025-10-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0154_auto_20251001_1124'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_deleted'], name='organizatio_is_dele_d44ef0_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active'], name='organizatio_is_acti_1ffc28_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_banned'], name='organizatio_is_bann_c5d067_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['city'], name='organizatio_city_id_ecf3b9_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['country'], name='organizatio_country_4286a6_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_deleted', 'is_active', 'is_banned'], name='organizatio_is_dele_ae9a25_idx'),
        ),
    ]
