# Generated by Django 3.1.7 on 2025-10-31 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0156_pinnedorganizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationinvoiceinfo',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_info', to='organizations.organization'),
        ),
    ]
