# Generated by Django 3.1.7 on 2025-11-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0157_auto_20251031_1139'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='organizationblacklist',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='unique_user_organization_blacklist'),
        ),
    ]
