# Generated by Django 3.1.7 on 2025-11-27 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0158_auto_20251119_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='discount',
        ),
    ]
