# Generated by Django 3.1.7 on 2025-11-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0159_remove_coupon_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='image',
            field=models.URLField(),
        ),
    ]
