# Generated by Django 3.1.7 on 2025-12-08 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0047_auto_20250603_1201'),
        ('organizations', '0161_coupon_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponusage',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usage', to='transactions.transaction'),
        ),
    ]
