# Generated by Django 3.1.7 on 2025-12-14 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0162_couponusage_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='maaly_pay_activated',
            field=models.BooleanField(default=False, help_text='Activated in this organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='maaly_pay_confirmed',
            field=models.BooleanField(default=False, help_text='Available in this organization'),
        ),
        migrations.CreateModel(
            name='MaalyPayOrganizationPaymentSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.CharField(max_length=420)),
                ('merchant_id', models.CharField(max_length=420)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maaly_pay_info', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
