# Generated by Django 3.1.7 on 2025-12-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0164_couponbanners'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
    ]
