# Generated by Django 3.1.7 on 2025-12-26 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0062_remove_file_file_type'),
        ('organizations', '0165_auto_20251215_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalPaymentSystemSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_system_id', models.PositiveSmallIntegerField(choices=[(1, 'FreedomPay'), (2, 'PaySy'), (3, 'Libersave'), (4, 'Betapay'), (5, 'CryptoCloud'), (6, 'MaalyPay')], help_text='ID платежной системы (совместим с существующим кодом)')),
                ('is_enabled_in_region', models.BooleanField(default=True, help_text='Платежка доступна в этом регионе')),
                ('is_available_for_request', models.BooleanField(default=True, help_text='Организации могут запрашивать подключение')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_payment_settings', to='common.country')),
            ],
            options={
                'verbose_name': 'Regional Payment System Setting',
                'verbose_name_plural': 'Regional Payment System Settings',
                'unique_together': {('country', 'payment_system_id')},
            },
        ),
    ]
