# Generated by Django 3.1.7 on 2025-12-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0166_regionalpaymentsystemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionalpaymentsystemsettings',
            name='allowed_organizations',
            field=models.ManyToManyField(blank=True, help_text='Организации-исключения: для них платежка доступна даже если отключена в регионе', related_name='payment_system_overrides', to='organizations.Organization'),
        ),
    ]
