# Generated by Django 3.1.7 on 2025-12-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0167_regionalpaymentsystemsettings_allowed_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='maalypayorganizationpaymentsystem',
            name='bank_info',
            field=models.CharField(
                blank=True,
                help_text='Bank account information (IBAN, account number, etc.)',
                max_length=500,
                null=True,
            ),
        ),
    ]
