# Generated by Django 3.2.13 on 2026-01-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0170_migrate_country_to_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalpaymentsystemsettings',
            name='is_enabled_in_region',
            field=models.BooleanField(default=True, help_text='Платежка доступна в указанных странах'),
        ),
    ]
