# Generated by Django 3.1.7 on 2026-01-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0175_chat_source_telegram_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_catalog',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
