# Generated by Django 3.1.7 on 2026-01-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0050_auto_20251208_1530'),
        ('organizations', '0176_auto_20260121_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='transaction',
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='invoices',
                to='transactions.transaction',
            ),
        ),
    ]
