# Generated by Django 3.1.7 on 2026-01-23 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0177_auto_20260122_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ('position_number',), 'verbose_name': 'Ai Plans Info', 'verbose_name_plural': 'Ai Plans Info'},
        ),
        migrations.AddField(
            model_name='plan',
            name='position_number',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Номер позиции в тарифах', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
