# Generated by Django 3.1.7 on 2026-01-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0178_auto_20260123_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='is_catalog',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
