# Generated by Django 3.1.7 on 2026-01-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0180_merge_20260124'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerfile',
            name='is_readable_by_ai',
            field=models.BooleanField(default=True, help_text='Если галочка стоит, ИИ прочитает текст файла. Если нет — просто отправит ссылку клиенту.', verbose_name='ИИ должен читать этот файл?'),
        ),
    ]
