# Generated by Django 3.1.7 on 2026-01-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0181_answerfile_is_readable_by_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='ai_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistant',
            name='ai_voice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assistant',
            name='first_message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
