# Generated by Django 3.1.7 on 2026-02-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0182_auto_20260130_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='voice_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
