# Generated by Django 3.1.7 on 2026-02-09 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0183_assistant_voice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotlink',
            name='decription',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')])),
                ('opens_at', models.TimeField(blank=True, null=True)),
                ('closes_at', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False, verbose_name='Выходной')),
                ('is_24_hours', models.BooleanField(default=False, verbose_name='Круглосуточно')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='organizations.organization')),
            ],
            options={
                'ordering': ['day_of_week'],
                'unique_together': {('organization', 'day_of_week')},
            },
        ),
    ]
