# Generated by Django 3.1.7 on 2026-02-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0184_auto_20260209_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='voice_assistant_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userassistant',
            name='is_voice_assistant',
            field=models.BooleanField(default=True),
        ),
    ]
