# Generated by Django 3.1.7 on 2026-02-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0185_auto_20260211_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userassistant',
            name='is_voice_assistant',
            field=models.BooleanField(default=False),
        ),
    ]
