# Generated by Django 3.1.7 on 2026-02-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0186_auto_20260211_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='voice_assistant_id',
            field=models.CharField(blank=True, help_text='id агента', max_length=255, null=True),
        ),
    ]
