# Generated by Django 3.1.7 on 2026-02-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0187_auto_20260211_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='catalog_file',
            field=models.FileField(blank=True, help_text='JSON файл с каталогом товаров', null=True, upload_to='assistants_data'),
        ),
    ]
