# Generated by Django 3.1.7 on 2026-03-12 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0192_organization_gemini_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='profitgate_activated',
            field=models.BooleanField(default=False, verbose_name='Profitgate активирован'),
        ),
        migrations.AddField(
            model_name='organization',
            name='profitgate_confirmed',
            field=models.BooleanField(default=False, verbose_name='Profitgate подтвержден'),
        ),
        migrations.CreateModel(
            name='ProfitgateIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=255, verbose_name='Merchant ID')),
                ('endpoint_id', models.CharField(max_length=255, verbose_name='Endpoint ID')),
                ('api_secret', models.CharField(max_length=255, verbose_name='API Secret (Key)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profitgate_integration', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Интеграция Profitgate',
                'verbose_name_plural': 'Интеграции Profitgate',
            },
        ),
    ]
