# Generated by Django 3.1.7 on 2026-03-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0193_auto_20260312_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalpaymentsystemsettings',
            name='payment_system_id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'FreedomPay'), (2, 'PaySy'), (3, 'Libersave'), (4, 'Betapay'), (5, 'CryptoCloud'), (6, 'MaalyPay'), (7, 'ZinaPay'), (8, 'Profitgate')], help_text='ID платежной системы (совместим с существующим кодом)'),
        ),
        migrations.DeleteModel(
            name='ProfitgateIntegration',
        ),
    ]
