# Generated by Django 3.1.7 on 2026-03-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0194_auto_20260313_2210"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistant",
            name="external_api_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assistant",
            name="external_api_key",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="assistant",
            name="external_api_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="assistant",
            name="external_api_path",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
