# Generated by Django 3.1.7 on 2026-03-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0194_auto_20260313_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionalpaymentsystemsettings',
            name='conversion_fee_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Комиссия, которая добавляется к итоговой сумме при конвертации валюты', max_digits=5, verbose_name='Процент при конвертации (%)'),
        ),
    ]
