# Generated by Django 3.1.7 on 2026-03-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0195_assistant_external_api_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistant",
            name="external_api_methods",
            field=models.JSONField(blank=True, default=list),
        ),
    ]