# Generated by Django 3.1.7 on 2026-03-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0196_assistant_external_api_methods"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistant",
            name="external_api_body",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]