from django.urls import path

from transactions.views.stat_views import (
    PartnersTotalStatsView, OrganizationTotalsView, OrganizationTransactionCalendarView,
)
from transactions.views.transaction_views import (
    TransactionCompleteView, TransactionPreprocessView, UserTransactionOrganizationView, UserTotalsView,
    UserTransactionsListView, UserTransactionDetailView, OrganizationTransactionListView,
    OrganizationTransactionRetrieveDestroyView, UserUnprocessedTransactionCountView, UserSaleTotalsView,
    UserSaleTransactionsListView, UserSaleTransactionOrganizationView, OnlineTransactionCompleteView,
    OrganizationUsersTransactionView, OnlineBookingTransactionCompleteView,
    OrganizationBookingTransactionRetrieveDestroyView, RentPaymentRejectView, RentPaymentAcceptView,
    TransactionBookingPreprocessView, TransactionBookingCompleteView, UserSaleRentalTransactionOrganizationView,
    UserSaleRentalTotalsView, OrganizationRentalUsersTransactionView, UserRentalTransactionOrganizationView,
    UserRentalTotalsView, TransactionUserInfoView, TransactionBookingActivate, UserRentalTransactionsDetailListView,
    UserRentalTransactionsListView, UserSaleTransactionsDetailListView, UserRentalSaleTransactionsListView,
    OrganizationRentalCustomerTransactionView, UserRentalUnprocessedTransactionCountView, ResultURLView,
    InitPaymentView, PaymentSuccessView, OnlinePaymentTransactionCompleteView, OrderPaymentAcceptView,
    OrderPaymentRejectView, TransactionPayOfflineView, CashierTransactionCompleteView,
    UserTicketUnprocessedTransactionCountView, UserSaleTicketTransactionOrganizationView, UserSaleTicketTotalsView,
    OrganizationTicketUsersTransactionView, CheckTicketInUsersView, TransactionTicketUserInfoView,
    TransactionTicketActivate, UserSaleTicketTransactionsDetailListView, OrganizationTicketCustomerTransactionView,
    UserTicketTotalsView, UserTicketTransactionOrganizationView, UserTicketSaleTransactionsListView,
    TransactionOwnTicketInfoView, TransactionTicketInfoView, UserTicketTransactionsListView, UserBalanceTotalsView,
    OrganizationBalanceTransactionListView, PayoutSystemListAPIView
)

urlpatterns = [
    path('transactions/', OrganizationTransactionListView.as_view(), name='organization_transactions'),
    path('transactions/<int:pk>/', OrganizationTransactionRetrieveDestroyView.as_view(),
         name='organization_transaction_detail'),
    path('transactions/<int:pk>/booking/', OrganizationBookingTransactionRetrieveDestroyView.as_view(),
         name='organization_booking_transaction_detail'),

    path('transactions/preprocess/', TransactionPreprocessView.as_view(), name='transaction_preprocess'),
    path('transactions/complete/', TransactionCompleteView.as_view(), name='transaction_complete'),
    path('transactions/complete/cashier/', CashierTransactionCompleteView.as_view(), name='transaction_complete'),
    path('transactions/complete/offline/', TransactionPayOfflineView.as_view(), name='transaction_complete_offline'),
    path('transactions/organizations/<int:pk>/users/', OrganizationUsersTransactionView.as_view(),
         name='transactions_organizations_users'),
    path('transactions/organizations/rental/<int:pk>/users/', OrganizationRentalUsersTransactionView.as_view(),
         name='transactions_organizations_rental_users'),
    path('transactions/organizations/rental/<int:pk>/customers/', OrganizationRentalCustomerTransactionView.as_view(),
         name='transactions_organizations_rental_users'),
    path('onlineTransactions/complete/', OnlineTransactionCompleteView.as_view(), name='online_transaction_complete'),

    path('transactions/preprocess/booking/<int:pk>/', TransactionBookingPreprocessView.as_view(),
         name='transaction_booking_preprocess'),
    path('transactions/complete/booking/', TransactionBookingCompleteView.as_view(),
         name='transaction_booking_complete'),
    path('onlinePaymentTransactions/complete/', OnlinePaymentTransactionCompleteView.as_view(),
         name='online_payment_transaction_complete'),
    path('onlineBookingTransactions/complete/', OnlineBookingTransactionCompleteView.as_view(),
         name='online_booking_transaction_complete'),
    path('transactions/order/payment/accept/', OrderPaymentAcceptView.as_view(), name='user_transaction_order_accept'),
    path('transactions/payment/accept/', RentPaymentAcceptView.as_view(), name='user_transaction_accept'),
    path('transactions/<int:pk>/order/reject/', OrderPaymentRejectView.as_view(), name='user_transaction_order_reject'),
    path('transactions/<int:pk>/reject/', RentPaymentRejectView.as_view(), name='user_transaction_reject'),
    path('transactions/booking/user/', TransactionUserInfoView.as_view(), name='transaction_user_info'),
    path('transactions/booking/activate/', TransactionBookingActivate.as_view(),
         name='transaction_booking_activate'),

    path('statistics/totals/', UserTotalsView.as_view(), name='user_totals'),
    path('statistics/saleTotals/', UserSaleTotalsView.as_view(), name='user_sale_totals'),
    path('statistics/totals/rental/', UserRentalTotalsView.as_view(), name='user_rental_totals'),
    path('statistics/saleTotals/rental/', UserSaleRentalTotalsView.as_view(), name='user_sale_rental_totals'),
    path('statistics/transactions/', UserTransactionsListView.as_view(), name='user_transactions'),
    path('statistics/transactions/rental/', UserRentalTransactionsListView.as_view(), name='user_rental_transactions'),
    path('statistics/transactions/rental/<int:pk>/', UserRentalTransactionsDetailListView.as_view(),
         name='user_rental_transactions_detail'),
    path('statistics/saleTransactions/', UserSaleTransactionsListView.as_view(), name='user_sale_tran'),
    path('statistics/saleTransactions/rental/', UserRentalSaleTransactionsListView.as_view(),
         name='user_rental_sale_tran'),
    path('statistics/saleTransactions/rental/<int:pk>/', UserSaleTransactionsDetailListView.as_view(),
         name='user_rental_sale_tran'),
    path('statistics/transactions/<int:pk>/', UserTransactionDetailView.as_view(), name='user_transaction_detail'),
    path('statistics/organizations/', UserTransactionOrganizationView.as_view(), name='transaction_organizations'),
    path('statistics/saleOrganizations/', UserSaleTransactionOrganizationView.as_view(),
         name='sale_transaction_organizations'),
    path('statistics/organizations/rental/', UserRentalTransactionOrganizationView.as_view(),
         name='rental_transaction_organizations'),
    path('statistics/saleOrganizations/rental/', UserSaleRentalTransactionOrganizationView.as_view(),
         name='sale_rental_transaction_organizations'),
    path('statistics/unprocessedTranCount/', UserUnprocessedTransactionCountView.as_view(),
         name='unprocessed_transaction_count'),
    path('statistics/unprocessedTranCount/rental/', UserRentalUnprocessedTransactionCountView.as_view(),
         name='unprocessed_rental_transaction_count'),

    # tickets
    path('statistics/unprocessedTranCount/ticket/', UserTicketUnprocessedTransactionCountView.as_view(),
         name='unprocessed_ticket_transaction_count'),
    path('statistics/saleOrganizations/ticket/', UserSaleTicketTransactionOrganizationView.as_view(),
         name='sale_ticket_transaction_organizations'),
    path('statistics/saleTotals/ticket/', UserSaleTicketTotalsView.as_view(), name='user_sale_ticket_totals'),
    path('transactions/organizations/ticket/<int:pk>/users/', OrganizationTicketUsersTransactionView.as_view(),
         name='transactions_organizations_ticket_users'),
    path('transactions/ticket/', TransactionTicketInfoView.as_view(), name='transaction_ticket'),
    path('transactions/ticket/check_user/', CheckTicketInUsersView.as_view(), name='check_ticket_in_ticket_users'),
    path('transactions/ticket/user/', TransactionTicketUserInfoView.as_view(), name='transaction_ticket_user_info'),
    path('transactions/ticket/own/', TransactionOwnTicketInfoView.as_view(), name='transaction_ticket_own'),
    path('transactions/ticket/activate/', TransactionTicketActivate.as_view(),
         name='transaction_ticket_activate'),
    path('statistics/saleTransactions/ticket/', UserTicketSaleTransactionsListView.as_view(),
         name='user_ticket_sale_tran'),
    path('statistics/saleTransactions/ticket/<int:pk>/', UserSaleTicketTransactionsDetailListView.as_view(),
         name='user_ticket_sale_tran_detail'),
    path('transactions/organizations/ticket/<int:pk>/customers/', OrganizationTicketCustomerTransactionView.as_view(),
         name='transactions_organizations_ticket_users'),
    path('statistics/totals/ticket/', UserTicketTotalsView.as_view(), name='user_ticket_totals'),
    path('statistics/organizations/ticket/', UserTicketTransactionOrganizationView.as_view(),
         name='ticket_transaction_organizations'),
    path('statistics/transactions/ticket/', UserTicketTransactionsListView.as_view(), name='user_ticket_transactions'),

    path('statistics/<int:pk>/partners_totals/', PartnersTotalStatsView.as_view(), name='partners_totals'),
    path('statistics/<int:pk>/totals/', OrganizationTotalsView.as_view(), name='organization_totals'),
    path('orgTransactions/calendar/', OrganizationTransactionCalendarView.as_view(), name='org_client_calendar'),

    # pay
    path('transactions/pay/', InitPaymentView.as_view(), name='init_payment'),
    path('transactions/result/', ResultURLView.as_view(), name='result_url'),
    path('transactions/success/', PaymentSuccessView.as_view(), name='success_url'),

    # balance
    path('transactions/balance/', OrganizationBalanceTransactionListView.as_view(),
         name='organization_balance_transactions'),
    path('statistics/balance/totals/', UserBalanceTotalsView.as_view(), name='user_balance_totals'),
    path('transactions/payout-system/', PayoutSystemListAPIView.as_view(), name='payout_systems_list')

]
