# Generated by Django 3.1.7 on 2022-03-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=255, unique=True)),
                ('text', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failure', 'failure'), ('not_yet', 'not_yet')], default='not_yet', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
