# Generated by Django 3.1.7 on 2022-03-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_sender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('success', 'success'), ('failure', 'failure')], max_length=20, null=True),
        ),
    ]
