# Generated by Django 3.1.7 on 2022-03-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_sender', '0002_auto_20220313_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmodel',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
    ]
