# Generated by Django 3.0.8 on 2020-07-14 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0013_auto_20200714_1501'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0004_auto_20200712_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_percent', models.PositiveSmallIntegerField(default=0)),
                ('savings', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('discount_type', models.CharField(choices=[('fixed', 'fixed'), ('cumulative', 'cumulative'), ('manual', 'manual')], default='manual', max_length=20)),
                ('is_processed', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bought_transactions', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(default='KGS', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='common.Currency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='organizations.Organization')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_transactions', to=settings.AUTH_USER_MODEL)),
                ('source_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='organizations.DiscountCard')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
