# Generated by Django 3.0.8 on 2020-07-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
