# Generated by Django 3.0.8 on 2020-08-19 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_flags_data_migration'),
        ('transactions', '0002_auto_20200716_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='employee_avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.File'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='employee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='employee_role',
            field=models.CharField(default='Кассир', max_length=255),
            preserve_default=False,
        ),
    ]
