# Generated by Django 3.0.8 on 2020-09-13 23:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20200819_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='from_cashback',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='discount_type',
            field=models.CharField(choices=[('fixed', 'fixed'), ('cumulative', 'cumulative'), ('cashback', 'cashback'), ('manual', 'manual')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
