# Generated by Django 3.0.8 on 2020-09-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20200913_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='to_cashback',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
