# Generated by Django 3.0.8 on 2021-01-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0006_auto_20210111_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'offline')], default='offline',
                                   max_length=20),
        ),
    ]
