# Generated by Django 3.0.8 on 2021-01-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='delivery_type',
            field=models.CharField(choices=[('cash_courier', 'cash_courier'), ('self_pickup', 'self_pickup')], default='self_pickup', max_length=20),
        ),
    ]
