# Generated by Django 3.0.8 on 2021-01-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_transaction_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('rejected', 'in_progress'), ('accepted', 'accepted')], default='accepted', max_length=20),
        ),
    ]
