# Generated by Django 3.1.7 on 2021-03-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_auto_20210114_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fixed_cart',
            field=models.JSONField(null=True),
        ),
    ]
