# Generated by Django 3.1.7 on 2021-04-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_transaction_fixed_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='delivery_type',
            field=models.CharField(choices=[('cash_courier', 'cash_courier'), ('self_pickup', 'self_pickup'), ('cart_checkout', 'cart_checkout')], default='self_pickup', max_length=20),
        ),
    ]
