# Generated by Django 3.1.7 on 2021-04-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_auto_20210411_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='purchase_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
