# Generated by Django 3.1.7 on 2021-05-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_transaction_purchase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='display_time',
            field=models.DateTimeField(null=True),
        ),
    ]
