# Generated by Django 3.1.7 on 2023-03-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_transaction_display_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(choices=[('in_progress', 'in_progress'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='in_progress', max_length=20),
        ),
    ]
