# Generated by Django 3.1.7 on 2023-03-16 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_transaction_payment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='payment_type',
            new_name='payment_status',
        ),
    ]
