# Generated by Django 3.1.7 on 2023-03-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_auto_20230316_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(choices=[('in_progress', 'in_progress'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('refunded', 'refunded')], default='in_progress', max_length=20),
        ),
    ]
