# Generated by Django 3.1.7 on 2023-07-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_auto_20230320_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'cash'), ('bankcard', 'bankcard')], default='cash', max_length=20),
        ),
    ]
