# Generated by Django 3.1.7 on 2023-07-13 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_transaction_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment_type',
        ),
    ]
