# Generated by Django 3.1.7 on 2023-07-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_remove_transaction_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='delivery_type',
            field=models.CharField(choices=[('cash_courier', 'cash_courier'), ('self_pickup', 'self_pickup'), ('cart_checkout', 'cart_checkout'), ('online_payment', 'online_payment')], default='self_pickup', max_length=20),
        ),
    ]
