# Generated by Django 3.1.7 on 2023-09-11 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0051_auto_20230117_1218'),
        ('organizations', '0102_organization_payment_with_confirmation'),
        ('transactions', '0020_auto_20230713_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16)),
                ('currency', models.ForeignKey(default='KGS', on_delete=django.db.models.deletion.PROTECT, to='common.currency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='organizations.organization')),
            ],
        ),
    ]
