# Generated by Django 3.1.7 on 2023-09-14 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0051_auto_20230117_1218'),
        ('transactions', '0021_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner_name_on_card', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=16)),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('fee_percent', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.file')),
            ],
        ),
        migrations.AddField(
            model_name='balance',
            name='payment_systems',
            field=models.ManyToManyField(to='transactions.PayoutSystem'),
        ),
    ]
