# Generated by Django 3.1.7 on 2023-09-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_auto_20230914_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='payment_systems',
            new_name='payout_systems',
        ),
    ]
