# Generated by Django 3.1.7 on 2023-09-15 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0051_auto_20230117_1218'),
        ('transactions', '0023_auto_20230914_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payoutsystem',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='payoutsystem',
            name='owner_name_on_card',
        ),
        migrations.RemoveField(
            model_name='payoutsystem',
            name='transfer_amount',
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name_on_card', models.CharField(max_length=255)),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.file')),
                ('payout_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipients', to='transactions.payoutsystem')),
            ],
        ),
    ]
