# Generated by Django 3.1.7 on 2023-09-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_auto_20230915_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='card_number',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
