# Generated by Django 3.1.7 on 2023-09-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0025_recipient_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fee_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'offline'), ('withdrawal', 'withdrawal')], default='offline', max_length=20),
        ),
    ]
