# Generated by Django 3.1.7 on 2023-09-21 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0103_organization_show_followers'),
        ('transactions', '0027_transaction_fee_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='organizations.organization'),
        ),
    ]
