# Generated by Django 3.1.7 on 2023-09-21 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0028_recipient_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='organization',
        ),
    ]
