# Generated by Django 3.1.7 on 2023-09-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0030_auto_20230926_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='withdrawal_type',
            field=models.CharField(choices=[('bankcard', 'bankcard'), ('swift', 'swift')], default='bankcard', max_length=20),
        ),
    ]
