# Generated by Django 3.1.7 on 2023-10-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0031_transaction_withdrawal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='currency',
            field=models.CharField(choices=[('KGS', 'KGS'), ('TRC20', 'TRC20')], default='KGS', max_length=20),
        ),
    ]
