# Generated by Django 3.1.7 on 2023-10-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0032_auto_20231019_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('in_progress', 'in_progress'), ('under_review', 'under_review'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('error', 'error')], default='in_progress', max_length=20),
        ),
    ]
