# Generated by Django 3.1.7 on 2023-11-01 09:10

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0035_auto_20231030_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_info',
            field=models.JSONField(decoder=common.utils.DecimalDecoder, encoder=common.utils.DecimalEncoder, null=True),
        ),
    ]
