# Generated by Django 3.1.7 on 2023-11-06 09:42

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0036_transaction_payment_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, help_text='File that you want to store', null=True, upload_to=common.utils.upload_file_with_unique_name)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, related_name='transactions', to='transactions.TransactionFile'),
        ),
    ]
