# Generated by Django 3.1.7 on 2023-11-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0037_auto_20231106_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='transactions.TransactionFile'),
        ),
    ]
