# Generated by Django 3.1.7 on 2023-11-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0038_auto_20231106_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionfile',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='transactionfile',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
