# Generated by Django 3.1.7 on 2023-11-06 11:08

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0039_auto_20231106_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionfile',
            name='file',
            field=models.FileField(blank=True, help_text='File that you want to store', null=True, upload_to=common.utils.upload_transaction_file_with_unique_name),
        ),
    ]
