# Generated by Django 3.1.7 on 2024-06-12 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0127_auto_20240611_0630'),
        ('transactions', '0041_auto_20231106_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='organizations.assistant'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'offline'), ('withdrawal', 'withdrawal'), ('assistant', 'assistant')], default='offline', max_length=20),
        ),
    ]
