# Generated by Django 3.1.7 on 2024-06-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0042_auto_20240612_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='assistant',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'offline'), ('withdrawal', 'withdrawal')], default='offline', max_length=20),
        ),
    ]
