# Generated by Django 3.1.7 on 2024-06-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0043_auto_20240612_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'offline'), ('withdrawal', 'withdrawal'), ('assistant', 'assistant')], default='offline', max_length=20),
        ),
    ]
