# Generated by Django 3.1.7 on 2025-05-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0044_auto_20240612_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'offline'), ('withdrawal', 'withdrawal'), ('assistant', 'assistant'), ('org_subscription', 'org_subscription')], default='offline', max_length=20),
        ),
    ]
