# Generated by Django 3.1.7 on 2025-05-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0045_auto_20250520_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
