# Generated by Django 3.1.7 on 2025-06-03 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_userapppurchase'),
        ('organizations', '0149_service_is_application'),
        ('transactions', '0046_transaction_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user_app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='applications.userapp'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'offline'), ('withdrawal', 'withdrawal'), ('assistant', 'assistant'), ('org_subscription', 'org_subscription'), ('user_app', 'user_app')], default='offline', max_length=20),
        ),
    ]
