# Generated by Django 3.1.7 on 2025-12-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0047_auto_20250603_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='discount_coupon',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='product_coupon',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
