# Generated by Django 3.1.7 on 2025-12-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0048_auto_20251208_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='product_coupon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
