# Generated by Django 3.1.7 on 2025-12-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0049_auto_20251208_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='product_coupon',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
