# Generated by Django 3.0.8 on 2020-10-03 17:45

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0036_types_categories_translation_data_migration'),
        ('common', '0010_auto_20200926_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('name_ru', models.CharField(max_length=64, null=True)),
                ('name_en', models.CharField(max_length=64, null=True)),
                ('name_tr', models.CharField(max_length=64, null=True)),
            ],
            options={
                'verbose_name_plural': 'Main categories',
            },
        ),
        migrations.CreateModel(
            name='ItemSubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('name_ru', models.CharField(max_length=64, null=True)),
                ('name_en', models.CharField(max_length=64, null=True)),
                ('name_tr', models.CharField(max_length=64, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='shop.ItemCategory')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_categories', to='organizations.Organization')),
            ],
            options={
                'verbose_name_plural': 'Item categories',
                'ordering': ('-organization', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('article', models.CharField(blank=True, max_length=64, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('youtube_links', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('images', models.ManyToManyField(blank=True, related_name='shop_items', to='common.File')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_items', to='organizations.Organization')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_in_category', to='shop.ItemSubcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
