# Generated by Django 3.0.8 on 2020-10-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'verbose_name_plural': 'Item categories'},
        ),
        migrations.AlterModelOptions(
            name='itemsubcategory',
            options={'ordering': ('-organization', 'name'), 'verbose_name_plural': 'Item subcategories'},
        ),
        migrations.AddField(
            model_name='shopitem',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
