# Generated by Django 3.0.8 on 2020-10-19 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_in_category', to='shop.ItemSubcategory'),
        ),
    ]
