# Generated by Django 3.0.8 on 2020-11-05 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0006_auto_20201104_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=225)),
                ('apartment', models.CharField(max_length=36)),
                ('intercom', models.CharField(max_length=36)),
                ('entrance', models.CharField(max_length=36)),
                ('floor', models.CharField(max_length=36)),
                ('phone', models.CharField(max_length=36)),
                ('comment', models.CharField(max_length=36)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_infos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
