# Generated by Django 3.0.8 on 2020-11-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20201112_1635'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.UniqueConstraint(fields=('user', 'item'), name='unique_complaint_from_user'),
        ),
    ]
