# Generated by Django 3.0.8 on 2020-12-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20201119_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='comment',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
