# Generated by Django 3.0.8 on 2020-12-13 08:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_shopitem_instagram_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 8, 57, 3, 526794, tzinfo=utc)),
        ),
    ]
