# Generated by Django 3.0.8 on 2020-12-16 09:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20201213_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 16, 9, 41, 57, 738163, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 16, 9, 41, 57, 738129, tzinfo=utc)),
        ),
    ]
