# Generated by Django 3.0.8 on 2020-12-17 08:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20201216_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 8, 15, 38, 938524, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 8, 15, 38, 938487, tzinfo=utc)),
        ),
    ]
