# Generated by Django 3.0.8 on 2020-12-18 12:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20201217_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 12, 34, 8, 854279, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 12, 34, 8, 854207, tzinfo=utc)),
        ),
    ]
