# Generated by Django 3.0.8 on 2020-12-21 11:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20201218_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 21, 11, 42, 49, 364710, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 21, 11, 42, 49, 364675, tzinfo=utc)),
        ),
    ]
