# Generated by Django 3.0.8 on 2020-12-24 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20201222_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopitem',
            name='instagram_data',
        ),
    ]
