# Generated by Django 3.0.8 on 2020-12-26 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_shopitem_instagram_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInstagramData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_pk', models.CharField(max_length=255)),
                ('thumbnail_url', models.URLField(max_length=500)),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_data', to='shop.ShopItem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
