# Generated by Django 3.0.8 on 2021-01-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_iteminstagramdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='apartment',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='entrance',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='floor',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='intercom',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
