# Generated by Django 3.0.8 on 2021-01-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20210108_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='apartment',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='comment',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='entrance',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='floor',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='intercom',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
