# Generated by Django 3.0.8 on 2021-01-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20210108_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminstagramdata',
            name='thumbnail_url',
            field=models.URLField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='iteminstagramdata',
            name='video_url',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
    ]
