# Generated by Django 3.0.8 on 2021-01-13 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_transaction_delivery_type'),
        ('shop', '0023_auto_20210112_1233'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique_cart_for_user_in_organization',
        ),
        migrations.AddField(
            model_name='cart',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart', to='transactions.Transaction'),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_info', to='transactions.Transaction'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(is_open=True), fields=('organization', 'user'), name='unique_cart_for_user_in_organization'),
        ),
    ]
