# Generated by Django 3.1.6 on 2021-02-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_add_subcategories_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='youtube_links',
            field=models.JSONField(null=True),
        ),
    ]
