# Generated by Django 3.1.7 on 2021-03-17 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_auto_20210216_1404'),
        ('shop', '0026_auto_20210213_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='icon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.file'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
