# Generated by Django 3.1.7 on 2021-04-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20210317_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='is_adult',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
