# Generated by Django 3.1.7 on 2021-03-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_itemcategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
