# Generated by Django 3.1.7 on 2021-04-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20210422_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteminstagramdata',
            name='post_pk',
        ),
    ]
