# Generated by Django 3.1.7 on 2021-07-02 11:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_remove_iteminstagramdata_post_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfo',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Для создания местоположения', null=True, srid=4326),
        ),
    ]
