# Generated by Django 3.1.7 on 2021-07-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20210701_0741'),
        ('shop', '0031_deliveryinfo_location'),
    ]

    operations = [
    ]
