# Generated by Django 3.1.7 on 2021-07-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_merge_20210705_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='description_lang',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='name_lang',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
