# Generated by Django 3.1.7 on 2021-07-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20210716_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='status',
            field=models.CharField(choices=[('delivery_status_taken_for_delivery', 'Taken for delivery'), ('delivery_status_set_for_delivery', 'Set for delivery'), ('delivery_status_rejected_by_delivery_service', 'Rejected by delivery service'), ('delivery_status_accepted_by_delivery_service', 'Accepted by delivery service'), ('delivery_status_delivered', 'Delivered'), ('delivery_status_rejected_by_customer', 'Rejected by customer')], default='delivery_status_set_for_delivery', max_length=255),
        ),
    ]
