# Generated by Django 3.1.7 on 2021-07-16 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_auto_20210716_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryinfo',
            name='user',
        ),
    ]
