# Generated by Django 3.1.7 on 2021-07-23 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20210721_1429'),
        ('shop', '0036_delete_deliveryinfo'),
    ]

    operations = [
    ]
