# Generated by Django 3.1.7 on 2021-09-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_merge_20210723_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='is_instagram',
            field=models.BooleanField(default=False),
        ),
    ]
