# Generated by Django 3.1.7 on 2021-09-13 08:01

from django.db import migrations


def transfer_item_instagram(apps, schema_editor):
    ShopItem = apps.get_model('shop.ShopItem')
    items = ShopItem.objects.filter(name='Instagram', price=None, is_updated=False, images__isnull=True)
    for item in items:
        item.is_instagram = True
        item.save()

def rollback_transfer(apps, schema_editor):
    ShopItem = apps.get_model('shop.ShopItem')
    items = ShopItem.objects.filter(name='Instagram', price=None, is_updated=False, images__isnull=True)
    for item in items:
        item.is_instagram = False
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_shopitem_is_instagram'),
    ]

    operations = [
        migrations.RunPython(transfer_item_instagram, rollback_transfer)
    ]
