# Generated by Django 3.1.7 on 2021-09-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_auto_20210913_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopitem',
            name='is_instagram',
        ),
        migrations.AddField(
            model_name='shopitem',
            name='removed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
