# Generated by Django 3.1.7 on 2021-12-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_auto_20210914_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='description_lang',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='name_lang',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
