# Generated by Django 3.1.7 on 2022-03-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_auto_20211206_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='youtube_links',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
