# Generated by Django 3.1.7 on 2022-04-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_auto_20220408_0711'),
        ('shop', '0042_auto_20220323_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='shop_items', to='common.FileVideo'),
        ),
    ]
