# Generated by Django 3.1.7 on 2022-06-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20220616_1505'),
        ('shop', '0044_auto_20220418_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsubcategory',
            name='criteria_subcategory',
            field=models.ManyToManyField(blank=True, related_name='item_subcategories', to='stock.CriteriaSubcategory'),
        ),
    ]
