# Generated by Django 3.1.7 on 2022-07-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_delete_stockcollection'),
        ('shop', '0046_auto_20220620_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='available_sizes',
            field=models.ManyToManyField(blank=True, related_name='shop_items', to='stock.SizeFormat'),
        ),
    ]
