# Generated by Django 3.1.7 on 2022-08-09 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_criteriasubcategory_icon'),
        ('shop', '0047_shopitem_available_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_item', to='stock.sizeformat'),
        ),
    ]
