# Generated by Django 3.1.7 on 2023-01-30 11:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_auto_20221220_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_time_type', models.CharField(blank=True, choices=[('minute', 'minute'), ('hour', 'hour'), ('day', 'day'), ('month', 'month'), ('year', 'year')], max_length=55, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='shopitem',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Для создания местоположения', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='purchase_type',
            field=models.CharField(blank=True, choices=[('product', 'product'), ('rent', 'rent')], default='product', max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='rental_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.rentalperiod'),
        ),
    ]
