# Generated by Django 3.1.7 on 2023-02-17 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_auto_20230130_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='rental_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.rentalperiod'),
        ),
    ]
