# Generated by Django 3.1.7 on 2023-02-22 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_auto_20230222_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings', to='shop.shopitem'),
        ),
    ]
