# Generated by Django 3.1.7 on 2023-03-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_booking_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='rental_period_list',
        ),
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
