# Generated by Django 3.1.7 on 2023-03-02 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_auto_20230302_0725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='end_date',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='start_date',
            new_name='start_time',
        ),
    ]
