# Generated by Django 3.1.7 on 2023-03-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_auto_20230302_0738'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_bookig_for_user_in_organization',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(is_open=True), fields=('organization', 'user'), name='unique_booking_for_user_in_organization'),
        ),
    ]
