# Generated by Django 3.1.7 on 2023-03-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_auto_20230302_1031'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_booking_for_user_in_organization',
        ),
    ]
