# Generated by Django 3.1.7 on 2023-06-15 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0051_auto_20230117_1218'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0059_booking_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_images', to='common.file')),
                ('items', models.ManyToManyField(blank=True, related_name='collections', to='shop.ShopItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
