# Generated by Django 3.1.7 on 2023-06-19 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0060_itemcollection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcollection',
            name='image',
        ),
    ]
