# Generated by Django 3.1.7 on 2023-06-20 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0051_auto_20230117_1218'),
        ('shop', '0061_remove_itemcollection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcollection',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_images', to='common.file'),
        ),
    ]
