# Generated by Django 3.1.7 on 2023-06-28 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0051_auto_20230117_1218'),
        ('shop', '0062_itemcollection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcollection',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_videos', to='common.filevideo'),
        ),
    ]
