# Generated by Django 3.1.7 on 2023-06-28 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0063_itemcollection_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcollection',
            name='video',
        ),
        migrations.AlterField(
            model_name='itemcollection',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_images', to='shop.shopitem'),
        ),
    ]
