# Generated by Django 3.1.7 on 2023-08-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0064_auto_20230628_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='purchase_type',
            field=models.CharField(blank=True, choices=[('product', 'product'), ('rent', 'rent'), ('ticket', 'ticket')], default='product', max_length=55, null=True),
        ),
    ]
