# Generated by Django 3.1.7 on 2023-08-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0066_auto_20230809_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketperiod',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
