# Generated by Django 3.1.7 on 2023-08-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0067_ticketperiod_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketperiod',
            name='is_active',
        ),
        migrations.AddField(
            model_name='shopitem',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
