# Generated by Django 3.1.7 on 2023-08-16 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_auto_20230713_1106'),
        ('shop', '0069_auto_20230816_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', to='transactions.transaction'),
        ),
    ]
