# Generated by Django 3.1.7 on 2023-09-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0070_auto_20230816_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='minimum_purchase',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
