# Generated by Django 3.1.7 on 2023-12-18 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0052_countryandcity'),
        ('shop', '0071_shopitem_minimum_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='citizenship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_items', to='common.country'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_items', to='common.currency'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='current_locations',
            field=models.ManyToManyField(blank=True, related_name='shop_items_current', to='common.CountryAndCity'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='preferred_locations',
            field=models.ManyToManyField(blank=True, related_name='shop_items_preferred', to='common.CountryAndCity'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='salary_from',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='salary_to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
