# Generated by Django 3.1.7 on 2023-12-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0072_auto_20231218_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='purchase_type',
            field=models.CharField(blank=True, choices=[('product', 'product'), ('rent', 'rent'), ('ticket', 'ticket'), ('resume', 'resume')], default='product', max_length=55, null=True),
        ),
    ]
