# Generated by Django 3.1.7 on 2023-12-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0073_auto_20231218_1149'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='shopitem',
        #     name='current_locations',
        # ),
        migrations.AddField(
            model_name='shopitem',
            name='current_locations',
            field=models.JSONField(blank=True, null=True),
        ),
        # migrations.RemoveField(
        #     model_name='shopitem',
        #     name='preferred_locations',
        # ),
        migrations.AddField(
            model_name='shopitem',
            name='preferred_locations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
