# Generated by Django 3.1.7 on 2023-12-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0074_auto_20231219_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='purchase_type',
            field=models.CharField(blank=True, choices=[('product', 'product'), ('rent', 'rent'), ('ticket', 'ticket'), ('resume', 'resume')], default='product', max_length=55, null=True),
        ),
    ]
