# Generated by Django 3.1.7 on 2023-12-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0053_delete_countryandcity'),
        ('shop', '0075_itemcategory_purchase_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopitem',
            name='citizenship',
        ),
        migrations.AddField(
            model_name='shopitem',
            name='citizenship',
            field=models.ManyToManyField(blank=True, related_name='shop_items', to='common.Country'),
        ),
    ]
