# Generated by Django 3.1.7 on 2023-12-21 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0076_auto_20231220_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('languages', models.JSONField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_info', to='shop.shopitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
