# Generated by Django 3.1.7 on 2023-12-21 12:34

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0078_auto_20231221_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeInfoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('file', models.FileField(blank=True, help_text='File that you want to store', null=True, upload_to=common.utils.upload_file_with_unique_name)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='resumeinfo',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='shop.ResumeInfoFile'),
        ),
    ]
