# Generated by Django 3.1.7 on 2023-12-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0079_auto_20231221_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeinfo',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='resume_info', to='shop.ResumeInfoFile'),
        ),
    ]
