# Generated by Django 3.1.7 on 2023-12-21 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0080_auto_20231221_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=255)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_phone_numbers', to='shop.shopitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
