# Generated by Django 3.1.7 on 2023-12-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0081_resumecontacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResumeContacts',
            new_name='ResumePhoneNumber',
        ),
    ]
