# Generated by Django 3.1.7 on 2023-12-21 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0082_auto_20231221_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumephonenumber',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_phone_numbers', to='shop.shopitem'),
        ),
    ]
