# Generated by Django 3.1.7 on 2023-12-22 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0084_resumesocialnetwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeDetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_detail_info', to='shop.shopitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
