# Generated by Django 3.1.7 on 2023-12-22 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0085_resumedetailinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeWorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('start_of_work', models.DateField()),
                ('end_of_work', models.DateField()),
                ('up_to_now', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_work_experience', to='shop.shopitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
