# Generated by Django 3.1.7 on 2024-01-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0088_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='education',
            field=models.ManyToManyField(blank=True, related_name='shop_items', to='shop.Education'),
        ),
    ]
