# Generated by Django 3.1.7 on 2024-01-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0089_shopitem_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='name_tr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
