# Generated by Django 3.1.7 on 2024-01-10 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0090_auto_20240109_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('start_of_study', models.DateField(null=True)),
                ('end_of_study', models.DateField(null=True)),
                ('up_to_now', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_education', to='shop.shopitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
