# Generated by Django 3.1.7 on 2024-01-12 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0109_service_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0091_resumeeducation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_contacts', models.BooleanField(default=True)),
                ('phone_numbers', models.JSONField(blank=True, null=True)),
                ('links', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'in_progress'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='in_progress', max_length=20)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_resumes', to='shop.shopitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_resume', to='organizations.organization')),
                ('sender_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_organization_resume', to='organizations.organization')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_user_resume', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
