# Generated by Django 3.1.7 on 2024-01-12 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0092_resumerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumerequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processed_resume', to=settings.AUTH_USER_MODEL),
        ),
    ]
