# Generated by Django 3.1.7 on 2024-01-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0093_resumerequest_processed_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumerequest',
            old_name='user_contacts',
            new_name='show_contacts',
        ),
    ]
