# Generated by Django 3.1.7 on 2024-01-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0094_auto_20240116_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='name_zh',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_de',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_zh',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='itemsubcategory',
            name='name_de',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='itemsubcategory',
            name='name_zh',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
