# Generated by Django 3.1.7 on 2024-01-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0095_auto_20240118_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumerequest',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
