# Generated by Django 3.1.7 on 2024-02-01 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0112_auto_20240130_0525'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0096_resumerequest_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_shop_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_items', to='organizations.organization'),
        ),
    ]
