# Generated by Django 3.1.7 on 2024-06-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0097_auto_20240201_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='comments_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
