# Generated by Django 3.1.7 on 2024-06-05 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0099_commenttheme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentTheme',
        ),
    ]
