# Generated by Django 3.1.7 on 2024-06-05 12:56

import common.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0100_delete_commenttheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme_type', models.CharField(choices=[('default', 'Default')], max_length=20)),
                ('svg_background', models.FileField(blank=True, help_text='Background SVG file for default theme', null=True, upload_to=common.utils.upload_file_with_unique_name)),
                ('svg_pattern', models.FileField(blank=True, help_text='Pattern SVG file for default theme', null=True, upload_to=common.utils.upload_file_with_unique_name)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCommentTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme_type', models.CharField(choices=[('predefined', 'Predefined'), ('custom', 'Custom')], max_length=20)),
                ('theme_id', models.PositiveIntegerField(blank=True, help_text='ID of the predefined theme', null=True)),
                ('image', models.ImageField(blank=True, help_text='User uploaded image for custom theme', null=True, upload_to=common.utils.upload_file_with_unique_name)),
                ('user', models.OneToOneField(help_text='User who uploaded the custom theme or selected the theme', on_delete=django.db.models.deletion.CASCADE, related_name='user_theme', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
