# Generated by Django 3.1.7 on 2024-06-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0101_commenttheme_usercommenttheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttheme',
            name='theme_type',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
