# Generated by Django 3.1.7 on 2024-06-06 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0054_auto_20240118_0509'),
        ('shop', '0102_auto_20240605_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercommenttheme',
            name='image',
            field=models.OneToOneField(blank=True, help_text='User uploaded image for custom theme', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.file'),
        ),
    ]
