# Generated by Django 3.1.7 on 2024-06-19 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0103_auto_20240606_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='minimum_purchase',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
