# Generated by Django 3.1.7 on 2024-06-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0104_auto_20240619_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='minimum_purchase',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
