# Generated by Django 3.1.7 on 2024-06-26 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0133_chatmessage_is_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0105_auto_20240620_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='organizations.assistant'),
        ),
        migrations.AddField(
            model_name='comment',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='organizations.chat'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.shopitem'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
