# Generated by Django 3.1.7 on 2025-12-26 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0106_auto_20240626_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedShopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_users', to='shop.shopitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_shop_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pinned Shop Item',
                'verbose_name_plural': 'Pinned Shop Items',
            },
        ),
    ]
