# Generated by Django 3.1.7 on 2025-12-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0107_pinnedshopitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Закреплен в организации'),
        ),
    ]
