# Generated by Django 3.1.7 on 2026-01-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0108_shopitem_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
