# Generated by Django 3.1.7 on 2026-01-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0109_shopitem_pinned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='comments/audio/%Y/%m/%d/', verbose_name='Голосовое сообщение'),
        ),
    ]
