# Generated by Django 3.1.7 on 2026-01-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0110_comment_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_audio',
            field=models.FileField(blank=True, null=True, upload_to='comments/user_audio/%Y/%m/%d/', verbose_name='Голосовое сообщение от пользователя'),
        ),
    ]
