# Generated by Django 3.1.7 on 2026-02-10 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0072_alter_aipromptsettings_defaults'),
        ('shop', '0111_comment_user_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsubcategory',
            name='icon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.file'),
        ),
    ]
