# Generated by Django 3.1.7 on 2026-02-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0112_itemsubcategory_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemsubcategory',
            old_name='icon',
            new_name='sub_icon',
        ),
    ]
