map $http_user_agent $user_bots {
     default 0;
     ~*(google|bing|yandex|msnbot) 1;
     ~*(AltaVista|Googlebot|Slurp|BlackWidow|Bot|ChinaClaw|Custo|DISCo|Download|Demon|eCatch|EirGrabber|EmailSiphon|EmailWolf|SuperHTTP|Surfbot|WebWhacker) 1;
     ~*(Express|WebPictures|ExtractorPro|EyeNetIE|FlashGet|GetRight|GetWeb!|Go!Zilla|Go-Ahead-Got-It|GrabNet|Grafula|HMView|Go!Zilla|Go-Ahead-Got-It) 1;
     ~*(rafula|HMView|HTTrack|Stripper|Sucker|Indy|InterGET|Ninja|JetCar|Spider|larbin|LeechFTP|Downloader|tool|Navroad|NearSite|NetAnts|tAkeOut|WWWOFFLE) 1;
     ~*(GrabNet|NetSpider|Vampire|NetZIP|Octopus|Offline|PageGrabber|Foto|pavuk|pcBrowser|RealDownload|ReGet|SiteSnagger|SmartDownload|SuperBot|WebSpider) 1;
     ~*(Teleport|VoidEYE|Collector|WebAuto|WebCopier|WebFetch|WebGo|WebLeacher|WebReaper|WebSauger|eXtractor|Quester|WebStripper|WebZIP|Wget|Widow|Zeus) 1;
     ~*(Twengabot|htmlparser|libwww|Python|perl|urllib|scan|Curl|email|PycURL|Pyth|PyQ|WebCollector|WebCopy|webcraw|WhatsApp) 1;
}

proxy_cache_path /tmp/nginx/cache/prerender levels=1:2 keys_zone=PRERENDER:10m;

server {
    server_name test.apofiz.com;

    client_max_body_size 32m;

    root /root/projects/frontend/dist/;

    location = /.well-known/apple-app-site-association {
        add_header Content-Type text/json;
        return 200 '{"applinks":{"apps":[],"details":[{"appID":"2QYX5D4L9H.com.app.apofiz","paths":["/","/p/*","/organizations/*"]}]}}';
    }

    location = /robots.txt {
        add_header Content-Type text/plain;
        return 200 'User-agent: *\nAllow: /';
    }

    #location ^~ /static/ {
    #    root /root/projects/backend;
    #}

    #location ^~ /media/ {
    #    root /root/projects/backend;
    #}

    #location ^~ /api/ {
    #    include proxy_params;
    #    proxy_pass http://unix:/run/gunicorn.sock;
    #}

    #location ^~ /admin/ {
    #    include proxy_params;
    #    proxy_pass http://unix:/run/gunicorn.sock;
    #}

    location /api/ {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }

    location /admin/ {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }

    location /internal-static/admin/ {
        alias /root/projects/backend/internal-static/admin/;
    }

    location /internal-static/gis/ {
        alias /root/projects/backend/internal-static/gis/;
    }

    location /media/flags-iso/ {
        alias /root/projects/backend/media/flags-iso/;
    }

    location @prerender {
        proxy_cache PRERENDER;
        proxy_cache_background_update on;
        proxy_cache_lock on;
        proxy_cache_lock_age 10s;
        proxy_cache_lock_timeout 10s;
        proxy_cache_valid 200 1d;

        proxy_set_header X-SSARR-Reference-URL https://test.apofiz.com/;

        if ($user_bots = 1) {
            proxy_pass http://127.0.0.1:3000;
        }

        if ($user_bots = 0) {
            rewrite .* /index.html break;
        }
    }

    location / {
        #try_files $uri /index.html;
        try_files $uri @prerender;
    }



    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/test.apofiz.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/test.apofiz.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot





}
server {
    if ($host = test.apofiz.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name test.apofiz.com;
    return 404; # managed by Certbot


}
