# Generated by Django 3.1.7 on 2026-02-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='savedcontact',
            name='saved_conta_user_id_c62b6a_idx',
        ),
        migrations.RemoveIndex(
            model_name='savedcontact',
            name='saved_conta_full_na_a04c60_idx',
        ),
        migrations.AddIndex(
            model_name='savedcontact',
            index=models.Index(fields=['user', '-created_at'], name='saved_conta_user_id_c75e78_idx'),
        ),
        migrations.AddIndex(
            model_name='savedcontact',
            index=models.Index(fields=['full_name'], name='saved_conta_full_na_9a5845_idx'),
        ),
    ]
