# Generated by Django 3.1.7 on 2026-02-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_bot', '0008_usereasycard_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpbotpromptsettings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
