# Generated by Django 3.1.7 on 2025-09-30 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0153_service_is_without_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0002_auto_20250626_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='forwarded_from',
            field=models.ForeignKey(blank=True, help_text='Оригинальный отправитель пересланного сообщения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='forwarded_message',
            field=models.ForeignKey(blank=True, help_text='Исходное сообщение, которое переслали', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwards', to='messenger.chatmessage'),
        ),
        migrations.AddField(
            model_name='messengerchat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images'),
        ),
        migrations.AddField(
            model_name='messengerchat',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this chat belongs to, if any', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messenger_chats', to='organizations.organization'),
        ),
    ]
