# Generated by Django 3.1.7 on 2026-01-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0067_auto_20260108_1111'),
        ('instagram_parsers', '0010_instagramapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.CharField(blank=True, help_text='Start with AIza...', max_length=255, null=True, verbose_name='Gemini API Key')),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'Gemini Api',
                'verbose_name_plural': 'Gemini Api',
            },
        ),
        migrations.CreateModel(
            name='ChatGPTConfig',
            fields=[
            ],
            options={
                'verbose_name': 'ChatGpt Description Api',
                'verbose_name_plural': 'ChatGpt Description Api',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.chatgptsettings',),
        ),
        migrations.CreateModel(
            name='InstagramConfig',
            fields=[
            ],
            options={
                'verbose_name': 'Instagram Api',
                'verbose_name_plural': 'Instagram Api',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('instagram_parsers.instagramapi',),
        ),
    ]
