# Generated by Django 3.1.7 on 2026-01-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPTAssistConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.CharField(blank=True, help_text='Start with AIza...', max_length=255, null=True, verbose_name='Gpt assistant API Key')),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'GPT assistant  Api',
                'verbose_name_plural': 'GPT assistant  Api',
            },
        ),
    ]
