# Generated by Django 3.1.7 on 2026-01-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0002_gptassistconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='geminiconfig',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='geminiconfig',
            name='login',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='geminiconfig',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gptassistconfig',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gptassistconfig',
            name='login',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gptassistconfig',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
