# Generated by Django 3.1.7 on 2026-02-25 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0003_auto_20260109_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiModelConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_model', models.CharField(help_text='Model name to use for text generation, e.g. gemini-2.5-pro', max_length=100, verbose_name='Text Model Name')),
                ('image_model', models.CharField(help_text='Model name to use for image generation, e.g. gemini-3-pro-image-preview', max_length=100, verbose_name='Image Model Name')),
                ('is_active', models.BooleanField(default=False, help_text='Whether this model is active and should be used for generation', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Gemini Model Config',
                'verbose_name_plural': 'Gemini Model Configs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='geminiconfig',
            name='model_for_image',
            field=models.ForeignKey(blank=True, help_text='Model to use for image generation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gemini_configs_image', to='api_keys.geminimodelconfig', verbose_name='Gemini Image Model'),
        ),
        migrations.AddField(
            model_name='geminiconfig',
            name='model_for_text',
            field=models.ForeignKey(blank=True, help_text='Model to use for text generation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gemini_configs_text', to='api_keys.geminimodelconfig', verbose_name='Gemini Text Model'),
        ),
    ]
