# Generated by Django 3.1.7 on 2026-02-25 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0004_auto_20260225_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geminiconfig',
            name='model_for_text',
            field=models.ForeignKey(blank=True, help_text='Model to use for text generation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gemini_configs_text', to='api_keys.geminimodelconfig', verbose_name='Gemini Model'),
        ),
    ]
