# Generated by Django 3.1.7 on 2026-02-25 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0005_auto_20260225_0620'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiImageModelConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(help_text='Model name for image generation, e.g. gemini-3-pro-image-preview', max_length=100, verbose_name='Model Name')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Gemini Image Model',
                'verbose_name_plural': 'Gemini Image Models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeminiTextModelConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(help_text='Model name for text generation, e.g. gemini-2.5-pro', max_length=100, verbose_name='Model Name')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Gemini Text Model',
                'verbose_name_plural': 'Gemini Text Models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='geminiconfig',
            name='model_for_image',
            field=models.ForeignKey(blank=True, help_text='Model to use for image generation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gemini_configs', to='api_keys.geminiimagemodelconfig', verbose_name='Image Model'),
        ),
        migrations.AlterField(
            model_name='geminiconfig',
            name='model_for_text',
            field=models.ForeignKey(blank=True, help_text='Model to use for text generation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gemini_configs', to='api_keys.geminitextmodelconfig', verbose_name='Text Model'),
        ),
        migrations.DeleteModel(
            name='GeminiModelConfig',
        ),
    ]
