# Generated by Django 3.1.7 on 2026-03-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0006_auto_20260225_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_key_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='AWS Access Key ID')),
                ('secret_access_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='AWS Secret Access Key')),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'AWS Config',
                'verbose_name_plural': 'AWS Configs',
            },
        ),
    ]
