HOMEPAGE_BANNERS_COUNT = 12
HOMEPAGE_ORGS_IN_CATEGORIES_COUNT = 12
HOMEPAGE_MIN_PARTNERS_THRESHOLD = 4
HOMEPAGE_MIN_ORDERED_PARTNERS_THRESHOLD = 2
HOMEPAGE_PARTNERS_COUNT = 12

FIXED = 'fixed'
CUMULATIVE = 'cumulative'
CASHBACK = 'cashback'
TYPES = (
    (FIXED, FIXED),
    (CUMULATIVE, CUMULATIVE),
    (CASHBACK, CASHBACK),
)