HOMEPAGE_BANNERS_COUNT = 12
HOMEPAGE_ORGS_IN_CATEGORIES_COUNT = 12
HOMEPAGE_MIN_PARTNERS_THRESHOLD = 4
HOMEPAGE_MIN_ORDERED_PARTNERS_THRESHOLD = 2
HOMEPAGE_PARTNERS_COUNT = 12

MAX_ORGANIZATIONS_PER_USER = 3

INSTAGRAM_POSTS_TO_PARSE = 100

HOTLINK_ITEM = 'item'
HOTLINK_ORGANIZATION = 'organization'
HOTLINK_EXTERNAL = 'external'

HOTLINK_TYPES = (
    (HOTLINK_ITEM, HOTLINK_ITEM),
    (HOTLINK_ORGANIZATION, HOTLINK_ORGANIZATION),
    (HOTLINK_EXTERNAL, HOTLINK_EXTERNAL),
)
