HOMEPAGE_BANNERS_COUNT = 12
HOMEPAGE_ORGS_IN_CATEGORIES_COUNT = 12
HOMEPAGE_MIN_PARTNERS_THRESHOLD = 4
HOMEPAGE_MIN_ORDERED_PARTNERS_THRESHOLD = 2
HOMEPAGE_PARTNERS_COUNT = 12

MAX_ORGANIZATIONS_PER_USER = 3

INSTAGRAM_POSTS_TO_PARSE = 100

HOTLINK_URL = 'link'
HOTLINK_CONTACT = 'contact'
HOTLINK_COLLECTION = 'collection'
HOTLINK_PARTNERS = 'partners'

HOTLINK_URL_EXTERNAL = 'external'
HOTLINK_URL_ITEM = 'item'
HOTLINK_URL_ORGANIZATION = 'organization'

HOTLINK_TYPES = (
    (HOTLINK_URL, HOTLINK_URL),
    (HOTLINK_CONTACT, HOTLINK_CONTACT),
    (HOTLINK_COLLECTION, HOTLINK_COLLECTION),
    (HOTLINK_PARTNERS, HOTLINK_PARTNERS),
)

HOTLINK_INTERNAL_LINK_DOMAINS = ('apofiz.com', 'www.apofiz.com', 'test.apofiz.com', 'www.test.apofiz.com', 'test2.apofiz.com')


VERIFIED = "verified"
NOT_VERIFIED = "not_verified"
UNDER_REVIEW = "under_review"
VERIFICATIONS_STATUS = (
    (VERIFIED, VERIFIED),
    (NOT_VERIFIED, NOT_VERIFIED),
    (UNDER_REVIEW, UNDER_REVIEW)
)
