# Generated by Django 3.0.8 on 2020-07-30 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_auto_20200726_1117'),
        ('notifications', '0003_notification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_notifications', to='organizations.Organization'),
        ),
    ]
