# Generated by Django 3.0.8 on 2020-07-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('discount', 'Discount'), ('subscription', 'Subscription'), ('system', 'System'), ('partner', 'Partner')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='notification',
            name='mode',
        ),
    ]
