# Generated by Django 3.0.8 on 2020-07-30 13:14

from django.db import migrations

from notifications.constants import (
    NOTIFICATION_MODES,
    NOTIFICATION_MODE_DISCOUNT,
    NOTIFICATION_MODE_SUBSCRIPTION,
    NOTIFICATION_MODE_SYSTEM, NOTIFICATION_MODE_PARTNER
)


def create_notification_modes(apps, _):
    NotificationMode = apps.get_model('notifications', 'NotificationMode')

    NotificationMode.objects.create(name=NOTIFICATION_MODE_DISCOUNT)
    NotificationMode.objects.create(name=NOTIFICATION_MODE_SUBSCRIPTION)
    NotificationMode.objects.create(name=NOTIFICATION_MODE_SYSTEM)
    NotificationMode.objects.create(name=NOTIFICATION_MODE_PARTNER)


class Migration(migrations.Migration):
    dependencies = [
        ('notifications', '0005_auto_20200730_1314'),
    ]

    operations = [
        migrations.RunPython(create_notification_modes),
    ]

