# Generated by Django 3.0.8 on 2020-07-30 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20200730_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='mode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='notifications.NotificationMode'),
            preserve_default=False,
        ),
    ]
