# Generated by Django 3.0.8 on 2020-07-30 13:14

from django.db import migrations

from notifications.constants import (
    NOTIFICATION_MODES,
    DISCOUNT_NOTIFICATION_MODE,
    SUBSCRIPTION_NOTIFICATION_MODE,
    SYSTEM_NOTIFICATION_MODE, PARTNER_MODE
)


def create_notification_modes(apps, _):
    NotificationMode = apps.get_model('notifications', 'NotificationMode')

    NotificationMode.objects.create(name=DISCOUNT_NOTIFICATION_MODE)
    NotificationMode.objects.create(name=SUBSCRIPTION_NOTIFICATION_MODE)
    NotificationMode.objects.create(name=SYSTEM_NOTIFICATION_MODE)
    NotificationMode.objects.create(name=PARTNER_MODE)


class Migration(migrations.Migration):
    dependencies = [
        ('notifications', '0005_auto_20200730_1314'),
    ]

    operations = [
        migrations.RunPython(create_notification_modes),
    ]

