# Generated by Django 3.0.8 on 2020-07-30 12:40

from django.db import migrations


def create_notification_modes(apps, _):
    NotificationMode = apps.get_model('notifications', 'NotificationMode')

    NotificationMode.objects.create(name='system', type='system')
    NotificationMode.objects.create(name='discount', type='discount')
    NotificationMode.objects.create(name='partner', type='partner')
    NotificationMode.objects.create(name='subscription', type='subscription')


class Migration(migrations.Migration):
    dependencies = [
        ('notifications', '0006_notification_mode'),
    ]

    operations = [
        migrations.RunPython(create_notification_modes),
    ]
