# Generated by Django 3.0.8 on 2020-08-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_generate_notification_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('accept_discount', 'accept_discount'), ('decline_discount', 'decline_discount'), ('new_discount', 'new_discount'), ('new_organization', 'new_organization'), ('followed_to_organization', 'followed_to_organization'), ('organization_followed', 'organization_followed'), ('system', 'system')], default='system', max_length=40),
        ),
    ]
