# Generated by Django 3.0.8 on 2020-08-01 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notification_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_at',)},
        ),
    ]
