# Generated by Django 3.0.8 on 2020-08-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_django', '0005_auto_20170808_1145'),
        ('notifications', '0008_auto_20200801_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsetting',
            name='fcm_device',
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='fcm_device',
            field=models.ManyToManyField(to='fcm_django.FCMDevice'),
        ),
    ]
