# Generated by Django 3.0.8 on 2020-08-04 09:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_auto_20200801_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('accept_discount', 'accept_discount'), ('decline_discount', 'decline_discount'), ('new_discount', 'new_discount'), ('new_organization', 'new_organization'), ('followed_to_organization', 'followed_to_organization'), ('organization_followed', 'organization_followed'), ('system', 'system'), ('accept_partnership', 'accept_partnership'), ('decline_partnership', 'decline_partnership'), ('request_partnership', 'request_partnership')], default='system', max_length=40),
        ),
    ]
