# Generated by Django 3.0.8 on 2020-08-05 06:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_auto_20200804_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
