# Generated by Django 3.0.8 on 2020-08-06 04:41
from __future__ import unicode_literals

from django.db import migrations


def default_settings(apps, _):
    User = apps.get_model('users', 'User')
    NotificationSettings = apps.get_model('notifications', 'NotificationSetting')
    for user in User.objects.all():
        try:
            NotificationSettings.objects.get(user=user)
        except NotificationSettings.DoesNotExist:
            NotificationSettings.objects.create(user=user)


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('notifications', '0012_auto_20200805_0731'),
    ]
    operations = [
        migrations.RunPython(default_settings),
    ]
