# Generated by Django 3.0.8 on 2020-08-06 04:41
from __future__ import unicode_literals

from django.db import migrations


def default_settings(apps, _):
    user = apps.get_model('users', 'User')
    notification_settings = apps.get_model('notifications', 'NotificationSetting')
    for user in user.objects.all():
        try:
            notification_settings.objects.get(user=user)
        except notification_settings.DoesNotExist:
            settings = notification_settings(user=user)
            settings.save()


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('notifications', '0012_auto_20200805_0731'),
    ]
    operations = [
        migrations.RunPython(default_settings),
    ]
