# Generated by Django 3.0.8 on 2020-08-10 09:36

from django.db import migrations

from notifications.constants import NOTIFICATION_MODE_PERSONAL


def create_notification_modes(apps, _):
    NotificationMode = apps.get_model('notifications', 'NotificationMode')

    NotificationMode.objects.create(name=NOTIFICATION_MODE_PERSONAL)


class Migration(migrations.Migration):
    dependencies = [
        ('notifications', '0013_default_settings'),
    ]

    operations = [
        migrations.RunPython(create_notification_modes)
    ]
