# Generated by Django 3.0.8 on 2020-08-10 10:33

from django.db import migrations

from notifications.constants import NOTIFICATION_MODE_SUBSCRIPTION, NOTIFICATION_MODE_PERSONAL


def convert_subscription_mode_to_personal(apps, _):
    NotificationMode = apps.get_model('notifications', 'NotificationMode')
    Notification = apps.get_model('notifications', 'Notification')

    subscription_notification_mode = NotificationMode.objects.get(name=NOTIFICATION_MODE_SUBSCRIPTION)
    personal_notification_mode = NotificationMode.objects.get(name=NOTIFICATION_MODE_PERSONAL)

    Notification.objects.filter(mode=subscription_notification_mode).update(mode=personal_notification_mode)


class Migration(migrations.Migration):
    dependencies = [
        ('notifications', '0014_auto_20200810_0936'),
    ]

    operations = [
        migrations.RunPython(convert_subscription_mode_to_personal)
    ]
