# Generated by Django 3.0.8 on 2020-08-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_auto_20200810_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('accept_discount', 'accept_discount'), ('decline_discount', 'decline_discount'), ('new_discount', 'new_discount'), ('new_organization', 'new_organization'), ('followed_to_organization', 'followed_to_organization'), ('organization_followed', 'organization_followed'), ('system', 'system'), ('accept_partnership', 'accept_partnership'), ('decline_partnership', 'decline_partnership'), ('request_partnership', 'request_partnership'), ('accepted_seller_discount', 'accepted_seller_discount'), ('recruited', 'recruited'), ('changed_position', 'changed_position'), ('dismissed', 'dismissed')], default='system', max_length=40),
        ),
    ]
