# Generated by Django 3.0.8 on 2020-08-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0018_auto_20200811_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('accept_discount', 'accept_discount'), ('decline_discount', 'decline_discount'), ('new_discount', 'new_discount'), ('new_organization', 'new_organization'), ('followed_to_organization', 'followed_to_organization'), ('organization_followed', 'organization_followed'), ('system', 'system'), ('accept_partnership', 'accept_partnership'), ('decline_partnership', 'decline_partnership'), ('request_partnership', 'request_partnership'), ('accepted_seller_discount', 'accepted_seller_discount'), ('recruit', 'recruit'), ('changed_position', 'changed_position'), ('dismissed', 'dismissed'), ('quit', 'quit'), ('changed_position_as_owner', 'changed_position_as_owner'), ('organization_message', 'organization_message'), ('gave_organization', 'gave_organization'), ('owned_organization', 'owned_organization')], default='system', max_length=40),
        ),
    ]
