# Generated by Django 3.0.8 on 2020-09-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0023_auto_20200915_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_tr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
