# Generated by Django 3.0.8 on 2020-09-29 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_django', '0005_auto_20170808_1145'),
        ('notifications', '0024_auto_20200929_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsetting',
            name='fcm_device',
        ),
        migrations.CreateModel(
            name='SettingsToToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('en', 'en'), ('ru', 'ru'), ('tr', 'tr')], default='ru', max_length=25)),
                ('fcm_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcm_django.FCMDevice')),
                ('notification_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.NotificationSetting')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
