# Generated by Django 3.0.8 on 2020-09-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_django', '0005_auto_20170808_1145'),
        ('notifications', '0025_auto_20200929_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='fcm_device',
            field=models.ManyToManyField(through='notifications.SettingsToToken', to='fcm_django.FCMDevice'),
        ),
    ]
