# Generated by Django 3.0.8 on 2020-10-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0026_notificationsetting_fcm_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('withdraw_cashback_client', 'withdraw_cashback_client'), ('charge_cashback_client', 'charge_cashback_client'), ('withdraw_cashback_seller', 'withdraw_cashback_seller'), ('charge_cashback_seller', 'charge_cashback_seller'), ('check_attendance_in', 'check_attendance_in'), ('check_attendance_out', 'check_attendance_out'), ('attendance_in', 'attendance_in'), ('attendance_out', 'attendance_out'), ('accept_discount', 'accept_discount'), ('decline_discount', 'decline_discount'), ('new_discount', 'new_discount'), ('new_organization', 'new_organization'), ('followed_to_organization', 'followed_to_organization'), ('organization_followed', 'organization_followed'), ('system', 'system'), ('accepted_partnership', 'accepted_partnership'), ('declined_partnership', 'declined_partnership'), ('requested_partnership', 'requested_partnership'), ('accepted_seller_discount', 'accepted_seller_discount'), ('get_job', 'get_job'), ('recruit', 'recruit'), ('changed_position', 'changed_position'), ('dismissed', 'dismissed'), ('quit', 'quit'), ('changed_position_as_owner', 'changed_position_as_owner'), ('organization_message', 'organization_message'), ('gave_organization', 'gave_organization'), ('owned_organization', 'owned_organization'), ('sent_message', 'sent_message'), ('accepted_partnership_recipient', 'accepted_partnership_recipient'), ('declined_partnership_recipient', 'declined_partnership_recipient'), ('requested_partnership_recipient', 'requested_partnership_recipient')], default='system', max_length=40),
        ),
    ]
