# Generated by Django 3.0.8 on 2021-01-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0028_auto_20201003_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='product_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
