# Generated by Django 3.0.8 on 2021-01-22 15:10

from django.db import migrations

# Generated by Django 3.0.8 on 2020-07-30 13:14

from django.db import migrations

from notifications.constants import (
    PRODUCT_MODE
)


def create_notification_modes(apps, _):
    NotificationMode = apps.get_model('notifications', 'NotificationMode')

    NotificationMode.objects.create(name=PRODUCT_MODE)


class Migration(migrations.Migration):
    dependencies = [
        ('notifications', '0030_auto_20210122_1458'),
    ]

    operations = [
        migrations.RunPython(create_notification_modes),
    ]
