# Generated by Django 3.1.6 on 2021-02-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0031_product_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='extra_data',
            field=models.JSONField(null=True),
        ),
    ]
