# Generated by Django 3.1.6 on 2021-02-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0032_auto_20210213_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='mode',
            field=models.CharField(choices=[('discount', 'Discount'), ('subscription', 'Subscription'), ('system', 'System'), ('partner', 'Partner'), ('personal', 'Personal'), ('product', 'Product')], max_length=255),
        ),
    ]
