# Generated by Django 3.1.7 on 2021-05-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0033_auto_20210218_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsetting',
            name='organization_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
