# Generated by Django 3.1.7 on 2021-08-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0034_auto_20210528_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='delivery_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
