# Generated by Django 3.1.7 on 2023-03-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0042_auto_20230303_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('accepted_order_client', 'accepted_order_client'), ('accepted_rental_client', 'accepted_rental_client'), ('declined_order_client', 'declined_order_client'), ('declined_rental_client', 'declined_rental_client'), ('requested_order_client', 'requested_order_client'), ('requested_rental_client', 'requested_rental_client'), ('accepted_order', 'accepted_order'), ('accepted_rental', 'accepted_rental'), ('accepted_rental_payment', 'accepted_rental_payment'), ('declined_rental_payment', 'declined_rental_payment'), ('declined_accepted_rental', 'declined_accepted_rental'), ('declined_accepted_rental_client', 'declined_accepted_rental_client'), ('declined_order', 'declined_order'), ('declined_rental', 'declined_rental'), ('requested_order', 'requested_order'), ('requested_rental', 'requested_rental'), ('new_cashback', 'new_cashback'), ('withdraw_cashback_client', 'withdraw_cashback_client'), ('charge_cashback_client', 'charge_cashback_client'), ('withdraw_cashback_seller', 'withdraw_cashback_seller'), ('charge_cashback_seller', 'charge_cashback_seller'), ('check_attendance_in', 'check_attendance_in'), ('check_attendance_out', 'check_attendance_out'), ('attendance_in', 'attendance_in'), ('attendance_out', 'attendance_out'), ('accept_discount', 'accept_discount'), ('decline_discount', 'decline_discount'), ('new_discount', 'new_discount'), ('new_organization', 'new_organization'), ('followed_to_organization', 'followed_to_organization'), ('organization_followed', 'organization_followed'), ('system', 'system'), ('accepted_partnership', 'accepted_partnership'), ('declined_partnership', 'declined_partnership'), ('requested_partnership', 'requested_partnership'), ('accepted_seller_discount', 'accepted_seller_discount'), ('get_job', 'get_job'), ('recruit', 'recruit'), ('changed_position', 'changed_position'), ('dismissed', 'dismissed'), ('quit', 'quit'), ('changed_position_as_owner', 'changed_position_as_owner'), ('organization_message', 'organization_message'), ('gave_organization', 'gave_organization'), ('owned_organization', 'owned_organization'), ('sent_message', 'sent_message'), ('accepted_partnership_recipient', 'accepted_partnership_recipient'), ('declined_partnership_recipient', 'declined_partnership_recipient'), ('requested_partnership_recipient', 'requested_partnership_recipient'), ('for_delivery', 'for_delivery'), ('accepted_by_delivery', 'accepted_by_delivery'), ('sent_to_delivery_by_organization_for_client', 'sent_to_delivery_by_organization_for_client'), ('accepted_by_delivery_for_client', 'accepted_by_delivery_for_client'), ('rejected_by_delivery', 'rejected_by_delivery'), ('rejected_by_delivery_for_client', 'rejected_by_delivery_for_client'), ('rejected_by_delivery_for_organization', 'rejected_by_delivery_for_organization'), ('delivery_delivered', 'delivery_delivered'), ('delivery_delivered_for_client', 'delivery_delivered_for_client'), ('delivery_delivered_for_organization', 'delivery_delivered_for_organization'), ('for_delivery_for_organization', 'for_delivery_for_organization'), ('new_comment', 'new_comment')], default='system', max_length=255),
        ),
    ]
