# Generated by Django 3.1.7 on 2023-09-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0053_auto_20230816_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='ticket_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
