# Generated by Django 3.1.7 on 2024-01-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0062_auto_20240117_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='description_zh',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_zh',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
