# Generated by Django 3.1.7 on 2024-01-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0063_auto_20240118_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='resume_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
