# Generated by Django 3.1.7 on 2024-01-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0064_notificationsetting_resume_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingstotoken',
            name='language',
            field=models.CharField(choices=[('en', 'en'), ('ru', 'ru'), ('tr', 'tr'), ('de', 'de')], default='ru', max_length=25),
        ),
    ]
