# Generated by Django 3.1.7 on 2024-01-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0067_auto_20240123_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingstotoken',
            name='language',
            field=models.CharField(choices=[('en', 'en'), ('ru', 'ru'), ('tr', 'tr'), ('de', 'de'), ('zh', 'zh')], default='ru', max_length=25),
        ),
    ]
